### ISSUE TITLE
Improve cached operations handling and dashboard view

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#1018]
### Current behavior

UI/CLI/Client submission: by default enable the cache mode.
UI: Tabs are empty and only show a link to the original operation.

### Enhancement

 * [x] When the user submits an independent operation via UI/CLI/Client the cache must be disabled by default.
 * [x] When an operation is a pipeline (DAG, hyperparam tuning, parallel) the cache must be disabled by default for the parent but should be enabled for child operations.
 * [ ] ~~UI should resolve all tabs from original operation and display it or just disable all tabs and only allow the overview tab with information about the original operation.~~ Moved to #1127
 * [x] restart should trigger nocache by default.

**Comment by siddygups** [comment]
Definitely agree that restart should trigger nocache.
