### ISSUE TITLE
Files downloading with erroneous GNUzip (tar.gz) extension

### ISSUE THREAD

**Issue by siddygups** [polyaxon/polyaxon#1027]
I am attempting to use RunClient to download 2 artifacts, one file (single pytorch .pt weights file) and one directory (manually added code dir)

when downloading the file, I use download_artifact():
https://github.com/polyaxon/polyaxon/blob/194a3475d7d8b71055a18d1496c120999692a84f/core/polyaxon/client/run.py#L721

This in turn, uses Polystore.download_file(). In line 172, .tar.gz is concatenated to _local_path, which I believe to be a mistake for a file download.
https://github.com/polyaxon/polyaxon/blob/194a3475d7d8b71055a18d1496c120999692a84f/core/polyaxon/stores/polyaxon_store.py#L164-L180

When I attempt to untar, it throws.  If I instead rename to .pt, the file opens fine.

**Comment by mouradmourafiq** [comment]
I introduced this regression in my last fix: https://github.com/polyaxon/polyaxon/commit/9658aff8ed365be3a30576a877b1cfc213d368df#diff-cb1573f728ac093065c213687ad50cf0L172

**Comment by mouradmourafiq** [comment]
`v1.1.7.post4` is out, waiting for some PR to get merged, and will try to release v1.1.8 to clean this mess :)
