### ISSUE TITLE
Unable to run examples in kubernetes cluster

### ISSUE THREAD

**Issue by blgnksy** [polyaxon/polyaxon#1044]
### Describe the bug
I have already installed Polyaxon on my **Kubernetes** cluster using the instructions on [docs](https://polyaxon.com/docs/setup/platform/). I am trying to run the example on [quick start guide](https://polyaxon.com/docs/core/quick-start/). But Polyaxon cli raises an error. 

### To Reproduce
```bash
(plx) ubuntu@master-node:~/polyaxon_env$  polyaxon run --url=https://raw.githubusercontent.com/polyaxon/polyaxon-quick-start/master/experimentation/simple.yml -l
Please provide a valid project.
```

### Environment
Python 3.6.9 (virtual env)
pip 20.2.2.
polyaxon 1.1.7.post4
polyaxon-sdk 1.1.7

Client Version: 1.18.8 
Server Version: 1.18.8

**Comment by mouradmourafiq** [comment]
you need to create a project: https://polyaxon.com/docs/core/quick-start/#create-a-project.

**Comment by blgnksy** [comment]
Thanks @mouradmourafiq
