### ISSUE TITLE
polyaxon-quick-start broken 'section in the documentation' link

### ISSUE THREAD

**Issue by erexer** [polyaxon/polyaxon#1066]
### Unclear documentation

[polyaxon-quick-start](https://github.com/polyaxon/polyaxon-quick-start) has a broken 'section in the documentation' link that throws a 404.

This should instead link to [docs/core/quick-start](https://polyaxon.com/docs/core/quick-start/).

**Comment by mouradmourafiq** [comment]
Thanks!
