### ISSUE TITLE
Can't deploy flower with the chart on k8s 1.16+

### ISSUE THREAD

**Issue by swimablefish** [polyaxon/polyaxon#1096]
### Describe the bug

My k8s cluster is 1.18. It failed when I enabled flower. Then I checked the chart and found the apiVersion was `extensions/v1beta1` which is incompatible to k8s 1.16+

### To reproduce

enable flower and run helm to update the release 

### Expected behavior

The update should be successful

### Environment

k8s 1.18.6
helm 3.2.1

**Comment by mouradmourafiq** [comment]
Thank you for pointing that, adding this to v1.1.9
