### ISSUE TITLE
Show the agent version on the control panel

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#1104]
### Current behavior

The list of agents on the control panel shows information about the token, queues and settings.

### Enhancement

It would be interesting to also show the version of the agent (ex: 1.1.19).

**Comment by mouradmourafiq** [comment]
This makes a lot of sense! Several features are planned to provide much better visibility about the agents and queues states and current usage, see #727 and #728

**Comment by mouradmourafiq** [comment]
Will release in v1.2.0 with a couple of changes in the agents as well.
