### ISSUE TITLE
deleted flagged missed in initialization

### ISSUE THREAD

**Issue by zeyaddeeb** [polyaxon/polyaxon#1107]
### Describe the bug

Getting this error with version `1.1.9`

![image](https://user-images.githubusercontent.com/9543653/94963440-26726900-04c6-11eb-99f3-adaf10452b30.png)

### To reproduce

`polyaxon upgrade && polyaxon run -f poylaxonfile` 

### Expected behavior

Run completed

### Environment
polyaxon 1.1.9

**Comment by mouradmourafiq** [comment]
is there server also v1.1.9?

**Comment by mouradmourafiq** [comment]
you can run `polyaxon version --check`

**Comment by zeyaddeeb** [comment]
```
Current cli version: 1.1.8.


Platform:

-------  --------------------------------
version  1.1.9
dist     ce
auth
-------  --------------------------------

compatibility versions:

--------  -----------------------------------
cli       {'min': '1.0.9', 'latest': '1.1.8'}
platform  {'min': '1.0.9', 'latest': '1.1.8'}
agent     {'min': '1.0.9', 'latest': '1.1.8'}
ui        {'min': '1.0.9', 'latest': '1.1.8'}
--------  -----------------------------------
```

**Comment by zeyaddeeb** [comment]
its an in cluster run, the image running should have `1.1.9` since its doing `pip install -U polyaxon`

**Comment by mouradmourafiq** [comment]
the image is not problem, Polyaxon server 1.1.9 should be compatible with previous clients, but the new client is not compatible with previous servers.

The "deleted" key does not exist on the project serializer (https://github.com/polyaxon/polyaxon/blob/master/platform/coredb/coredb/api/projects/serializers.py) in v1.1.9 that's why I am asking if the server is v1.1.9.

**Comment by mouradmourafiq** [comment]
Just tried an example: 
<img width="1162" alt="Screenshot 2020-10-02 at 22 06 52" src="https://user-images.githubusercontent.com/1261626/94965359-a0711500-04fb-11eb-9a13-781c20730e80.png">

**Comment by mouradmourafiq** [comment]
Can you try this example it's using an image with 1.1.9:

```bash
polyaxon run --url=https://raw.githubusercontent.com/polyaxon/polyaxon-quick-start/master/experimentation/typed.yml -l -P epochs=1
```

**Comment by mouradmourafiq** [comment]
Actually you don't have to, the experiment you are running is definitely using 1.1.9. The issue is the API.

**Comment by zeyaddeeb** [comment]
the example you sent ran fine, the operation ran but the pod pod didn't delete after that. I'll upgrade my cli and see what happens

**Comment by zeyaddeeb** [comment]
I'm getting the same issue

**Comment by mouradmourafiq** [comment]
Can you provide an example to reproduce?

**Comment by zeyaddeeb** [comment]
```
kind create cluster --name dev-cluster
kubectl create ns cool-ns

helm install polyaxon  polyaxon/polyaxon --namespace cool-ns

kubectl port-forward -n cool-ns svc/polyaxon-polyaxon-gateway 8000:80

polyaxon config set --host=http://localhost:8000

polyaxon project create --name default/cool-project

```

Setup the following files

```yaml
version: 1.1
kind: component
tags: [baseline-model]

run:
  kind: job
  container:
    image: zdeebpix/polyaxon-example:latest
    workingDir: "/app"
    command: ["python", "-u", "model.py"]
```

```Dockerfile
FROM python:3.8-slim-buster

WORKDIR /app

RUN apt-get update -y && apt-get install -y gcc
RUN pip3 install -U polyaxon
RUN pip3 install joblib
RUN pip3 install numpy
COPY . .
```

```python
from typing import Any, Dict

from polyaxon import tracking
import logging

RANDOM_STATE = 42


logger = logging.getLogger()


def get_metrics() -> Dict[str, Any]:
    return {"accuracy": 1}


if __name__ == "__main__":

    tracking.init()

    metrics = get_metrics()

    tracking.log_metrics(**metrics)
```

**Comment by mouradmourafiq** [comment]
Your example works just fine, I used your own docker image.

Can you run `helm repo update` before running install/upgrade just to be sure.

**Comment by zeyaddeeb** [comment]
I updated the repo. I'm running version 1.1.9

**Comment by zeyaddeeb** [comment]
I'm using an s3 as artifact store, that shouldn't matter, correct?

**Comment by mouradmourafiq** [comment]
no it should not, I tried your example with minio.

**Comment by zeyaddeeb** [comment]
I see this error on the operation container: 
```
Error from server (BadRequest): container "polyaxon-sidecar" in pod "plx-operation-3f3372e9fcc34efcb015a602470e73f4-pbkvb" is waiting to start: trying and failing to pull image
```

and this is from streams pod

```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5057d27e20>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f506411f1c0>, 1926211.628)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5064e26760>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5064f336d0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5064039760>, 1927803.872)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5057ca0b20>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f50645b5eb0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f50576df0a0>, 1929598.012)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f5064f4f6a0>
```

**Comment by mouradmourafiq** [comment]
Sorry for late reply, it seems like the image `polyaxon/polyaxon-sidecar:1.1.9` was corrupted for some reason, we still need to investigate how this issue happened. We pushed a new image to `polyaxon/polyaxon-sidecar:1.1.9` to fix the corrupted blob for now.

One last thing to watch out for is the cache folder `.polyaxon` if you have an initialized project, normally that cache should be on the .gitignore and .dockerignore, it might contain old caches created with your 1.1.8 cli, and you might have created your docker image with that cache.

**Comment by zeyaddeeb** [comment]
Funny enough, just finished reviewing how the cli works and as soon as I removed `.polyaxon` everything worked again. We can close this for sure.

**Comment by mouradmourafiq** [comment]
Thank you @zeyaddeeb for the quick answers and glad it's working again.
