### ISSUE TITLE
The settings icon does not appear on firefox

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#1109]
### Describe the bug

The settings icon does not appear on firefox.

![Screenshot from 2020-10-06 23-26-05](https://user-images.githubusercontent.com/1316069/95280512-8bfa8880-082b-11eb-93f6-6398c9372649.png)

**Comment by mouradmourafiq** [comment]
We should definitely improve the post login process to  resolve to the default `organization` in a lot of cases it's simple, there's one organization.

This page is the user profile page, you can use the drop down to select an organization, the gear/settings button will be available there.

**Comment by polyaxon-team** [comment]
We will start redirecting to the user's default org instead of the user's profile. The change will be deployed on Monday.
