### ISSUE TITLE
Parallel coordinates metrics & params swap

### ISSUE THREAD

**Issue by gmrukwa** [polyaxon/polyaxon#1114]
### Describe the bug

Adding parallel coordinates plot for a project, the parameters are swapped with the metrics:

![image](https://user-images.githubusercontent.com/1897842/95587559-7a3efe00-0a42-11eb-8e56-f9c7b84c0a39.png)

### To reproduce

1. Navigate to jobs list
2. Click `Visualize` on the top of the table
3. Click `Add` on the right hand side
4. Select `Parallel`
5. Open `dimensions` list

### Expected behavior

Outputs of jobs should be listed as metrics and inputs of the jobs should be listed as params.

### Environment

Polyaxon 1.1.9

**Comment by polyaxon-team** [comment]
Fixed, thank you for reporting 👍
