### ISSUE TITLE
Initializers' failures are not well handled

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#1129]

**Comment by denisoliveirac** [comment]
Does this problem refer to invalid docker images as well? I saw a behavior today that the image is invalid and polyaxon indicated that the process was still running, with no error message. 
![Screenshot from 2020-10-30 17-58-23](https://user-images.githubusercontent.com/1316069/97758471-b4e60480-1add-11eb-80e3-94b7339e4a6f.png)

**Comment by mouradmourafiq** [comment]
Is this the main container or an init container?
