### ISSUE TITLE
Add a way of import files with components and operations

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#1147]
### Use case

Operations can acquire great complexity and create a huge definition file. It would be interesting to have a way to reference files in the local file system.

### Feature description

Create a localRef to handle this or a way to import files.

**Comment by mouradmourafiq** [comment]
Do you mean like [pathRef](https://polyaxon.com/docs/core/specification/operation/#pathref)

**Comment by mouradmourafiq** [comment]
Note that the best way to manage mature components is via the component hub, more on that next Monday.
