### ISSUE TITLE
polyaxon helm chart imagePullSecrets support to bypass ratelimiting

### ISSUE THREAD

**Issue by omerfsen** [polyaxon/polyaxon#1174]
### Current behavior

Current helm chart does not support imagePullSecrets and with new dockerhub rate limitation https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/ pulling image will be limited to 100 per 6 hours to anonymous and 200 per 6 hours for free authenticated tiers. Though paid users will not see this limit.

### Enhancement

Support imagePullSecrets on polyaxon helm chart and use it if it is defined

**Comment by polyaxon-team** [comment]
@omerfsen there's already support for an `imagePullSecrets` in the current chart, [see this line](https://github.com/polyaxon/polyaxon/blob/master/charts/polyaxon/values.yaml#L506).

**Comment by omerfsen** [comment]
I was thinking this is after you deploy the Polyaxon not while installing the helm chart.

**Comment by polyaxon-team** [comment]
For jobs, services/apps, distributed jobs we have a uniform section [environment](https://polyaxon.com/docs/core/specification/environment/) which has among other fields the [imagePullsecrets](https://polyaxon.com/docs/core/specification/environment/#imagepullsecrets). You can define that per operation, or extract a complete configuration as a [preset](https://polyaxon.com/docs/core/scheduling-strategies/presets/).
