### ISSUE TITLE
Enable providing custom git config params for git repository connections

### ISSUE THREAD

**Issue by Ohtar10** [polyaxon/polyaxon#1179]
### Current behavior
Right now, If I want to work with a private repository, which runs with a self-signed certificate, If I do not want nor cannot configure a global git config option `http.sslVerify=false`in the worker nodes to bypass this check, I can simply clone a repository via `git -c http.sslVerify=false clone https://private.git.server/some/repo`.

With polyaxon however, it seems there is no way to pass such configuration options in the connection entries nor in the git dictionary when interacting with repositories. This forces the user to configure the workers with the necessary changes to enable cloning from repositories running with self-signed certificates.

### Enhancement

It would be nice to have an option to specify custom git configuration options per connection so users can add these properties and work effortlessly with these kinds of repositories.

As per slack chat with Bastian, this might be added to the `schema` setting of connections.

**Comment by polyaxon-team** [comment]
A new field will be provided with the git schema:

```yaml
url: ..,
revision: ...
flags: ["--force", "--anotherFlag", "--recursive", "-c http.sslVerify=false"]
```

Those additional flags will be added to the command and can be set globally on the connection definition, or can be used on  per operation using the init git section.
