### ISSUE TITLE
Are there API docs available  ?

### ISSUE THREAD

**Issue by serans1** [polyaxon/polyaxon#118]
Hi, 
Great job. 
Are there any API docs available for the platform?
I wish to create a simplified UI and want to work directly with the server.

**Comment by mouradmourafiq** [comment]
@serans1 Thanks for having interest in Polyaxon.

Do you have any framework in mind for building the UI?
We have already [ui/dashboard](https://github.com/polyaxon/polyaxon/tree/master/client/src) that we would like to extend.

**Comment by mouradmourafiq** [comment]
When you have time can you join the slack channel to chat a bit more. Maybe we can find a way to make your efforts available to everyone?

**Comment by PankeshGupta** [comment]
Hi i want to contribute , can u please add me to the slack channel .

**Comment by mouradmourafiq** [comment]
Hi @PankeshGupta you can visit this [url](https://join.slack.com/t/polyaxon/shared_invite/enQtMzQ0ODc2MDg1ODc0LWY2ZTdkMTNmZjBlZmRmNjQxYmYwMTBiMDZiMWJhODI2ZTk0MDU4Mjg5YzA5M2NhYzc5ZjhiMjczMDllYmQ2MDg) to get access to the slack channel.

**Comment by PankeshGupta** [comment]
Thanks
