### ISSUE TITLE
When a base image is invalid, the job continues to run without any reports

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#1200]
### Describe the bug

I created a job with an image at an address that the cluster does not have access to. Kubernetes presents the error of ImagePullBackOff, however, the job continues running, without presenting any error message in the log.

### To reproduce
```version: 1.1
kind: operation
component:
  version: 1.1
  kind: component
  name: component-test
  description: Test component
  tags:
    - learn
  run:
    kind: job
    init:
      - git:
          revision: xxx
        connection: github-connection-xxx
    container:
      command:
        - sh
        - '-c'
        - >-
          ls -lha
      image: gcr.io/test/invalid_image
      name: polyaxon-main
      workingDir: '{{ globals.artifacts_path }}/github-connection-xxx'
```

### Expected behavior
Any feedback regarding the failure and deleting the workload.

**Comment by mouradmourafiq** [comment]
This is planned, and is related to #1129
We will try to fix this as soon as v1.5 is released.
