### ISSUE TITLE
Update the tag latest of polyaxon-cli

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#1214]
### Current behavior

I'm using the polyaxon-cli docker container integrated with github actions. I would like to use the image as the latest, so as not to have to make manual upgrades in the github actions pipeline. The tag image is no longer being updated and it would be interesting to integrate it into the release pipeline.

Latest tag: https://hub.docker.com/layers/polyaxon/polyaxon-cli/latest/images/sha256-e88ae254f2a6b301467cc048cf4e6b49aabff317951d8c8c09bf636ff6836263?context=explore

### Enhancement

Update the tag latest when release a new version.

**Comment by mouradmourafiq** [comment]
Makes sense.
