### ISSUE TITLE
Offline Ui Plotly Dependency Problem

### ISSUE THREAD

**Issue by smlblbn** [polyaxon/polyaxon#1233]
### Describe the bug

In Helm Common Reference documentation (https://polyaxon.com/docs/setup/platform/common-reference/) UI section, there is an offline flag for accessing UI without internet access. If we set offline flag true, some of the required javascript libraries load from the static path.

polyaxon/polyaxon-api:1.6.0 and polyaxon/polyaxon-api:1.5.4 docker images involve required javascript files for offline mode. Static files exist in "/var/www/static/v1/vendors/js" directory.

"plotly.1.58.4.min.js" is one of the files in this directory. That file is corrupted. If we set offline flag true and open polyaxon dashboard, the dashboard is not shown because of that corrupted javascript library.

The original javascript file can accessible from https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.58.4/plotly.min.js. Some parts of this file do not exist inside the downloaded one.

### To reproduce

For reproducing the problem, you can set UI section configuration with the below configuration and deploy the system on the kubernetes cluster.

```
ui:
  enabled: true
  offline: true
  adminEnabled: true
```

After port forwarding, when accessing polyaxon dashboard from browser open the developer window, you can see the error coming from corrupted files.

### Expected behavior

To verify that the problem is caused by this file, the previously downloaded "plotly.1.58.4.min.js" file added a previously downloaded docker image, and a new docker built with the same name. Following command used for creating a new image. Deploying cluster with changed image, Polyaxon dashboard can be seen.

```
docker run --rm -it -v /new_js_directory:/new_js_directory --entrypoint bash polyaxon/polyaxon-api:1.6.0
cp /new_js_directory/plotly.1.58.4.min.js /var/www/static/v1/vendors/
docker commit --change='ENTRYPOINT ["/bin/bash", "./entrypoint.sh"]' "replace_with_container_name" polyaxon/polyaxon-api:1.6.0
```

After that change polyaxon dashboard becomes functional. If we use a corrupted javascript file polyaxon dashboard is not functional.

### Environment

Ubuntu 18:04
minikube version: v1.17.1
helm version: v3.4.1
polyaxon version 1.5.4 and 1.6.0

**Comment by polyaxon-team** [comment]
Thank you for reporting, we will fix this issue with v1.6.1.
