### ISSUE TITLE
Expose a simple way of injecting ssh server into the service kind

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#1243]
### Use case

> Hello, I am wondering if it is possible to run the service in Polyaxon such that I can use my PyCharm with remote interpreter (let's say via ssh connection). Anyone tried such option?

### Feature description

Component spec:

  * An SSH server needs to be injected in the container.
  * A port forward needs to be created for 22.
  * Auto-config a host entry .ssh/config.

Gateway changes:

 * For nginx based gateway: we either need to expose NodePort or to make sure the nginx extension with stream support is enabled.
 * For istio based gateway: it seems like initially it's not going to be possible.

### Alternatives

Allow the user to control the underlying service configuration as requested by this user:

> I’ve noticed that a Polyaxon Service creates a Kubernetes service of type ClusterIP. Is there a way to change the type to LoadBalancer? I would like to assign an external IP (doesn’t need to be an elastic IP) so that I can access the main container of the service with SSH

Not sure how this will work with the rest of the system, but we should add a flag to the service kind, e.g. `isExternal: true` to show that the service is not exposed by the gateway, in this case Polyaxon will only manage the reconciliation process with the operator, provide the APIs to stop/restart/resume the service, and provide information from the UI/CLI to view the external service as well as predefined `kubectl` commands.

### For Polyaxon Agent

We should only allow users with `Admin` roles to start such services.  Or at the very least add a configuration on the project/organization level to allow cluster admins to allow/disallow this type of services.

### More context from the slack discussion
> It’s not possible to change this service type. We use headless services and control access via the gateway, this allow us to provide nice external url to those services (owner/project/run-uuid/), hidden inside the cluster -> no accidental service exposing private data from a non-k8s expert, control of auth and permissions,…
I think the SSH case is something that we need to think about, while ensuring it also gets exposed with the same assumptions. Or just allow users to change the behavior while documenting the results and behavior.

**Comment by elgalu** [comment]
Hi, is this something that cannot be solved via `kubectl exec` ? 

If not, an option would be to check how Okteto (open source) does it: https://okteto.com/docs/reference/ssh-server/

**Comment by mouradmourafiq** [comment]
This is a stale issue, we actually shipped a feature called "shell" that is enabled by default on all jobs and services. Currently available in the UI and next minor release will be available in the CLI as well with `polyaxon ops shell`.

<img width="1438" alt="Screenshot 2021-09-11 at 21 43 18" src="https://user-images.githubusercontent.com/1261626/132959708-6a118427-6f04-4924-ab47-594724f73d7a.png">

<img width="1438" alt="Screenshot 2021-09-11 at 21 45 16" src="https://user-images.githubusercontent.com/1261626/132959722-dbb3fa66-1af9-4fb4-aaf7-1dd3e95d4d45.png">

<img width="1436" alt="Screenshot 2021-08-17 at 18 56 22" src="https://user-images.githubusercontent.com/1261626/132959738-53cd4c7c-01bb-4e01-a055-7720aa9bd23f.png">
