### ISSUE TITLE
Jobs table doesn't update correctly when jobs are deleted

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#1246]
### Describe the bug

When deleting jobs from the UI the table doesn't automatically update and keeps trailing empty rows that only disappear after a reloading the page or clicking the "Refresh" button.

### To reproduce

https://user-images.githubusercontent.com/13285808/112624316-c4b80980-8e2d-11eb-949a-f0087ac057b9.mov

### Expected behavior

The UI should immediately update the reflect the current jobs.

### Environment

Polyaxon Cloud: 1.7.4

**Comment by mouradmourafiq** [comment]
This is known, I think we should do this post-virtualization.
