### ISSUE TITLE
tracking.contrib.keras.PolyaxonCallback breaks when learning rate is LearningRateSchedule

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#1248]
### Describe the bug

TensorFlow Keras optimizers can use [`keras.optimizers.schedules.LearningRateSchedule`](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/LearningRateSchedule) as learning rates. This breaks the `tracking.contrib.keras.PolyaxonCallback` callback as it assumes that learning rates are either Tensors or floating point values:
https://github.com/polyaxon/polyaxon/blob/bbc38cb4a759acdf14d35bbe1ad5687869fe0c09/core/polyaxon/tracking/contrib/keras.py#L97-L101

### To reproduce

Construct a Keras model that uses an optimizer with a learning rate schedule. `tracking.contrib.keras.PolyaxonCallback` will throw
```python-traceback
File "/usr/local/lib/python3.8/dist-packages/polyaxon/tracking/contrib/keras.py", line 97, in on_train_begin
params["learning_rate"] = sanitize_np_types(
File "/usr/local/lib/python3.8/dist-packages/polyaxon/utils/np_utils.py", line 30, in sanitize_np_types
if math.isnan(value) or math.isinf(value):
TypeError: must be real number, not LearningRateSchedule
```

### Expected behavior
`tracking.contrib.keras.PolyaxonCallback` should not throw.

### Environment

Polyaxon Cloud 1.7.4

**Comment by mouradmourafiq** [comment]
This is bad, we'll release v1.7.5 next week with a fix for this.
Added some try/catch to avoid breaking training.
Thanks.
