### ISSUE TITLE
occurred on error when I do "polyaxon admin deploy" or "helm install polyaxon/polyaxon  --namespace=polyaxon --generate-name "  

### ISSUE THREAD

**Issue by wangtingwei1995** [polyaxon/polyaxon#1254]
(py3.8) root@test-k8s-cpu-42:~/polyaxon-charts# helm install polyaxon/polyaxon  --namespace=polyaxon --generate-name
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"

**Comment by polyaxon-team** [comment]
Hi @wangtingwei1995 what Kubernetes version are you using?
If you are on a Kubernetes version less than 1.16, you should add this option:

```
operator:
  useCRDV1Beta1: true
```
