### ISSUE TITLE
'Run' object has no attribute '_exit_handler'

### ISSUE THREAD

**Issue by ahmedo42** [polyaxon/polyaxon#1258]
In pytorch-ignite we provide a wrapper for Polyaxon ,  we are implementing a unified interface for closing every logger after completeing its run.

we want to have the following functionality:

```python
class PolyaxonLogger(BaseLogger)
    def __init__(self, *args: Any, **kwargs: Any):
        try:
            from polyaxon.tracking import Run

            self.experiment = Run(*args, **kwargs)

        except ImportError:
            try:
                from polyaxon_client.tracking import Experiment 

                self.experiment = Experiment(*args, **kwargs)

    def close(self) -> None:
        self.experiment.end()
```
but when calling `close()` , I get the error mentioned in the title of the issue , when inspecting the object it's not initialized properly.

**Comment by mouradmourafiq** [comment]
Thanks for reporting this issue, this is a bug when the run is not managed (i.e. in-cluster) and not offline. We will add handling for this case in the next release.

Most Polyaxon's users will not face this issue since the context in-cluster get initialize correctly.

**Comment by mouradmourafiq** [comment]
If you need to make the CI work on your end, you can add `try: except:` block to the logic inside the `close()` function.
