### ISSUE TITLE
Documentation links to a missing page

### ISSUE THREAD

**Issue by milos-popovic** [polyaxon/polyaxon#1262]
### Missing Documentation

Page https://polyaxon.com/docs/intro/ links to https://polyaxon.com/docs/core/introduction/ which is missing

Sentence:
> To gain a deeper understanding of how Polyaxon can help you iterate faster with your experiments, please take some time to familiarize yourself with the [architecture & experimentation](https://polyaxon.com/docs/core/introduction/)

**Comment by polyaxon-team** [comment]
Thank you, we will push a fix.
