### ISSUE TITLE
Artifacts not shown under Artifacts tab and not downloading properly through web interface.

### ISSUE THREAD

**Issue by minaadel** [polyaxon/polyaxon#1268]
### Describe the bug
After logging references of artifacts using the polyaxon tracking class, the following things happen when interacting with the UI:
* The artifacts are not shown under the main artifacts tab
![image](https://user-images.githubusercontent.com/1820025/114114768-d1366a80-98e1-11eb-83fb-202631607422.png)
* They are however visible under Lineage -> Artifacts, however, when attempting to download them from there, the downloaded files don't contain the original file contents, but rather the following html code.
![image](https://user-images.githubusercontent.com/1820025/114114201-aa2b6900-98e0-11eb-9b0d-695ec9762401.png)
```html
<!DOCTYPE html>
<html>
<head>
    <title>Polyaxon</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" href="/static/images/favicon.ico?version=1"/>
    <link href="/static/vendors/fonts/fonts.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="/static/dist/css/global.min.css" media="all" rel="stylesheet" type="text/css"/>
    <base href="/">
</head>

<body>
<div id="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <div class="jumbotron jumbotron-action">
                <div class="text-center">
                    <img src="/static/images/404.svg" alt="404" height="300">
                </div>
                <div id="main">
                    <p>The page you requested does not exist.</p>
                    <h3><a href="/" title="home" class="brand">Polyaxon</a></h3>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
```
the names of the files downloaded are also misformated:
* b9b0a06922934dadb566d91738f59e0d.txtfile
* b9b0a06922934dadb566d91738f59e0d.event.my-csv.plx

I should note that the files themselves are saved normally in the outputs directory of the persistent volume.

### To reproduce
This excerpt is taken from [https://polyaxon.com/docs/experimentation/tracking/quick-start/](url)
```python

    from polyaxon import tracking
    from polyaxon.polyboard.artifacts import V1ArtifactKind

    ...

    # saving a text file to the current directory, and then moving it to /outputs using log_artifact
    asset_path = "testing.txt"
    with open(asset_path, "w") as f:
        tracking.log_outputs(text_file_path=asset_path)
        f.write("putting content to artifact")
    tracking.log_artifact(path=asset_path, kind=V1ArtifactKind.FILE,
        name="txtfile")
    # saving a text file to /outputs directly, and then logging the reference using log_artifact_ref
    asset_path = tracking.get_outputs_path("file.csv")
    with open(asset_path, "w") as f:
        tracking.log_outputs(csv_file_path=asset_path)
        f.write("Artifact content.")
    tracking.log_artifact_ref(path=asset_path, kind=V1ArtifactKind.CSV, name="my-csv")
```

### Expected behavior
The artifacts should appear in main artifacts tab, and the content of the files downloaded should be:
* putting content to artifact
* Artifact content.

### Environment
microk8s 1.16/edge
polyaxon 1.8.0 and 1.7.4 (tried both)

**Comment by mouradmourafiq** [comment]
Hi, can you give a bit more context about your cluster, I think this issue and #1269 are probably happening because of the wrong artifacts store in your deployment.

If you have more than one node, you will likely have this issue with the default artifacts store definition which is a tmp path on the host node. More details [here](https://polyaxon.com/docs/setup/connections/artifacts/).

**Comment by minaadel** [comment]
This is a microk8s deployment, so single node.
I'm currently using a persistent volume claim integration, but the issues were the same when I was using the default-artifacts-store hostpath integration or my own custom defined hostpath, that being said, this is how it looks.
```
$ microk8s kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS        REASON   AGE
persistent-store                           1Gi        RWX            Retain           Bound    polyaxon/persistent-store-claim     persistent                   14h
pvc-bee3f40c-2760-4c51-a01e-b2c9b307e279   20Gi       RWX            Delete           Bound    container-registry/registry-claim   microk8s-hostpath            14h

$ microk8s kubectl get pvc --all-namespaces
NAMESPACE            NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
container-registry   registry-claim           Bound    pvc-bee3f40c-2760-4c51-a01e-b2c9b307e279   20Gi       RWX            microk8s-hostpath   14h
polyaxon             persistent-store-claim   Bound    persistent-store                           1Gi        RWX            persistent          14h
```

my polyaxon_config.yaml
```
...
# Please do not change this value,
# if you want to provide a custom artifacts store, please use artifactsStore.
# This is used as a fallback when no artifactsStore is provided
defaultArtifactsStore:
  name: default-artifacts-store
  kind: host_path
  schema: {"hostPath": "/tmp/artifactsStore", "mountPath": "/artifactsStore"}

artifactsStore:
  name: my-artifacts-store
  kind: volume_claim
  schema: {"volumeClaim": "persistent-store-claim", "mountPath": "/artifacts"}
...
```
```
$ microk8s kubectl describe -n polyaxon pod polyaxon-polyaxon-streams
...
Volumes:
  my-artifacts-store:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  persistent-store-claim
    ReadOnly:   false
```

The output files themselves are available under the directory of the persistent volume hostPath very normally; each run has it's own folder with the run hash and four subdirectories: resources, plxlogs, outputs and events. All of the files I've created are saved under the outputs folder for each run.

What other information could I provide that would be helpful?

**Comment by mouradmourafiq** [comment]
How did you expose the service to view the UI/API?

**Comment by mouradmourafiq** [comment]
I know that it's mostly single node, but there are people using microk8s clustering: https://microk8s.io/docs/clustering.

I think the issue is probably that you are exposing the API and not the Gateway, I should have thought about it when you mentioned mikrok8s, because you are probably using node port as well, see this https://polyaxon.com/docs/setup/platform/common-reference/#gateway

**Comment by mouradmourafiq** [comment]
As mentioned in the other issues, please expose the gateway and everything will work as expected, the artifacts store change was not necessary, sorry about that.

**Comment by minaadel** [comment]
You were absolutely correct. exposing the gateway as a NodePort, and reverting streams and api back to ClusterIP, and pointing both my web browser and the polyaxon cli at the gateway port did the trick. It was necessary to also add http:// as a prefix to the polyaxon cli config host flag, because it attempted to connect via https.
Otherwise, works like a charm right now. Thank you very much :)
