### ISSUE TITLE
[web-ui] Column header tooltips don't work in Firefox

### ISSUE THREAD

**Issue by AdamHillier** [polyaxon/polyaxon#1285]
### Describe the bug

By default the columns in e.g. tables of jobs are very narrow. This makes the column headers unreadable. E.g.:

![image](https://user-images.githubusercontent.com/7688302/115270001-c8d8fd80-a133-11eb-8962-6c33766e673e.png)

That isn't too much of a problem as long as there are tooltips on hover. On Safari this works as expected: hovering over a column header shows a tooltip with the full column header. Unfortunately, in my testing it does not work in Firefox.

### To reproduce

In Firefox, open a list of jobs, and hover over a column header.

### Expected behavior

A tooltip with the column header is displayed.

### Environment

MacOS 10.15.6, Firefox 87.0.

**Comment by polyaxon-team** [comment]
We can revert the change for the predefined the size, which was the previous behavior.

You can also resize all columns:
<img width="1130" alt="Screenshot 2021-04-19 at 18 25 53" src="https://user-images.githubusercontent.com/24545041/115270770-f4acb100-a13c-11eb-9892-0985e84e70df.png">

**Comment by AdamHillier** [comment]
I don't have any strong feelings about the pre-defined size being collapsed, and I agree that resizing the columns is a workaround, but since the tooltips do work in Safari does that not mean there's a bug that's preventing them being displayed in Firefox?

**Comment by mouradmourafiq** [comment]
@AdamHillier we will check it out, and see if the issue the tooltip is browser feature or a bug in the UI code.

Regarding the predefined sizes, I agree that it was not necessary to set those values given that there's enough space left for the two last columns.

We will update the issue with more info tomorrow.

**Comment by mouradmourafiq** [comment]
This was not a bug, somehow a magic behavior in safari, a change was made to make the UI always show a browser tooltip when hovering a column header in the comparison table, we forced the behavior by setting a `title` property on all columns.

For the predefined sizes, I think it was introduced to prevent the initial horizontal scroll, but the current behavior is not aesthetically better and has a legibility issue, so we will revert that change.
