### ISSUE TITLE
Document autoscaling of preemptible GPU resources

### ISSUE THREAD

**Issue by sotte** [polyaxon/polyaxon#131]
I would like to be able to define a pool of preemptible GPUs that are automatically used whenever I run experiments or do a hyper parameter search. The resources should be freed after the training.

I think this would be a great feature and it would save a lot of money! :)

**Comment by mouradmourafiq** [comment]
@sotte I think that's the current behavior, pods used for training are removed once the experiment is finished. Or did you mean something else?

**Comment by sotte** [comment]
Oh, I was going through the docs and I did not have the impression that that is the current behaviour. If that is the case I think it's really great! (But the docs could/should be clearer.)

Actually, I think this feature deserves a separate tutorial because it's so amazing!

**Comment by jorgemf** [comment]
@sotte, @mouradmourafiq I think you don't understand each other. I think what polyaxon does is to run in a cluster you have already predefined, launching jobs in pods as required. What @sotte wants is to add nodes to the cluster when launching the jobs, so he can add preemptible instances when needed as they are cheaper. You start with a one instance cluster and when a new experiment requires new resources you add them to your cluster to polyaxon can run the required jobs for the experiment.

**Comment by sotte** [comment]
Yes, @jorgemf describes what I want: a minimal cluster that that scales up, with preemtible instances and GPUs, as the workload increases.

**Comment by mouradmourafiq** [comment]
@sotte @jorgemf This could be a nice feature. I think there are already tutorials describing such behavior at least for AWS.

@sotte I just realized that you will be at Pydata, Friday 6th, if you are going to be around the whole day let me know and we can catch up after my presentation.

**Comment by sotte** [comment]
@mouradmourafiq yes I'm at PyData and I'm really looking forward to your talk! I'll be there for the whole conference, so let's catch up.

**Comment by jorgemf** [comment]
@sotte take a look to https://github.com/openai/kubernetes-ec2-autoscaler

**Comment by sotte** [comment]
That looks interesting! Sadly we're using google cloud, but doing something similar should work with GKE as well. I'll try to do some research on the weekend.

Also: https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler

**Comment by wbuchwalter** [comment]
https://github.com/kubernetes/autoscaler is what is used under the scene by GKE, and it also works for AWS and Azure.

**Comment by rogerzklotz** [comment]
From [google docs](https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms#about) it looks like we can use the [built in node scheduling](https://docs.polyaxon.com/customization/customize_node_scheduling/) to accomplish something like this. I haven't had the chance to try this out, does anyone see anything obvious that would make this a bad idea?

**Comment by vfdev-5** [comment]
My 2 cents on the topic, I'm trying to acomplish a similar stuff. What I've done and this works in more or less intended way mostly following the [Polyaxon tutorial on GKE](https://docs.polyaxon.com/tutorials/gke_deployment/kubernetes_on_gke/).

I create a cluster with several node-pools for example:
- default-pool with option `--node-labels=polyaxon=core`
- gpu-preempt for GPU experiments with options: 
```
--node-labels=polyaxon=exp-gpu
--preemptible
--enable-autoscaling
--num-nodes "0"
--min-nodes "0"
--max-nodes "2"
```
this pool has automatically a taint `nvidia.com/gpu:present`

- cpu-preempt without GPU for builds and jobs with options:
```
--node-labels=polyaxon=build_job
--preemptible
--enable-autoscaling
--num-nodes "0"
--min-nodes "0"
--max-nodes "2"
```
and I use the following `polyaxon-config.yml`:
```
nodeSelectors:
  core:
    polyaxon: core
  experiments:
    polyaxon: exp-gpu
    polyaxon: exp-small-gpu
  builds:
    polyaxon: build_job
  jobs:
    polyaxon: build_job

tolerations:
  experiments:
    - key: nvidia.com/gpu
      operator: Equal
      value: present
```

When I start an experiment then the docker image building is done with `cpu-preempt` node and the experiment is run with `gpu-preempt` node. All nodes are destroyed when build/experiments are ended and unneeded after ~15 minutes.

HTH

**Comment by mouradmourafiq** [comment]
@vfdev-5 This is a nice resource, maybe we should add it as a guide in the docs or a blog post for future references.
