### ISSUE TITLE
Use polyaxon as a tracking server with experiments on local workstation

### ISSUE THREAD

**Issue by JacobJeppesen** [polyaxon/polyaxon#1326]
### Current behavior
I have workstation with a GPU that I occasionally would like to use to run experiments, which automatically uploads results to polyaxon. It seems like the --local flag would previously do something similar, but is not supported anymore.

### Enhancement
It would be great if I could just run `polyaxon run -p project1 -f experiment.yaml --local`, and the experiment would run on the workstation while using polyaxon as a tracking server. It could either be with automatic or manual sync after the experiment has finished. As far as I can tell, the offline mode (https://blog.polyaxon.com/polyaxon-v1-6/) can be used, but requires changing the project code, rather than simply setting a flag in the CLI.

(this issue was made following this Slack conversation: https://app.slack.com/client/T6QR3FYN7/C6QBND2SV/thread/C6QBND2SV-1622014123.048100)

**Comment by ddebby** [comment]
also request this feature
