### ISSUE TITLE
Create a simple react app to create/update polyaxon k8s deployment configuration

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#135]
### Feature motivation

The app should allow user to create/download/load a json/yaml config file to create/upgrade a Polyaxon deployment.

### Feature description

 * The react app can expose in an easy way the different options provided by polyaxon helm chart.
 * Users should ideally follow a wizard to create a deployment.
 * The wizard must provide steps to configure: storage, database, resources, replication, and other options.
 * The app should allow to download a yaml/json file, that will be used later by helm to create the deployement.

**Comment by maver1ck** [comment]
Maybe this can help ?
https://github.com/helm/monocular
