### ISSUE TITLE
Private docker repo's

### ISSUE THREAD

**Issue by innovia** [polyaxon/polyaxon#139]
### Unclear documentation
Hi
it's unclear how or if its possible to use private docker repo such as ECR for example.

Where is the code section I'm willing to contribute

**Comment by mouradmourafiq** [comment]
@innovia, unfortunately, it is not possible to use a private docker registry at the moment.

Can you clarify a bit your use case, do you need only to pull images from a private docker registry or do you want to use the private docker registry as the main registry for not only pulling images but also for storing them during the build?

**Comment by innovia** [comment]
I only need to pull images from my ecr on Amazon no need to store them

**Comment by innovia** [comment]
From the code it's seems to be already supported ?

https://github.com/polyaxon/polyaxon/blob/0d0daed21a938d3bc5e08155d1ed1b5a24ba983d/polyaxon/dockerizer/builder.py#L74-L80

**Comment by mouradmourafiq** [comment]
@innovia it's not, that part of the code is used if the user sets authentication for the registry. By providing this values you will force the platform to use the external registry as the main registry for building the internal images:
```python
POLYAXON_REGISTRY_USER
POLYAXON_REGISTRY_PASSWORD
POLYAXON_REGISTRY_HOST
POLYAXON_REGISTRY_PORT
POLYAXON_REGISTRY_NODE_PORT
```
But to use one registry for only pulling images and the in-cluster one for building images, it's not possible.

You can try to set those values in your config yaml, but be aware that it will also push images.

**Comment by innovia** [comment]
for ecr this is not the case since they dont provide a user name and password

they force you to login every 12 hours and get a new token

**Comment by gzcf** [comment]
@mouradmourafiq Our team also needs this feature.So I implemented it in my fork. Just exposing external registries config in Chart's `values.yml` and adding extra login code in `DockerBuilder.login` method.

**Comment by mouradmourafiq** [comment]
@gzcf thank you for letting me know, good to know that it works for you. Is it possible to put some documentation or merge back the changes so that @innovia and other people can use it?

**Comment by gzcf** [comment]
@mouradmourafiq Of course. I will do it.

**Comment by innovia** [comment]
Duplicate #150
