### ISSUE TITLE
Mount nfs and get stuck on experiment

### ISSUE THREAD

**Issue by ziyitony** [polyaxon/polyaxon#143]
### Describe the bug
I used to deploy successfully with polyaxon-example repo. But this time I mounted nfs from another vm and failed to run difar10 in polyaxon-example, stuck in starting

![pod info](https://user-images.githubusercontent.com/18106851/42956272-236d004c-8bb2-11e8-8a09-63504d7a28ab.PNG)

### To Reproduce

just follow the guide [here](https://docs.polyaxon.com/tutorials/azure_deployment/training_experiments_on_polyaxon/)

### Expected behavior
run example successfully.

### Environment
![stucked](https://user-images.githubusercontent.com/18106851/42956078-9c00f154-8bb1-11e8-9228-5a70a32d5025.PNG)

![cluster](https://user-images.githubusercontent.com/18106851/42956265-1f62c28e-8bb2-11e8-8615-8f249d6e02f5.PNG)

**Comment by ziyitony** [comment]
![pv pvc nfs](https://user-images.githubusercontent.com/18106851/42956563-de5aac10-8bb2-11e8-94de-29a3f3dbf7a8.PNG)

`rbac:
  enabled: true

ingress:
  enabled: true

serviceType: ClusterIP

persistence:
  logs:
    existingClaim: polyaxon-pvc-logs
  repos:
    existingClaim: polyaxon-pvc-repos
  data:
    data1:
      existingClaim: polyaxon-pvc-data
      mountPath: /data
    data2:
      existingClaim: polyaxon-pvc-data
      mountPath: /code
  outputs:
    outputs1:
      existingClaim: polyaxon-pvc-outputs
      mountPath: /outputs`

**Comment by ziyitony** [comment]
Pardon for my disturbing please.
Is that because my user account is not root?

**Comment by mouradmourafiq** [comment]
This at least looks suspicious:

```
data:
  data1:
    existingClaim: polyaxon-pvc-data
    mountPath: /data
  data2:
     existingClaim: polyaxon-pvc-data
     mountPath: /code
```
You used the same claim `polyaxon-pvc-data` with 2 different paths.

**Comment by ziyitony** [comment]
Thanks, I will correct this place and try again.

**Comment by ziyitony** [comment]
@mouradmourafiq Anything goes fine now!
Thank you man. It's impossible for me to do this right without your kind and patient help.
Very good repo, good man.
I appreciate your contribution and kindness
