### ISSUE TITLE
Make it possible to apply the Polyaxon Operator CRD manifest through Config Sync

### ISSUE THREAD

**Issue by shotarok** [polyaxon/polyaxon#1447]
### Current behavior

We started using GCP ConfigSync for GitOps. The ConfigSync can't apply the Polyaxon Operator CRD manifest because of https://g.co/cloud/acm-errors#knv1045. The error is following:

```console
[1] KNV1045: Configs with "status" specified are not allowed. To fix, either remove the config or remove the "status" field in the config:

source: /Users/shotarok/ghq/github.com/kouzoh/mercari-us-ml-de-kubernetes/deploy-config/ml/gke_mercari-us-ml-dev_us-central1-b_us-polyaxon/cluster/CustomResourceDefinition/operations.core.polyaxon.com.yaml
metadata.name: operations.core.polyaxon.com
group: apiextensions.k8s.io
version: v1
kind: CustomResourceDefinition
```

### Enhancement

* Delete the status from the CRD manifests in the helm charts like below
  * https://github.com/polyaxon/charts/blob/master/agent/templates/crds/core.polyaxon.com_operations.yaml
  * https://github.com/polyaxon/charts/blob/master/agent/templates/crds/core.polyaxon.com_operations.yaml

```diff
@@ -13819,9 +13819,3 @@ spec:
     storage: true
     subresources:
       status: {}
-status:
-  acceptedNames:
-    kind: ''
-    plural: ''
-  conditions: []
-  storedVersions: []

```

**Comment by mouradmourafiq** [comment]
We will have to see if this change has any impact on the bahvior of the CRD.
An option is to add an option to the helm chart values:

```yaml
operator:
  skipStatus: true  # false by default
```

**Comment by shotarok** [comment]
Thanks! I don't think the change affects the CRD behaviors because I saw other CRDs that don't have the status fields. It'd be better to double-check the official documents. I don't mind either the option `skipStatus` or deleting the lines from the manifests. Thanks for the quick response!
