### ISSUE TITLE
POLYAXON_AGENT_SPAWNER_REFRESH_INTERVAL won't be defined when values.yaml has `agentSecret`.

### ISSUE THREAD

**Issue by shotarok** [polyaxon/polyaxon#1448]
### Describe the bug

* POLYAXON_AGENT_SPAWNER_REFRESH_INTERVAL won't be defined when values.yaml has `agentSecret`. Is this intentional?
* If this is unintentional, we may want to put `{{- end}}` on L35 instead of L41 in https://github.com/polyaxon/charts/blob/dac46b0881c3bfec021903d264d44d766435e264/agent/templates/agent-cm.yaml#L29-L41. 

### To reproduce

* Prepare values.yaml that has `.agentSecret` and `.agent.spawnerRefreshInterval`
* Render the polyaxon agent chart manifests with the values.yaml
* Confirm the ConfigMap doesn't have `POLYAXON_AGENT_SPAWNER_REFRESH_INTERVAL`.

### Expected behavior

* The ConfigMap will have `POLYAXON_AGENT_SPAWNER_REFRESH_INTERVAL`.

### Environment

* I used the v1.10.1 of the polyaxon agent chart, but the latest main branch also has the same if-else conditions as I put the link above.

**Comment by mouradmourafiq** [comment]
I think this is a regression, those two options were added under the wrong `if - end` block:

```yaml
  {{- if .Values.agent.isReplica }}
  POLYAXON_AGENT_IS_REPLICA: {{ .Values.agent.isReplica | quote }}
  {{- end }}
  {{- if .Values.agent.spawnerRefreshInterval }}
  POLYAXON_AGENT_SPAWNER_REFRESH_INTERVAL: {{ .Values.agent.spawnerRefreshInterval | quote }}
  {{- end }}
```
