### ISSUE TITLE
Support transferring/moving and copying artifacts from one project to another using the CLI

### ISSUE THREAD

**Issue by ehsanmok** [polyaxon/polyaxon#1452]
### Use case

The main use-case is if there are multiple model-registry for example and in the approval process one wants to transfer a registered model from one model-registry / project to another

### Feature description

Including a subcommand like `plx models transfer --version VERSION -p PROJECT1 --to-project PROJECT2`

### Alternatives

AFAIK there's no alternative but an almost workaround is like `plx ops artifacts -p PROJECT1` to download and `plx ops upload -p PROJECT2` to the second project but the latter needs the run uuid of the PROJECT1 which doesn't exist in PROJECT2

**Comment by polyaxon-team** [comment]
* [plx models copy](https://polyaxon.com/docs/core/cli/models/#models-copy)
 * [plx models copy](https://polyaxon.com/docs/core/cli/models/#models-transfer)
 
Same commands for `plx components` and `plx artifacts`.
