### ISSUE TITLE
Polyaxon cli build logs --follow does not show live logs  but session ended

### ISSUE THREAD

**Issue by innovia** [polyaxon/polyaxon#146]
### Describe the bug
When running the command `polyaxon build -b 3 logs --follow` the returned response is `Session Ended`

when running the same command with the flag --past it shows the logs but the if you repeat the command a few time you can see a progress in the logs (as if they were live)
for example:

`polyaxon build -b 3 logs --past`
...
Push: Pushing [=================================================> ] 845.1 MB/852.5 MB
Push: Pushing [=================================================> ]   849 MB/852.5 MB
```

again
`polyaxon build -b 3 logs --past`
```
Push: Pushing [=================================================> ] 845.1 MB/852.5 MB
Push: Pushing [=================================================> ]   849 MB/852.5 MB
Push: Pushing [=================================================> ] 851.3 MB/852.5 MB
Push: Pushing [==================================================>] 852.6 MB
Push: Pushed None
Push: 360519c23ed64975b3fa711ca570e228: digest: sha256:9e81fcae3c43e9ad167b4d8588ff67789a1629c2d1e6cce2c7fae9667a52bada size: 5137 None
Push finished: {'Tag': '360519c23ed64975b3fa711ca570e228', 'Digest': 'sha256:9e81fcae3c43e9ad167b4d8588ff67789a1629c2d1e6cce2c7fae9667a52bada', 'Size': 5137}
```
### To Reproduce
<!-- Include a code example or the steps that led to the problem. Please try to be as specific as possible. -->

### Expected behavior

### Environment
polyaxon 0.1.5

**Comment by mouradmourafiq** [comment]
I think we can close this issue, it was due to wrong ports configuration. Feel free to reopen if it was not the case :)
