### ISSUE TITLE
Unable to edit or delete saved queries

### ISSUE THREAD

**Issue by alexandresee** [polyaxon/polyaxon#1501]
### Describe the bug
When working in either the `Jobs` or the `Services` UI, I am unable to `edit` or `delete` saved search queries.

### To reproduce

1. Save a search query:
![image](https://user-images.githubusercontent.com/21223025/165094846-07f0b892-9072-4850-8fe8-27a11a6470d7.png)

---

##### (A) Unable to `edit`

2. Scroll to the search query from the dropdown list and select the newly created search query:
![image](https://user-images.githubusercontent.com/21223025/165096499-e9833b1b-2ba1-482c-9d4a-76c864050423.png)

2. Scroll to the search query from the dropdown list and press the `edit` button:
![image](https://user-images.githubusercontent.com/21223025/165097357-c368a598-1358-491c-bc99-31cc6b3cb0a8.png)

3. Changing only the `Name` of the search and pressing the `Update` **without** selecting `New instance` produces an error:
![image](https://user-images.githubusercontent.com/21223025/165097707-172806f2-2a88-440a-a350-6445051a27d2.png)

4. Changing the `Description` of the search and pressing the `Update` **without** selecting `New instance` produces an error:
![image](https://user-images.githubusercontent.com/21223025/165097843-0e52d20f-7724-47ae-a175-6ac79f5e994c.png)

---

##### (B) Unable to `delete`

2. Scroll to the search query from the dropdown list and press the `delete` button:
![image](https://user-images.githubusercontent.com/21223025/165092879-3ff95908-716f-4ea2-b7bf-47994229a22f.png)

3. Press the `I understand the consequences, remove this search.` button in the popup window:
![image](https://user-images.githubusercontent.com/21223025/165093468-d92bd891-0939-4120-8767-1ac5dcee31ec.png)

5. Observe that the search query is still in the dropdown list after (i) refreshing the UI using the "refresh button", (ii) reloading the page, and (iii) logging out and logging back in. In accordance, trying to create a new search query with the same `Name` fails:
![image](https://user-images.githubusercontent.com/21223025/165095121-7fc6f1b5-70bb-4629-b8e3-5f0e4ddebc10.png)

---

##### (A) Editing

Changing the `Name` or the `Description` of a search **without** selecting `New instance` should update the existing search without producing an error (unless the new name already exists, etc.).

##### (B) Deleting

Search deletion should be persisted, and a user should be able to create a new search with the same `Name`. 

### Environment

- Polyaxon: `v1.17.1`
- Google Chrome: `Version 100.0.4896.127 (Official Build) (x86_64)`
- macOS: `Big Sur 11.6`

**Comment by polyaxon-team** [comment]
Regarding the deletion, only users with the `admin` role or higher can delete searches, dashboards, and other entities. Permission docs: https://polyaxon.com/docs/management/organizations/members/#organization-permissions . Asking your org admin about your role can clarify if you can perform that action.

For the update, that should be possible for normal members. We will check if there's a special role check when the user is promoted to a specific role within a team.

**Comment by alexandresee** [comment]
Ok, thank you for the clarification. 

1. Is there a way for the org admin to delegate constrained permissions for specific actions? For example, could my org admin delegate to me the permission to delete (non-promoted) searches on a specific project? 

2. Is there a way to hide searches? My saved queries dropdown list is now completely cluttered from having to create new searches with new names each time I want to make a change.

**Comment by polyaxon-team** [comment]
1. It's possible to give the admin role for a user on a specific team

  2. Updating search should be possible for members, I think there's a regression that we will fix ASAP. In the meantime you can ask an admin to delete the searches. The can see all searches under that specific project:
    
![Screenshot 2022-04-25 at 16 20 07](https://user-images.githubusercontent.com/24545041/165108445-daec02a0-3e2a-4873-8ab3-26fb75dda6b0.png)

**Comment by polyaxon-team** [comment]
Updating searches and dashboards is fixed and will be deployed tomorrow. Members will be able to patch or update those entities without the need for the admin role.
Thank you for reporting the issue @alexandresee.
