### ISSUE TITLE
Statuses in the dashboard displayed abnormally

### ISSUE THREAD

**Issue by hongqing1986** [polyaxon/polyaxon#1507]
### Describe the bug
when a job is finished, the statuses in the dashboard displayed abnormally, as following:
![image](https://user-images.githubusercontent.com/21071786/173584953-fb62191b-841e-4ae6-9841-6acf5912367b.png)

And the warning step's details:
containers with unready status: [polyaxon-main polyaxon-sidecar]
![image](https://user-images.githubusercontent.com/21071786/173585587-4dceb79f-c8e0-4f8a-953b-3ca89dfd19da.png)

**Comment by hongqing1986** [comment]
any feedback?

**Comment by polyaxon-team** [comment]
The statuses tab keeps all transitions that an operation goes through (including times and details), the last status of the operation is the last item of the list and also the one mentioned on the details page.
