### ISSUE TITLE
How can i install the polyaxon from the source code ?

### ISSUE THREAD

**Issue by hongqing1986** [polyaxon/polyaxon#1508]
### Describe the problem
From the document, i didn't find the details about how i can install the polyaxon from the source code, 
Sometimes, If i encountered a problem, i can add some debug information, and redeploy it, maybe i can solved it by myself.
Could you show me the build steps?

**Comment by hongqing1986** [comment]
Any feedback?

**Comment by hongqing1986** [comment]
I didn't find these images's Dockerfile:
polyaxon/polyaxon-gateway
polyaxon/polyaxon-api
polyaxon/polyaxon-streams
polyaxon/polyaxon-operator

Anyone can help me ?

**Comment by polyaxon-team** [comment]
In v1.19, users will be able to start the platform only by installing the Python library, [see](https://polyaxon.com/docs/releases/roadmap/#sandbox).
We might also push a docker-compose or single docker container version for starting the platform without k8s. 
Those options will also serve as a tutorial on how to build/start Polyaxon from source or how to customize the behavior.

**Comment by hongqing1986** [comment]
For example, If i want to build polyaxon-streams image, how can i build from source?
