### ISSUE TITLE
403: Forbidden Error due to Plotly CDN being down - Need to point to alternative JS sources

### ISSUE THREAD

**Issue by Syakyr** [polyaxon/polyaxon#1530]
### Describe the bug
Polyaxon Dashboard has been unusable due to Plotly CDN being down and unavailable (see https://github.com/plotly/plotly.js/issues/6648). As such, since the Polyaxon Dashboard seems to be dependent on the CDN from Plotly (as of 1.20.0), it cannot be accessed.

Console inspect:
<img width="555" alt="Screenshot 2023-06-21 at 11 54 14 AM" src="https://github.com/polyaxon/polyaxon/assets/23415399/09052eb5-0937-456a-802d-2851b51cb710">

I am not aware that this may be fixed in 1.21.0 and 1.22.0, but if it has been, then I'm opening the issue to bring awareness and hopefully find a workaround to deploy with alternative JS sources (as outlined in the referenced Plotly.js issue).

### To reproduce

Just spin up a Polyaxon instance and log into the Dashboard (as of 21 June 2023, 0600z).

### Expected behavior

To be able to access the Dashboard.

### Environment
- Polyaxon=v.1.20.0

Extra environment information is available upon request, although I do not see it to be applicable considering this is an issue due to external factors, but a redundancy within the code would be appreciated.

**Comment by bastianerh** [comment]
You can redeploy/upgrade your installation to use local packages instead of cdns with:

```yaml
...
ui:
  offline: true
...
```

**Comment by arek-widelab** [comment]
What about resources like https://cdn.plot.ly/usa_110m.json?
Is it possible to replace that path as well using plotly api?

**Comment by ajuric** [comment]
> You can redeploy/upgrade your installation to use local packages instead of cdns with:
> 
> ```yaml
> ...
> ui:
>   offline: true
> ...
> ```

@bastianerh Does this means Polyaxon web will not be deployed/available?

**Comment by bastianerh** [comment]
@ajuric The UI will be available, the only difference is that it will serve all js packages and vendors from Polyaxon server instead of the CDNs.

**Comment by ajuric** [comment]
@bastianerh Cool, thank you a lot! :)

Is there any reason then why not always setting the "offline: true", to avoid problems like these? Asking because I handle our PLX deployment and would like to minimize my involvement there, but also wouldn't like to miss all the "good features" or don't "good practices" for deployment?

**Comment by ajuric** [comment]
I see, thanks! :+1:

**Comment by Syakyr** [comment]
Since the CDNs are back up, I'll close the issue. Hopefully if the CDNs are down again, this issue can be used as a reference.
