### ISSUE TITLE
Delete experiments from the website

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#167]
### Feature motivation

Cannot delete an experiment from the website

### Feature description

The website needs to be more user friendly and allow to delete experiments once they are useless

### Feature implementation

In the list of experiment add a button next to each experiment in order to delete it. Also add a button inside an experiment to delete it.

**Comment by mouradmourafiq** [comment]
@jorgemf This is definitely something that is needed and I will add, not only deleting experiments but also stopping experiments and other user interactions, deleting and creating projects ... directly from the dashboard. But I cannot give a timeline for these features just yet.

**Comment by mouradmourafiq** [comment]
Delete/stop experiments/jobs/groups will be part of next release.
