### ISSUE TITLE
Add Auto-Refreshing/Updating of the web-ui

### ISSUE THREAD

**Issue by wematan** [polyaxon/polyaxon#173]
### Feature motivation

When working with polyaxon in a team environment there may be a lot of updates and new items/projects being created or changed. 
the current state is that the web doesn't refresh by itself.

### Feature description
I would like the interface to keep updating for changes.

**Comment by mouradmourafiq** [comment]
The next version (0.3.0) will include a new button to refresh the component's (tables, charts, overview, ...) data
<img width="1246" alt="screen shot 2018-11-05 at 13 38 58" src="https://user-images.githubusercontent.com/1261626/47998587-2f066d00-e100-11e8-9c9b-55b812fa9f42.png">

**Comment by Lap1n** [comment]
This is not fixed for me in Polyaxon version 0.5.6.
