### ISSUE TITLE
Polyaxon Jupyter Hub spawner for gpu jobs on kubernetes

### ISSUE THREAD

**Issue by georghildebrand** [polyaxon/polyaxon#179]
### Feature motivation

Many companies and university groups started using jupyter hub for managing jupyter on larger scale. Having an spawner integration for polyaxon jobs would be a super feature. However, i confess i don't know polyaxon very much but i am looking for a nice job manager integration jupyter. 

### Feature description

- a spawner implementation for jupyter hub to spin up polyaxon workloads on the same kubernetes cluster --> use a gpu deployments (eg. by selecting p2 instance node pools) --> run polyaxon pods in this node pool

### Feature implementation

tbd,

**Comment by mouradmourafiq** [comment]
This will be possible starting from polyaxon v0.3.0.

**Comment by posix4e** [comment]
Is this good to close?
