### ISSUE TITLE
List of TensorBoards instances up

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#188]
### Feature motivation

Currently there is no way to know how many TensorBoard instances are up for a given project.

### Feature description

Add a new API call to know the TenorBoard instances up for a given project. Add also a view in the UI to list this instances.

**Comment by mouradmourafiq** [comment]
There's a command : `polyaxon project tensorboards`

**Comment by jorgemf** [comment]
@mouradmourafiq  I missed that. Thanks.
Is there anyway to delete the tensorboard instances we don't need anymore?

**Comment by mouradmourafiq** [comment]
yes: for experiment tensorboard `polyaxon tensorboard -xp id stop`, for group tensorboard`polyaxon tensorboard -g id stop`, for project tensorboard `polyaxon tensorboard stop`

**Comment by jorgemf** [comment]
Those commands still keep the Tensorboards builds in `polyaxon project tensorboards` I was expecting to not see them there.

**Comment by mouradmourafiq** [comment]
the command is not showing the running tensorboards, but all tensborads jobs under the project with their statuses. If you wish to mute stopped tensorboards, you can use the query: `polyaxon  project tensorboards -q 'status: ~stopped'`, or you can only view running tensorboards `polyaxon  project tensorboards -q 'status: running'`

**Comment by ajuric** [comment]
Currently in the UI, if I saw well, if there is Tensorboard(TB) running, you will only see a link to TB in the Overview tab of experiment (or project, or experiment group ...). That would mean that in the UI user would need to click through all overview tabs to check if there are any TB left ...

**Comment by mouradmourafiq** [comment]
The result of this command `polyaxon project tensorboards`, that returns tensorboard for a project, will be as well in the dashboard, on the project's tabs. But I still did not find time to do that.

**Comment by mouradmourafiq** [comment]
Closing this issue because v0.4.3 has tensorboards and notebooks tables per project, where users can see the list without the need to use the CLI.
