### ISSUE TITLE
Error while uploading projects with big files

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#194]
### Describe the bug

I have a project with jupyter notebooks, which are around 1.5Mb. Polyaxon fails when uploading this files with an error: `413 Request Entity Too Large`

### To Reproduce

Create a project with a big file as a jupyter notebook. Try to upload the code.

### Expected behavior

The jupyter notebook should be uploaded as code. It might be more interesting throw a warning and asking you if you are sure of uploading a big file instead of failing. I like the fact it tells me that I am uploading something big and it might be wrond doing it, but at the same time it limits what you can do with notebooks.

**Comment by mouradmourafiq** [comment]
Feel free to reopen if you still have the same issue after upgrading to 0.2.7
