### ISSUE TITLE
Error uploading a file with the notebook interface

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#195]
### Describe the bug

When trying to upload a file in a notebook nothing happens.

### To Reproduce

Start a notebook and try to upload a new file. Nothing happens.

### Expected behavior

The file should be uploaded into the notebook.

**Comment by mouradmourafiq** [comment]
The error message is misleading, you cannot upload files while a notebook is running, you need to stop the notebook before uploading.

I am not sure why the server is not sending the correct error message anymore. 

I updated the error message to indicate that either the user does not have write access or a notebook is currently running.

**Comment by jorgemf** [comment]
I am not talking about the polyaxon-cli, but the notebook interface. I can navigate, create files but not uploading new files.

**Comment by mouradmourafiq** [comment]
I think you are seeing a similar issue #194 that you have with the cli for large files, I also think it is related to this #200.

It was a bit hard to debug, but it was related to some ingress annotations. I just tested the fix for both upload very large code files and uploading with notebook interface and they work. The fix will be released today.

**Comment by jorgemf** [comment]
I tried with small files too. So not sure. I will test it again with the new version and update you with the results. If it is working I will close the issue

**Comment by mouradmourafiq** [comment]
Doing some more tests before releasing, as the release has a data migration, I will update this issue once the new version is released.

**Comment by mouradmourafiq** [comment]
You are right, you are probably having a different issue, I was able to upload a file with the current version. So I think this issue is not related to the other upload issue.

**Comment by jorgemf** [comment]
Seems it is working now with the new version
