### ISSUE TITLE
Creating a user in the admin panel seems to leave the account only partially set up

### ISSUE THREAD

**Issue by honnibal** [polyaxon/polyaxon#197]
Not sure whether this is something that should be expected to work, but my first instinct for creating a user was to go to the admin panel and create one directly, rather than using the /users/register page.

When the user is created directly from the admin console, after activating the user it still can't log in. Perhaps some permissions aren't added correctly this way?

**Comment by mouradmourafiq** [comment]
It's missing an email if the user is created through the admin, that part needs to be redone or disabled from the admin side.

I expect that it works if the user is created through `/users/register`?

**Comment by mouradmourafiq** [comment]
You can use the admin to create a user as well, but you will need to `edit` and add an email, and it should work as well after that.
