### ISSUE TITLE
polyaxon_helper unable to report metrics 

### ISSUE THREAD

**Issue by wematan** [polyaxon/polyaxon#201]
I ran a group experiment of a total of 4 experiments and reported metrics using send_metrics method from polyaxon_helper as I used in the past but for most of my experiments i got this error:
master.1 -- curr_test_loss:['0.614394'] ,curr_train_loss: ['0.00797425'] ,curr_acc ['0.800569']
master.1 -- Could get api info, please make sure this is running inside a polyaxon job.
master.1 -- Environment information not found, please make sure this is running inside a polyaxon job.

metrics were reported correctly in one of the experiments tho.

**Comment by mouradmourafiq** [comment]
is it possible to use:

```
  build_steps:
    - pip install --no-cache-dir -U polyaxon-helper
  nocache: true
```

**Comment by mouradmourafiq** [comment]
Did you manage to get it to work?

**Comment by mouradmourafiq** [comment]
Please reopen if you still have the same issue
