### ISSUE TITLE
Experiments in groups sometimes fail

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#211]
### Describe the bug

When there is nothing running in polyaxon and I launch a group experiment some of the experiments fail in the build phase. If an experiment group is already running and I launch another experiment group (without modifying anything in the code) none of the experiments of this second experiment group fails.

### To Reproduce

1. Wait until nothing is executing in polyaxon
2. Launch an experiment group (I used one with a matrix of 3 variables with 2 values per variable)

### Environment

Polyaxon 0.2.8
One node in kubernetes with 2 GPUs and 32Gb of RAM where polyaxon and the experiment run together.

**Comment by mouradmourafiq** [comment]
I experienced this myself as well, I don't know why yet, but I have a theory, I just never had the chance to look at it.
