### ISSUE TITLE
The button to change the x-asis of the graphs (time/step) does nothing

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#212]
### Describe the bug

When showing a graph and I try to change the x-axis to step the graphs do not change.

**Comment by mouradmourafiq** [comment]
You need to report a step as part of your metrics, from the [docs](https://docs.polyaxon.com/polyaxon_tracking/experiments/#log-metrics)

If you are still using the helper, you can just update your code:
```python
send_metrics(step=i, loss=0.2, ...)
```

**Comment by jorgemf** [comment]
Thanks. I forgot it
