### ISSUE TITLE
Keep columns in list of experiments

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#213]
### Feature motivation

Everytime the list of experiments is loaded I need to add again the columns. 

### Feature description

It would be nice if the selected columns were stored in the url somehow, so when the page is reloaded the columns are there.

Another nice addition would be if the data is automatically updated but keeping the columns in the url seems like something with more posibilities as sharing/saving the link

**Comment by jorgemf** [comment]
@mouradmourafiq I am talking abou this view: 
![screenshot-20181018093406-3650x932](https://user-images.githubusercontent.com/1029554/47138250-27019d00-d2b9-11e8-89a9-721004d2c174.png)

**Comment by mouradmourafiq** [comment]
yes that's also what I was talking about, you can save this as a query, and you can load it every time. But it will require selecting that query each time you reload the page.

But in any case I think we need this feature #173 ASAP.

**Comment by jorgemf** [comment]
I didn't see the button. Maybe it could be improved but I close the issue as the functionality is there
