### ISSUE TITLE
Incorrect schemata regarding Persistence

### ISSUE THREAD

**Issue by naetherm** [polyaxon/polyaxon#214]
#### Inconsistency
Within the documentation of the Persistency [0] and [1] are some typos. 

[0] https://docs.polyaxon.com/reference_polyaxon_helm/#persistence
[1] https://github.com/polyaxon/polyaxon-chart

For example, for the `repos` section it should be
```persistence.repos.existingClaim```
and not
```persistence.logs.existingClaim```

The same for the `upload` section. 

#### Postgresql

I'm also a bit confused about the persistence of the postgresql database. I haven't found any further information about it within the documentation and the charts. For me it seems that I have to create the PV and the PVC myself and assign it via `postgresql.persistence.existingClaim` (so no automatic creationg via helm)?

**Comment by mouradmourafiq** [comment]
Thank you for reporting the potential typos, a PR would be more than welcome.

For postgres, did you have a look at https://docs.polyaxon.com/customization/postgresql_ha/#dynamic-persistence-provisioning

**Comment by naetherm** [comment]
Kk ... to early in the morning. Thanks, and I'll make a PR.
