### ISSUE TITLE
Resume experiments doesn't work in finished experiment groups

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#215]
### Describe the bug

When all the experiments of an experiment group have finished, none of the experiments can be resumed. The status of the "new experiments" stay as created.

### To Reproduce

1. Create a group of experiments and wait until all the experiments have finished
2. Try to resume any of the experiments

### Expected behavior

New experiments should be created and executed , currently they are only created.

**Comment by mouradmourafiq** [comment]
Can you provide what platform version are you running?

**Comment by jorgemf** [comment]
The latest: 0.2.8

**Comment by mouradmourafiq** [comment]
What experiment group type are you running can you put in the spec for the `hptuning` section?

**Comment by jorgemf** [comment]
I am using matrix. My problem is with the command `polyaxon experiment -xp XX resume -u -f xxxx'

**Comment by mouradmourafiq** [comment]
I know, but I need to know first why the group is not starting the experiment, and then I will check the `resume` command after.

**Comment by jorgemf** [comment]
It might be related to https://github.com/polyaxon/polyaxon/issues/211 but resume always fails in a group with all the experiments inside the group finished (I haven't tested with failed experiments, it might happen to). I also tested in 0.2.7 and it also happens there

**Comment by mouradmourafiq** [comment]
Yes you are right, it does not work, I know what's the issue, and I will try to fix it ASAP, thanks for reporting.

**Comment by mouradmourafiq** [comment]
Feel fee to reopen, it should be possible to do this operation starting from next release 0.3.0.
