### ISSUE TITLE
Allow sorting by specific columns in the experiments UI

### ISSUE THREAD

**Issue by elyase** [polyaxon/polyaxon#224]
### Feature motivation
It would be great to be able to sort by specific columns, for example to find out the best performing experiments.

![image](https://user-images.githubusercontent.com/1175888/47417863-354c2f00-d779-11e8-9c36-408b2a0f6f5e.png)

### Feature description
Add a small arrow in the UI.

**Comment by mouradmourafiq** [comment]
You can do that after adding a metric column, you can use the `sort by` dropdown, see the image:
<img width="1268" alt="screen shot 2018-10-24 at 11 18 15" src="https://user-images.githubusercontent.com/1261626/47420405-a04c3480-d77e-11e8-8ea7-e32b3202143d.png">

**Comment by elyase** [comment]
Oh I see it now thanks. Apparently there is some issue in Safari:

![image](https://user-images.githubusercontent.com/1175888/47420813-9c6ce200-d77f-11e8-856d-85d39dda8491.png)

I still think it would be a little more intuitive to have small arrows on top of the column like this:

![](https://cdn-images-1.medium.com/max/800/1*ViE5_uxbbU6LEfnV8GrQtA.jpeg)

**Comment by mouradmourafiq** [comment]
Actually, there are quite some issues on Safari.

**Comment by mouradmourafiq** [comment]
The dropdown issue (and some other style issues in safari) is fixed, and will be part of next release. Thanks for reporting.

**Comment by mouradmourafiq** [comment]
2 UI issues were fixed in 0.2.9 (the sort by dropdown and an issue with columns (metrics/params))
