### ISSUE TITLE
[Chart] Selecting `line` creates a `bar` chart

### ISSUE THREAD

**Issue by wbuchwalter** [polyaxon/polyaxon#227]
### Describe the bug

In an experiment group in the metrics tab, when creating a new view selecting `line` still creates a `bar` charts.

### Environment

Polyaxon 0.2.8

**Comment by mouradmourafiq** [comment]
This is an intended behaviour when only one metric value exists per experiment unless it's a different behaviour you are describing.

**Comment by wbuchwalter** [comment]
Good to know I was expecting line to be a 'scatter' if only one metric value exists.
I will reopen if this also appear with multiple values, as I can't confirm right now.
