### ISSUE TITLE
[Chart] Add a `add all` button to the chart creation view

### ISSUE THREAD

**Issue by wbuchwalter** [polyaxon/polyaxon#228]
### Feature motivation
If I want to create a new chart in an experiment group, I have to individually select all experiments that I want to see. Very often I want to see all the experiments, and if I have more than a handful of experiments this becomes a bit painful.

### Feature description

Add a `Add all` button to add all experiments to the chart in one click.

**Comment by mouradmourafiq** [comment]
It was actually the default behaviour, but when having a large group the charts become very cluttered. Maybe allow selecting all if the group has small number of experiments?

**Comment by wbuchwalter** [comment]
I suspect different users will have different opinions on what is cluttered or not.
As long as `Add all` is an opt-in button (and not selected by default), I think it's okay to let the user decide for themselves?
Worst case if you select add all and it's too cluttered you can easily remove the chart and select individually instead.
What do you think?

**Comment by nishansubedi** [comment]
+1 to an `Add all` option. We're adopting Polyaxon at and find that running experiment groups is a pretty common use case for us. Another additional feature I'd love to have is the ability to clone an existing chart, and edit it. Happy to create a new issue for this if you feel that that is worthwhile. 
Thankyou

**Comment by mouradmourafiq** [comment]
@nishansubedi This is planned for the v0.5. It's actually possible, but very unusable at moment, if you don't choose any experiment and create a chart, it will use all experiments in the group/selection.

Regarding the feature request, please create a separate issue for that.

**Comment by mouradmourafiq** [comment]
This is in v1.
