### ISSUE TITLE
Add a warning when code is big

### ISSUE THREAD

**Issue by wbuchwalter** [polyaxon/polyaxon#229]
### Feature motivation

Many users have their code and data in the same root directory.
When doing `polyaxon run -u`, if the `.polyaxonignore` file is not properly filled, the command will hang for a long time while it uploads all the data.
This is not always intuitive for users why the command is taking so long.

### Feature description
If the files about to be uploaded are more than a certain threshold (say 50MB), the CLI should output a warning such as `Warning: Polyaxon is about to upload X MB of code. Did you forget to add your data to .polyaxonignore?`

**Comment by mouradmourafiq** [comment]
There's a hard limit but it was large 100MB, next release it will be configurable.

Users can set 2 values: POLYAXON_WARN_UPLOAD_SIZE and POLYAXON_MAX_UPLOAD_SIZE. The first will show a warning, the second will raise and abort the upload.

Closing the issue.
