### ISSUE TITLE
Visualization problem with "Metrics".

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#233]
### Describe the bug

I have also a visualization problem with "Metrics". I log metrics I can see them as points while hover on them, but no line drawn.

<img width="1421" alt="screen shot 2018-10-28 at 10 08 59" src="https://user-images.githubusercontent.com/2459423/47617437-5be6ce80-dac7-11e8-968e-a3a4f1cdddf7.png">

### Environment
0.2.9

**Comment by mouradmourafiq** [comment]
This will be part of the next release.
