### ISSUE TITLE
Configure timeout of setting experiment as zombie

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#234]
### Feature motivation

I would like to have a possibility configure the timeout that checks heartbeat of an experiment before setting the status in zombie state (no heartbeat was reported).".

### Feature description

My problem with "zombie state" appears on the first launch of the experiment when GPU node is not yet running. I'm starting an experiment (on GKE cluster) and the time that experiment's job pod is scheduled on GPU node (which does not exist, but then becomes available by autoscaler), polyaxon backend considers the job in zombie state and experiment is failed. However if I just relaunch the same experiment the second time, everything goes well as GPU node is already available.

Thanks!

**Comment by mouradmourafiq** [comment]
There will be an option to set `POLYAXON_HEARTBEAT_TIMEOUT` in seconds in the next release.
