### ISSUE TITLE
Possible wrong Status-Badge for Experiment Groups

### ISSUE THREAD

**Issue by naetherm** [polyaxon/polyaxon#235]
### Describe the bug
We'd an experiment group, where all builds failed due to some wrong configuration of the requirements.txt file, so all builds failed and thereby all experiments. But in the overview of the 'Experiment groups' the group is marked as '_succeeded_'. 

### To Reproduce
Make a polyaxonfile.yml leading to build errors.

### Expected behavior
The status of the 'Experiment group' should be '_failed_'.

**Comment by mouradmourafiq** [comment]
Yes this is related to this #191

**Comment by naetherm** [comment]
Ah yeah ... only searched for 'status'. Will close this again.
