### ISSUE TITLE
Delete an experiment gives an error after hours authenticated

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#236]
When I authenticate the day before and try to delete an experiment the next day, the system does not take any action. When I check the requests, I realize that the request fails with error 403 ({"detail":"CSRF Failed: CSRF cookie not set."}).

### Expected behavior
Delete an experiment or redirect to login page.

**Comment by mouradmourafiq** [comment]
Did you manage to delete it after a re-login?

**Comment by denisoliveirac** [comment]
Yes.

**Comment by mouradmourafiq** [comment]
So I guess it's just because there's a 12 hours validity for the cookies, and after that a relogin is required.

**Comment by mouradmourafiq** [comment]
This is actually fixed, the new dashboard relies only on the token.
