### ISSUE TITLE
When an experiment fails fast, no log is persisted

### ISSUE THREAD

**Issue by denisoliveirac** [polyaxon/polyaxon#237]
When an experiment fails fast, no log is persisted.

### Expected behavior
Persist log normally.
### Environment
Auto-scale environment running on (google) cloud.

[fail_fast.zip](https://github.com/polyaxon/polyaxon/files/2527017/fail_fast.zip)

**Comment by mouradmourafiq** [comment]
That's something I noticed before as well, if you have an issue and you want to debug it, you can use the `--ttl=NUMBER_IN_SECONDS`, e.g. `--ttl=60` to keep the resource for one minute while you check what's wrong with the failing job.

**Comment by mouradmourafiq** [comment]
Closing this issue, it was already solved, because logs collection behaviour has changed.
