### ISSUE TITLE
Multiple cmd sections in polyaxonfile specification f

### ISSUE THREAD

**Issue by ajuric** [polyaxon/polyaxon#242]
Currently, the polyaxonfile specification allows only one `cmd` command in run section.

1) I have tried `cmd: command1 {{ args }} && command2 {{ args }}`, but the second command wasn't executed (or I did something wrong?)
2) I have tried multiple `cmd` sections, but only the last one gets executed.

I have seen your advice for creating a script which starts multiple commands (https://docs.polyaxon.com/customization/customize_run_environment/#running-a-script), but with this approach I need to parse the command line arguments in the script again which is a duplicated job ... Easier it would be just to have multiple cmd sections which are executed one after another?

The reason I would like to run multiple commands is to evaluate the model after training.
Or you maybe have other suggestion how to evaluate the model in the Polyaxon? (Of course, I could trigger the code for evaluation at the end of the training script, but I'm curious if there are any other options ...)

**Comment by mouradmourafiq** [comment]
Next release users can use `cmd: command1 {{ args }} && command2 {{ args }}`
