### ISSUE TITLE
GPU Node taints on GKE produce unwanted behavior without specific additional configuration

### ISSUE THREAD

**Issue by timorohner** [polyaxon/polyaxon#243]
### Missing Documentation

When using GPU instances on google cloud, as mentioned by @vfdev-5 in another issue (https://github.com/polyaxon/polyaxon/issues/131) the following taint is added to all nodes that have access to GPUs: `nvidia.com/gpu=present`. 

To still be able to run experiments on machines with this taint there are at least 2 solutions, the first one being the one mentioned by @vfdev-5 and the second one being the following: 

- Add gpu=v100 label to the gpu nodes (or whatever other label you wish)
- Add the following to your experiment yaml file: 
```
environment:
  node_selector:
    gpu: v100
  resources:
    gpu:
      requests: 1
      limits: 1
```

This results in a situation where experiments are successfully run on nodes with gpus, even though those nodes have the aforementioned taints. But unfortunately monitoring the resources used up by the experiment is not possible, because the taints of the gpu nodes will result in the necessary pods not being deployed to monitor the resources used during the experiment. 

This should be documented. I don't think it's necessary to change/adjust any default values, but the documentation should clearly mention that cloud providers such as google cloud apply particular taints to nodes that have access to GPUs and that users have to adjust their configuration based on that.

**Comment by mouradmourafiq** [comment]
You may need to set a toleration for [resourcesDaemon](https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/values.yaml#L185) in you deployment config.yml file.

**Comment by timorohner** [comment]
Exactly. As I mentioned, it's hardly a bug. But it for sure should be documented, since having experiments run without resource monitoring is for sure unexpected/unwanted behavior.

**Comment by siddygups** [comment]
@timorohner @mouradmourafiq Hey guys.  First off - thanks for an amazing tool.  Could you please provide a bit more information regarding the appropriate resourcesDaemon toleration that should be added?

I cannot seem to get resources (regular or GPU) to work. To be clear I installed polyaxon-gpustats and polyaxon-helper in my dockerfile. I havent noticed anything peculiar in logs for psql or any other core service.

I tried this to no avail: 
```  
resourcesDaemon:
    - key: nvidia.com/gpu
      operator: Equal
      value: present
```
