### ISSUE TITLE
Experiment queue preview

### ISSUE THREAD

**Issue by ajuric** [polyaxon/polyaxon#253]
What's a proper way to check the position of the experiment in the experiment queue?

Currently, when I create 10 experiments, but I have only 5 GPUs, 5 experiments will start immediately and 5 experiments would wait for GPUs to become free. That is expected.
But what if other users also start a lot of experiments? Then users don't know the order of the experiments in the queue and don't know the position of their experiment.

Currently, I see the total number of experiments if I check `kubectl get pods ...` and there I can see currently running experiments, but also don't know the next experiments. And cannot all users have access to kubectl.

I think that it would be useful to have on the dashboard a list of current state of the queue (you would see the order of scheduled experiments, who started it and so on ...), or at least to be able to get it in the terminal with polyaxon-cli ...

**Comment by mouradmourafiq** [comment]
Since v0.5, the admin dashboard shows a cluster wide experiments/jobs/builds and their current statuses.
