### ISSUE TITLE
Capability to customize docker registry

### ISSUE THREAD

**Issue by dyngts** [polyaxon/polyaxon#257]
### Feature motivation

Currently, every time polyaxon build the docker image will be stored in polyaxon-docker-registry pod. However, you might want to store it somewhere else (e.g: your team central image registry). Thus, we need to have feature which enable polyaxon store the docker image flexibly into any docker registry.

### Feature description

Add new section in polyaxon chart to add list of docker registries that can be deployed during job build. Then, experimenter can setting in polyaxon job file which docker registry they want to target.

### Feature implementation

cc @mouradmourafiq

**Comment by mouradmourafiq** [comment]
Next release v0.5, users can connect and use any external registry for pull/push operations.

Closing this issue for now, documentation for different registries will be published with the v0.5 release.

**Comment by dyngts** [comment]
wow this is great @ricardofbarros @mouradmourafiq. thanks for make this happen
