### ISSUE TITLE
Add cluster wide queue for experiments and jobs

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#263]
### Feature motivation

In order to maximize cluster usage without scheduling all workload on k8s directly, the user should be able to start an experiment/job `polyaxon run -f ...` with 2 extra prams `--queue[flag]` and `--priority`, i.e. `polyaxon run --queue` or `polyaxon run --queue --priority=high`.

This behaviour is different than the default `polyaxon run` in the sense that the experiment won't be send directly to k8s's default scheduler, but instead it will be queued by an internal queue. This will allow the user to set up a global concurrency that Polyaxon should respect during the experiment/jobs scheduling (keeping a maximum number of runs equal to the global concurrency) very similar to how experiment groups behave.

User will be able as well to check the queue's state at any time.

### Feature description

Allow the user to either start or delay a job/experiment.

> I would like to define a lot of experiments and experiment groups because I have a lot of models I would like to train and a lot of datasets to train on. Let's say that the total number of all those experiments is 20. But I have only 4 worker nodes. After defining that, I would like to do something else, and come back later to check the experiment results. Obviously, experiments must wait for other experiments to finish and to free up worker nodes before they could be started. I don't see the point of starting a job before there are no free worker nodes and then checking the heartbeat if they are being executed

### Feature implementation

Experiments/Jobs should have extra params to define scheduling policy (immediate/queued) with an execution priority.

Experiments/Jobs should start following a simple order: `order by --priority, --creation-date`

this is related to #253

**Comment by dyngts** [comment]
Hi @mouradmourafiq ,

I got confused with following statement
>before there are no free worker nodes

this should be "before there are free worker nodes", right?

**Comment by ajuric** [comment]
@dyngts I have written that, and I really meant "before there are no free worker nodes" - Or to put it differently: jobs shouldn't be started if there are no available worker nodes (all worker nodes are already executing other jobs).

Does this help?

**Comment by dyngts** [comment]
Ah, thanks @ajuric to clarify this.

**Comment by ajuric** [comment]
How is this progressing? We desperately need this thing :D

Yesterday I wanted to test once again how will current Polyaxon version 0.3.9 (and k8s) handle the situation when I define 50 experiments, but only have a couple of GPUs available - everything failed :(

All errors were OOM - I assume that it means that even k8s didn't wait for resources to be free but tried to schedule more experiments on the same resource (GPU).

**Comment by wematan** [comment]
Waiting anxiously...
When is version 0.5 due to close?

**Comment by wematan** [comment]
Any update on when this is expected?

**Comment by mouradmourafiq** [comment]
No timeline for now.

**Comment by mouradmourafiq** [comment]
Queuing is part of the agents mechanism which will not be part of the open source version.

There's a plan to put 100% of Polyaxon's code open source, but at the moment this is not a high priority, so I would suggest that users who have these type of advanced use-cases and want to use the open source platform to extend the core functionality of Polyaxon with their own logic, this can be achieved either by a custom k8s scheduler or Polyaxon executor.

V1.0.5 Polyaxon core was just merged, and a release should be expected soon, the API driven workflow has been improved, and there are 5 sdk languages (python, go, typescript, java, and javascript), so users can build logic to extend the core functionality.

Closing this issue for now.
