### ISSUE TITLE
Outputs tab wrong content

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#264]
### Describe the bug

A bug with the content of the `Outputs` tab.
I run an experiment, say n35, in my code I create my log.txt file, which become visible in the output of the experiment which is permanently filled. Then I run another experiment and in the `Outputs` tab I see my log.txt file and other files. But job is not yet scheduled. In the content of the log.txt I see the content of the previous log.txt, experiment 35.

### Environment
Polyaxon 0.3.1
GKE

**Comment by mouradmourafiq** [comment]
The reducers has much better state management, and this is fixed as a side effect of this new behavior.
