### ISSUE TITLE
[Bug] UI bug in outputs view

### ISSUE THREAD

**Issue by alexandreMayerowitz** [polyaxon/polyaxon#267]
### Describe the bug

When the outputs tree structure becomes too deep (3 with my own experience), we can not open folders and see files inside it. No matter the number of characters of each folder, the problem always appear with more than 2 nested folders.

### To Reproduce

Create an experiment that produces an output with nested folders (at least 3 folders).

### Expected behavior

No matter the output tree structure, every folder should be able to be opened in order to reveal its content.

### Environment

Polyaxon 0.3.1

**Comment by mouradmourafiq** [comment]
It should be fixed for the 0.3.2, I will keep you updated as soon as the fix is merged, thanks for reporting.

**Comment by alexandreMayerowitz** [comment]
Perfect!

**Comment by mouradmourafiq** [comment]
This is fixed and it will be part of the next release.
