### ISSUE TITLE
Button to download locally the 'outputs' of an experiment

### ISSUE THREAD

**Issue by cBournhonesque** [polyaxon/polyaxon#269]
### Feature motivation

Currently, I have to go inside a pod to copy the outputs folder for the experiment; I think it would be nice to directly be able to download the outputs (i.e. my model) from the UI

### Feature description
Maybe an additional button in the 'outputs' tab?

**Comment by mouradmourafiq** [comment]
this is a duplicate of #176.

You can also use `polyaxon experiment -xp id outputs` it will download a tar.gz of that experiment.
Same thing `polyaxon job -j id outputs`

**Comment by mouradmourafiq** [comment]
It will be part of next release (v0.3.3)
