### ISSUE TITLE
Config parser doesn't understand docker registries with port numbers

### ISSUE THREAD

**Issue by edshelton** [polyaxon/polyaxon#271]
My private docker registry is exposed on a port number other than 443/80, e.g. `registry.foobar.com:4567`. It seems that Polyaxon's config parser assumes that the presence of a colon always means the end of the registry endpoint + docker image name and the start of the docker image tag. This is not always the case.

To reproduce, simply point Polyaxon to a docker registry which is exposed with a port number rather than plain 80/443-exposed. 

### Expected behaviour

Polyaxon should use a smarter regex to parse docker images. Perhaps a better assumption to make would be that the _last_ colon in the string is what separates the registry + image name and the tag.

### Environment

Any/all environments

### Error

```
{'_schema': ['Invalid docker image registry.foobar.com:4567/my/docker/image:latest’]}
```

**Comment by edshelton** [comment]
I've dug through the code and the problematic line is here:

https://github.com/polyaxon/polyaxon-schemas/blob/804d01e96c4101f65d6c1dd9a6da75db4027a080/polyaxon_schemas/build.py#L20

**Comment by mouradmourafiq** [comment]
Thanks for the proposition, you should fix the issue in this line as well https://github.com/polyaxon/polyaxon-schemas/blob/804d01e96c4101f65d6c1dd9a6da75db4027a080/polyaxon_schemas/build.py#L79

**Comment by edshelton** [comment]
Thanks @mouradmourafiq , I've now fixed it there too

**Comment by mouradmourafiq** [comment]
Closing this as it's already merged. You can try it by using `master` tag for all services and updating the cli from source: `pip install -r requirements/requirements-dev.txt -e .`

**Comment by mouradmourafiq** [comment]
Thinking about this again maybe it's not needed if you provide the credentials to your private registry, [docs](https://docs.polyaxon.com/customization/private_registries/) and if the name of the image does not interfere with a public image, in that case using the name should work out of the box.
