### ISSUE TITLE
Add configurable hostname when TLS is disabled

### ISSUE THREAD

**Issue by edshelton** [polyaxon/polyaxon#278]
In cases where TLS is not used, and an ingress controller is used for name-based hosting, it would be nice to have an optional hostname configurable around here:

https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/templates/ingress/ing.yaml#L44

Also helps if your cluster is using something like external-dns to automatically create DNS records based on the presence of that hostname ingress configuration 🙂

**Comment by faezs** [comment]
@edshelton are you working on this? I could take it up if you aren't.

**Comment by edshelton** [comment]
I'm not, I'm afraid. Feel free to pick it up. Thanks!

**Comment by mouradmourafiq** [comment]
closing this since polyaxon/polyaxon-chart#20 is merged.
