### ISSUE TITLE
How to offline install and update imagePullPolicy as 'IfNotPresent'?

### ISSUE THREAD

**Issue by littlecarpenter** [polyaxon/polyaxon#279]
In some production environment, there is no internet access.

And I copied the images into the pod and execute the command below.
helm install polyaxon/polyaxon --name=polyaxon --namespace=polyaxon -f polyaxon_config.yml  --version 0.3.2

But  'imagePullPolicy'   in ~/.helm/cache/archive/polyaxon/values.yaml will be updated as 'Always'. Anyone can give some guide to offline install polyaxon.

**Comment by mouradmourafiq** [comment]
it's possible to set the `imagePullPolicy` per service, you need to update that in the deployment config yaml.
