### ISSUE TITLE
Got empty files when downloading experiment outputs

### ISSUE THREAD

**Issue by dyngts** [polyaxon/polyaxon#281]
### Describe the bug
Here's the bug, you want to download outputs coming from specific experiment (Let's named it as exp#2), however the downloaded file is contain nothing (it's expected to have some model files). 

To give you context, this experiment is resumed from previous experiment (Let's named it as exp#1) where the last state is `failed`.

### To Reproduce
I found the bug using following steps
1. I'm running exp#1 (original experiment) which yield several ML models as the outputs.
2. After long running, exp#1 got failed.
3. I'm trying to resume the experiment which trigger new experiment (exp#2) <-- is it expected to spawn new experiment instead using the same experiment?
4. Finally, the exp#2 job is done. I'm trying to download outputs from exp#2 to explore the model output offline. Unfortunately, i got empty downloaded files.
5. When trying download output from original experiment (exp#1), I'm able to download the output successfully (contains some ML models).

### Expected behavior
Refer to `To Reproduce` steps, during step 4, it should download files contain several ML models instead empty files.

### Personal Notes
I make following hypothesis for this bug:
- since resumed experiment create new experiment but not new output dir, it will refer to the old output dir.
- However, when click download output, it'll refer to the new output dir, hence will download empty files.

### Environment
I'm using the latest polyaxon version (0.3.3) run on top of GKE.

**Comment by mouradmourafiq** [comment]
This is fixed and will be part of next release 0.3.4.

**Comment by hadyan-tvlk** [comment]
Hi @mouradmourafiq, Want to follow up this. just to be sure, When we resume the experiment, how we treat the output:
1. will it copy the output from resumed experiment to the new experiment? or
2. The new experiment will refer to the output from old (resumed) experiment?

**Comment by dyngts** [comment]
Hi @mouradmourafiq, Want to follow up this. just to be sure, When we resume the experiment, how we treat the output:
1. will it copy the output from resumed experiment to the new experiment? or
2. The new experiment will refer to the output from old (resumed) experiment?

**Comment by mouradmourafiq** [comment]
`resume` appends outputs to the old experiment.

**Comment by yu-iskw** [comment]
@mouradmourafiq I still have the same issue with 0.4.1. We use GCS for the outputs storage. Do you think if the issue ptentially occurs with GCS?

**Comment by mouradmourafiq** [comment]
@yu-iskw yes cloud storages don't have these options yet, you can file a new issue to track the progress on that.
