### ISSUE TITLE
Dashboard customization

### ISSUE THREAD

**Issue by mongoose54** [polyaxon/polyaxon#282]
### Feature motivation

Customization of dashboard

### Feature description

Is there any plan to allow developers to customize the dashboard web page? e.g. custom logo, etc.

**Comment by mouradmourafiq** [comment]
I think there are more important things to build in the platform, e.g. better deployment guides, better integrations, more stability, more optimized scheduling, ... So, I think providing a way to customize the logo is not on the roadmap, however, if you have concrete customization that could be beneficial to users feel free to open another issue.
