### ISSUE TITLE
Received an invalid config, you need to provide a valid host.

### ISSUE THREAD

**Issue by mongoose54** [polyaxon/polyaxon#283]
### Describe the bug

When I do `polyaxon login` I get the following error `Received an invalid config, you need to provide a valid host.`

### To Reproduce
- I followed the deployment instructions (https://docs.polyaxon.com/installation/deploy_polyaxon/) and then I followed the output instructions in the `NOTES` output
- I did `polyaxon config set --host=$POLYAXON_IP --http_port=$POLYAXON_HTTP_PORT  --ws_port=$POLYAXON_WS_PORT` and it outputs `Config was updated.`
- When I do `polyaxon login` I get the following error: `Received an invalid config, you need to provide a valid host.`

### Environment
Virtualenv 2.7, MacOS Mojave

**Comment by mouradmourafiq** [comment]
It depends on how you deployed the platform and where, I think in your case it's a minikube, make sure you check this [section in the docs](https://docs.polyaxon.com/installation/deploy_polyaxon/#install-polyaxon-on-minikube), you should also check that the deployment has an ip `echo $POLYAXON_IP`.

**Comment by mongoose54** [comment]
@mouradmourafiq Thank you for the clarification and your help. 

You were right. I am using minikube. I am using [your instructions ](https://docs.polyaxon.com/installation/deploy_polyaxon/#install-polyaxon-on-minikube) (e.g. Helm, kubectl, etc.) and my deployment is getting an IP (`echo $POLYAXON_IP` returns `192.168.99.100`) . Couple of issues:
1) When I run `polyaxon login` and it prompts me to open the browser to `192.168.99.100:31264/app/token` . Why is it redirecting me to an app token? I am attaching my `config.yml`, which is the same with your tutorial one:

```
isMinikube: true

rbac:
  enabled: false

ingress:
  enabled: false

serviceType: LoadBalancer

user:
  username: "root"
  email: "root@polyaxon.local"
  password: "dummypassword"
```

2) More importantly when I put 192.168.99.100:31264 on my browser I cannot connect. Please see screenshot below

Thank you in advance!

![screen shot 2018-12-02 at 6 06 40 pm](https://user-images.githubusercontent.com/277391/49348938-1173e700-f65d-11e8-949d-a118a9424bde.png)

**Comment by mouradmourafiq** [comment]
1 - you will find an answer to your question in the [docs](https://docs.polyaxon.com/polyaxon_cli/commands/auth/#login)

2 - You need to check that your minikube is able to use `loadbalancer`, otherwise you can try a service type `NodePort`.
