### ISSUE TITLE
Add a button “copy to clipboard”.

### ISSUE THREAD

**Issue by ajuric** [polyaxon/polyaxon#284]
### Describe the bug

Formatting (new lines, tabs, ...) while copying text from config tab is not preserved. Instead, everything becomes one line.

### To Reproduce
Copy the text from config tab of any project and paste it to some editor (PyCharm, Atom, ...)

### Expected behavior
New lines and tabs should be preserved after pasting in the text editor.

### Environment
Ubuntu 16.04, Mozilla, PyCharm

**Comment by mouradmourafiq** [comment]
Should be part of next release v0.3.6. (At least works for all browsers on mac)

<img width="1231" alt="screenshot 2019-01-12 at 21 30 46" src="https://user-images.githubusercontent.com/1261626/51078158-615cb980-16b1-11e9-997a-60dfb11023f0.png">
