### ISSUE TITLE
Add documentation about SSL

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#288]
### Missing Documentation
Polyaxon is launched with http, not https by default. According to some code and configuration of polyaxon, it seems that we can configure SSL. I want to know how to set up SSL with polyaxon.

https://github.com/polyaxon/polyaxon/search?q=ssl&unscoped_q=ssl

**Comment by jayleverett** [comment]
This is something that I need as well. 

Based on [this](https://github.com/polyaxon/polyaxon-chart#securing-api-server-with-tls), I tried to do it by creating a self-signed cert and corresponding secret as described [here](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/tls#tls-certificate-termination):

```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -subj "/CN=foo.bar.com"
kubectl create secret tls tls-secret --key /tmp/tls.key --cert /tmp/tls.crt
```

then passing the secret to the Polyaxon config:

```
serviceType : NodePort

ingress:
  enabled: true
  tls:
    enabled: true
    secretName: tls-secret
```

This does not seem to have worked. 

@mouradmourafiq any guidance here?

**Comment by mouradmourafiq** [comment]
Next release v0.4.3 will provide docs for setting SSL when using node port, by providing self-signed certificat, hopefully docs for using `let's encrypt` as well.

The recommended way of course is to use an ingress with TLS enabled.

**Comment by mouradmourafiq** [comment]
@jayleverett if you want to use the ingress, you should use a service type `ClulsterIP`.

**Comment by mouradmourafiq** [comment]
The documentation has now several guides and integrations for serving Polyaxon over HTTPS, see [this for quick link](https://docs.polyaxon.com/guides/best-practices-for-deploying-polyaxon/#ssl) to all the content about HTTPS/SSL.

Closing this issue, pleae reopen if you have any question.
