### ISSUE TITLE
GPUS not showing up in aks

### ISSUE THREAD

**Issue by posix4e** [polyaxon/polyaxon#296]
### To Reproduce

GPUs do not show up in azure aks  after fresh helm quickstart
$ polyaxon cluster

Cluster info:

--------------  ----------------------------------------
build_date      2018-11-26T14:31:35Z
major           1
go_version      go1.10.3
git_version     v1.11.5
platform        linux/amd64
git_commit      753b2dbc622f5cc417845f0ff8a77f539a4213ea
git_tree_state  clean
minor           11
compiler        gc
--------------  ----------------------------------------

Cluster Nodes:

  sequence  name                      hostname                  role    memory      cpu    n_gpus
----------  ------------------------  ------------------------  ------  --------  -----  --------
         1  aks-nodepool1-...-0  aks-nodepool1-... -0  agent   49.94 Gb  5.916         0

$ az aks list
[
  {
    "aadProfile": null,
    "addonProfiles": null,
    "agentPoolProfiles": [
      {
        "count": 1,
        "maxPods": 110,
        "name": "nodepool1",
        "osDiskSizeGb": 256,
        "osType": "Linux",
        "storageProfile": "ManagedDisks",
        "vmSize": "Standard_NC6"
      }
    ],
..
    "enableRbac": true,
...
    "kubernetesVersion": "1.11.5",

```

### Expected behavior
GPUS showing up when showing polyaxon cluster

### Environment
On Azure aks with new cluster behavior

**Comment by mouradmourafiq** [comment]
It's an issue with AKS, I don't think they fixed it yet, here's the workaround: 
```
$ kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.10/nvidia-device-plugin.yml
```

see this [issue](https://github.com/Azure/AKS/issues/466#issuecomment-402849952) for more details.

**Comment by posix4e** [comment]
Do I need to restart polyaxon as well?

**Comment by mouradmourafiq** [comment]
no just executing that command will install the plugin, the cluster will make the gpus visible and Polyaxon will detect them shortly after, you can then schedule GPU experiments/jobs.

**Comment by posix4e** [comment]
great
