### ISSUE TITLE
catch a stop signal, execute some code before stopping an experiment

### ISSUE THREAD

**Issue by VinayTeki** [polyaxon/polyaxon#297]
## For Example:
I want to update my own database saying the experiment is **stopped / force-stopped** by user by executing the command `polyaxon experiment -xp 10 stop`, I would like to know what kind of signal is sent to my experiment before killing the pod.
I'm assuming the signal is good old `SIGTERM`
Saying `SIGTERM` is the signal, can I safely use the below block of code to handle before killing a pod.
```python
import signal
import sys
 
def signal_term_handler(signal, frame):
    print 'updating some stuff in my own database'
    sys.exit(0)
 
signal.signal(signal.SIGTERM, signal_term_handler)
```

**Comment by mouradmourafiq** [comment]
@VinayTeki the experiment just invokes a kubernetes API to stop the experiment/job.
On the db side different messages are added to the details column, depending if the experiment was stopped voluntary by the user, by an early stopping mechanism, or forced to stop by the system itself for some reason. Changin the internal behaviour of the platform is not possible at the moment, we are trying to expose a set of [hooks](https://github.com/polyaxon/polyflow) for people to write their own plugins/behaviour, but it's going to take some time.

**Comment by VinayTeki** [comment]
@mouradmourafiq Thankyou !

**Comment by mouradmourafiq** [comment]
I think one way to to annotate jobs with user defined information could be achieved using tags, the user can add a tag to determine experiment that have a specific termination behaviour.

```python
import signal
import sys
 
def signal_term_handler(signal, frame):
    client.set_tags(["user-terminated", "another-tag"]
    sys.exit(0)
 
signal.signal(signal.SIGTERM, signal_term_handler)
```
