### ISSUE TITLE
Polyaxon fails to finish jobs

### ISSUE THREAD

**Issue by posix4e** [polyaxon/polyaxon#303]
### Describe the bug
None of my jobs ever complete
### To Reproduce
Just launch the expected jobs. 
You'll see that they stay completed on k8s
81c4951967dbf49c^C
posix4e@localhost:~/src/polyaxon-example/cifar-tensorboard$ kubectl get pods -n polyaxonNAME                                              READY   STATUS      RESTARTS   AGE
plxjob-master0-204ae4e495284efda95c94d1e1b592ef   0/2     Completed   0          19h
plxjob-master0-a8c4aa173ec845e3be52f4823f3aa0e6   0/2     Completed   0          19h
and are still running on the dashboard
### Expected behavior
Jobs complete

**Comment by posix4e** [comment]
Yep it's on azure!

**Comment by mouradmourafiq** [comment]
In the future the watch process will be available in 2 forms (an additional option to run it as a sidecar), but for the moment this seems to be azure specific [issue](https://github.com/Azure/AKS/issues/522), there's a [workaround](https://github.com/Azure/AKS/issues/676), I will update here if this can be implemented.

**Comment by mouradmourafiq** [comment]
As a quick workaround, you can add:

```python
from polyaxon_client.tracking import Experiment
...
experiment = Experiment()
...
experiment.succeeded()
``` 

to your code to force the status change, more details in the [docs](https://docs.polyaxon.com/polyaxon_tracking/experiments/#succeeded).

**Comment by mouradmourafiq** [comment]
Next release 0.3.6, the watch process will be restarted every hour (default value) to work around this issue, I am not sure if this is also happening in other kubernetes cluster but we will make it the default behavior.

Depending on the cluster size the watch process TTL may be customized, an optional value can be  configured:

```yaml
ttl:
  watchStatuses:  # in seconds
```

Closing the issue for now.
