### ISSUE TITLE
Make .polyaxonignore honour .gitignore syntax

### ISSUE THREAD

**Issue by patrungel** [polyaxon/polyaxon#306]
It would be beneficial for `.polyaxonignore` to behave the same as`.gitignore` as this would bring the least surprise + lots knowledge + IDE perks.
`.gitignore` rules are well-defined and well-known; idioms, SOF answers, and templates are available in abundance.

Reference: [Git - .gitignore Documentation](https://git-scm.com/docs/gitignore)

**Comment by mouradmourafiq** [comment]
Next release the CLI will honor similar .gitignore syntax.

**Comment by lgeiger** [comment]
@mouradmourafiq I don't think this has been fully fixed yet.

I just started a run with a `.polyaxonignore` that matches the default [Python gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore).

Despite this file ignoring files matching `*.egg-info/`, the CLI uploaded `my_package.egg-info`.

**Comment by mouradmourafiq** [comment]
Can you run with `polyaxon -v run ... -u` it will show you the `IgnoreManager` logs.

I just put `polyaxon.egg-info` in root path and under another folder and it was ignored:

```
Root:., Dirs:['dags', 'experimentation', 'test', 'ci', 'optimization', 'git-integration', 'schedules', '__pycache__', 'build-containers', 'local-integration', 'hooks', 'examples', 'joins', 'how-tos', '.git', 'presets', 'polyaxon.egg-info', 'helpers', 'services', '.idea']
Ignoring file : .DS_Store
...
Root:./polyaxon.egg-info, Dirs:[]
Ignoring directory : ./polyaxon.egg-info
...
Root:./optimization, Dirs:['polyaxon.egg-info']
Root:./optimization/polyaxon.egg-info, Dirs:[]
Ignoring directory : ./optimization/polyaxon.egg-info
...
Root:./.idea, Dirs:['markdown-navigator', 'inspectionProfiles', 'codeStyles']
Ignoring directory : ./.idea
```

**Comment by mouradmourafiq** [comment]
This rule was not respected in [gitignore](https://git-scm.com/docs/gitignore):

> If there is a separator at the end of the pattern then the pattern will only match directories, otherwise the pattern can match both files and directories.
