### ISSUE TITLE
Unable to delete a user from the admin dashboard

### ISSUE THREAD

**Issue by edshelton** [polyaxon/polyaxon#307]
### Describe the bug
```
Deleting the user 'foobar' would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:

activity log
```
as the root user.

### Expected behavior
root user should be able to delete any user regardless of related objects

**Comment by mouradmourafiq** [comment]
The error was due to the cluttered admin interface, a change has been made to only leave: Users and Tokens in the admin interface.

**Comment by naetherm** [comment]
Tested on polyaxon 0.3.7, we are also unable to delete users via the CLI. An example with a dummy-user I've created:
```
polyaxon user delete dummy2
```

And the result of the operation:
```
Could not delete user `dummy2`.

Error message `405 on http://xxx/api/v1/users/delete/dummy2/.`.
```
