### ISSUE TITLE
Project Tensorboards do not show new experiments

### ISSUE THREAD

**Issue by notsimon** [polyaxon/polyaxon#314]
### Describe the bug

When a project Tensorboard is started, any experiment created after this point wont be shown.

### To Reproduce

```
polyaxon run -u # this experiment will be shown in the Tensorboard
polyaxon tensorboard -p quick-start
polyaxon run -u # this experiment wont
```

### Expected behavior

The Tensorboard listing should be updated each time a new experiment is run. To begin with, maybe an automated restart of the Tensorboard would do ?

**Comment by mouradmourafiq** [comment]
Since we will be supporting a unique outputs backend from v0.3.9, the Tensorboards will be using absolute paths.

Closing this, feel free to reopen if you have the same issue after the upgrade.
