### ISSUE TITLE
Security - LDAP UID and GID management

### ISSUE THREAD

**Issue by rapatel0** [polyaxon/polyaxon#316]
### Feature motivation
Currently, all polyaxon experiments run as root user. This represents a security concern as users can effectively run arbitrary code as root user. This also complicates storage access as permissions are not propagated to output files that are generated. Running as "non-root" is essential for security compliance in most scenarios. 

### Feature description 
UIDs and GIDs are pulled from LDAP and stored in the local user cache.

Policy template for kubernetes that is harmonized with UID and GID pulled from the LDAP and propagated when a user runs and experiment or builds a container.

### Feature implementation
Steps (not sure if this is a complete list)
1. A separate kuberntes role and service account for experiment jobs 
1. Store UID and GID for the run user in posgres with token (not sure how local users are created) 
1. Set security context for pod in `polyaxon/polyaxon/scheduler/spawners/templates/project_jobs/pods.py`
1. Modify init container to change storage permissions for target user and add umask to container
1. (potentially) add user to dockerfile during build

#### Alternate implementation

**Comment by rapatel0** [comment]
Another Potential fix is to have additional lines that that are added to the Dockerfile build process that are under control of only the cluster-admin that are added during a docker file build. That would at least limit the runtime user.

**Comment by mouradmourafiq** [comment]
Although is not link to the LDAP UID and GID, Polyaxon has a security context starting from v0.5 that can be applied to all running pods started by Polyaxon. Additional work will be done in future releases.

Closing this issue for now.
