### ISSUE TITLE
Add a sub command to get the list of users.

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#317]
### Feature motivation
Superusers sometimes want to check the list of users. To do that, we need to look into the databasae now. A command to get the list of users would be quite useful. 

The command looks like the follosing:
```
$ polyaxon user list
```

### Feature description
- The command is used to get the list of users. 
- The command works with only superusers. The command doesn't allow normal users to get the list of users.
- It doesn't show any sensitive information, such as tokens and passwords.

**Comment by mouradmourafiq** [comment]
The admin view will be enabled by default for the next release, and as an admin you will see all users from that admin UI.

**Comment by yu-iskw** [comment]
@mouradmourafiq That sounds great! Thank you for the quick response as always.
