### ISSUE TITLE
experiment/metrics page loads very slowly, possibly due to lots of data

### ISSUE THREAD

**Issue by harpone** [polyaxon/polyaxon#318]
### Describe the bug
Currently I'm outputting training loss values etc. per every iteration, and displaying the metrics becomes painfully slow for about 10k iterations and more (100k iters takes insanely long).

Is there a way to mitigate the load time or should I just output fewer data points?

**Comment by mouradmourafiq** [comment]
I agree, the current component is not very well optimized, and the rerendering part is very slow. There's also an issue with the underlying library, plotly, that gets also slow.

I think for now you should limit the amount of data points you log during the training until we find a better approach.

**Comment by harpone** [comment]
OK thanks, will do that!
