### ISSUE TITLE
polyaxon-dockerizer's docker client should use the proxy envs

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polyaxon#320]
### Describe the bug
The pod responsible for building the docker image does not read the proxy settings from the environment variable set by the docker daemon.

### To Reproduce
Deploy polyaxon 0.3.5 to minikube cluster in a proxy protected network. Run the `polyaxon-quick-start` example from the documentation. The build job fails with no output only `errors.`. By setting the proxy manually utilizing `env_vars` it still fails with connection errors.

```log
2019-01-11 15:10:18 UTC -- /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
2019-01-11 15:10:20 UTC -- Extracting /data/mnist/train-images-idx3-ubyte.gz
2019-01-11 15:10:20 UTC -- Extracting /data/mnist/train-labels-idx1-ubyte.gz
2019-01-11 15:10:20 UTC -- Extracting /data/mnist/t10k-images-idx3-ubyte.gz
2019-01-11 15:10:20 UTC -- Extracting /data/mnist/t10k-labels-idx1-ubyte.gz
2019-01-11 15:10:20 UTC -- /usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
2019-01-11 15:10:20 UTC --   from ._conv import register_converters as _register_converters
2019-01-11 15:10:20 UTC -- Request to http://polyaxon-polyaxon-api:80/api/v1/root/quick-start/experiments/14/token/ failed with status code 503.
```

**Possible workaround**
Add the proxy manually to the build in the `polyaxonfile.yml` and add `polyaxon-polyaxon-api` to the `no-proxy` variable.
```
---
version: 1

kind: experiment

build:
  image: tensorflow/tensorflow:1.4.1-py3
  build_steps:
    - pip3 install --no-cache-dir -U polyaxon-client
  env_vars:
    - [http_proxy, "http://wwwproxy.example.com:8080"]
    - [https_proxy, "http://wwwproxy.example.com:8080"]
    - [no_proxy, "polyaxon-polyaxon-api"]
run:
  cmd:  python3 model.py  # Use default params
```
The problem with this solution is that all `polyaxonfile.yml` configurations need to be modified between different network environments.

### Expected behavior
The docker-py client inside the polyaxon builder pod should read the proxy configuration from the environment variables set by the docker daemon that has been configured for the k8s cluster.

Possibly related to https://github.com/docker/docker-py/issues/2199
Could possibly be solved by upgrading docker-py dependency to 3.7.0
https://github.com/polyaxon/polyaxon/blob/master/requirements/dockerizer/requirements-base.txt#L3
### Environment
minikube version: v0.32.0
kubectl version:
```yaml
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
polyaxon-cli: 0.3.5
polyaxon cluster:
```
Cluster info:

--------------  ----------------------------------------
git_tree_state  clean
go_version      go1.10.4
git_version     v1.12.4
minor           12
git_commit      f49fa022dbe63faafd0da106ef7e05a29721d3f1
platform        linux/amd64
compiler        gc
major           1
build_date      2018-12-14T06:59:37Z
--------------  ----------------------------------------

Cluster Nodes:

  sequence  name      hostname    role    memory      cpu    n_gpus
----------  --------  ----------  ------  --------  -----  --------
         1  minikube  minikube    master  7.32 Gb       4         0
```

**Comment by jiayiwang7** [comment]
Any updates?

**Comment by AntonFriberg** [comment]
There has been an update according to https://docs.polyaxon.com/configuration/custom-run-environment/

This at least let's you set default environment variables for scheduled runs.

> Env vars
Polyaxon now allows to set env vars to be used when scheduling runs, this allows users to expose some environment variables on every run without defining a config map or setting those environment variables on the docker image.
In order to set the default environment variables, you can update the ENV_VARS in the setting page for every primitive.

**Comment by mouradmourafiq** [comment]
Closing this as well, users can now set env vars and also they can change the networking interface of the container.
