### ISSUE TITLE
Cannot access _admin/db/user/<ID>/change/ page

### ISSUE THREAD

**Issue by naetherm** [polyaxon/polyaxon#325]
### Describe the bug

With an activated admin dashboard we are unable to access the edit pages for the users after creating a new user. 

The error message is: 
```
Error
Something went wrong.
Polyaxon
```

### To Reproduce
We've created a new user through the admin dashboard.

EDIT: Because it could be important: Because we've set it through the backend the user just has a username and no email set.

### Expected behavior
-

### Environment
```
Current platform version: 0.3.7.
```

**Comment by mouradmourafiq** [comment]
I could not reproduce this. I just created users using the admin and the registration form, and I am able to access the edit page.

**Comment by mouradmourafiq** [comment]
Feel free to reopen.
