### ISSUE TITLE
Enriching Functionality of Code Versioning

### ISSUE THREAD

**Issue by sakinaljana** [polyaxon/polyaxon#328]
### Feature motivation

I'm aware that Polyaxon support for code versioning by using commit id. However, i found some limitation to explore the code versioning. I propose feature enrichment of the code versioning  that can mimicking git like functionality (e.g: track down commit history, rollback to specific commit)

### Feature description
Enable Polyaxon CLI to have command like `polyaxon repo [ACTION]`, ACTION can be:
- track down the upload history by commit
- rollback the code to the specific commit

### Feature implementation
The technical changes should be:
- adding API to GET/POST the information related to code versioning.
- Adding new command in Polyaxon CLI to enable query related to code versioning.

**Comment by notsimon** [comment]
A leaner solution might be to just expose the internal Git repositories. Adding these as a *read-only* remotes would allow us to checkout, explore and cherry-pick the code of any experiment using the standard Git flow.
