### ISSUE TITLE
Unable to login to Polyaxon after downscaling Kubernetes cluster

### ISSUE THREAD

**Issue by jayleverett** [polyaxon/polyaxon#329]
Hi - I'm experiencing a similar issue to  #294 running version 0.3.7 of both the cli and the helm chart.

This has happened several times, and in each case I've successfully logged in to the cluster/dashboard and worked with it for several days following the deployment. At some point, though, I seem to get randomly locked out and polyaxon becomes unusable. 

Here's some detail on the specific errors I'm seeing. 

`polyaxon run` fails with a 403 error:

```
jay@Jays-MacBook-Pro polyaxon_test $polyaxon run
Creating an independent experiment.
Request to http://a06e8ca231a7411e9b3b812c0552c227-1883442768.us-east-1.elb.amazonaws.com:80/api/v1/root/test/experiments/ failed with status code 403.
Reason: {"detail":"Authentication credentials were not provided."}
Error while creating experiment.: None

Could not create experiment.


Error message `403 on http://a06e8ca231a7411e9b3b812c0552c227-1883442768.us-east-1.elb.amazonaws.com:80/api/v1/root/test/experiments/.`.
```

`polyaxon login` fails with a 400 error:

```
jay@Jays-MacBook-Pro polyaxon_test $kubectl get secret --namespace polyaxon polyaxon-polyaxon-secret -o jsonpath="{.data.POLYAXON_ADMIN_PASSWORD}" | base64 --decode
rootpasswordjay@Jays-MacBook-Pro polyaxon_test $
jay@Jays-MacBook-Pro polyaxon_test $polyaxon login -u root -p rootpassword

Could not login.


400 on http://a06e8ca231a7411e9b3b812c0552c227-1883442768.us-east-1.elb.amazonaws.com:80/api/v1/users/token/.
```

Logging in through the browser also fails.

My helm deployment is successful, and `helm upgrade polyaxon ...` does not fix the issue:

```
jay@Jays-MacBook-Pro polyaxon_test $helm history polyaxon
REVISION        UPDATED                         STATUS          CHART           DESCRIPTION
1               Thu Jan 17 11:22:04 2019        SUPERSEDED      polyaxon-0.3.7  Install complete
2               Wed Jan 23 11:53:07 2019        DEPLOYED        polyaxon-0.3.7  Upgrade complete
```

Running some `kubectl` commands, I *think* the issue may be caused by long-running notebook jobs that experience some sort of failure, but I'm not sure of this at all. Here's what I'm seeing on that side of things:

```
jay@Jays-MacBook-Pro polyaxon_test $kubectl -n polyaxon get deployments
NAME                                            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
plx-notebook-0a536248ce9b45099dae16f9c8bcbaa3   1         1         1            0           10d
polyaxon-docker-registry                        1         1         1            1           11d
polyaxon-polyaxon-api                           1         1         1            1           11d
polyaxon-polyaxon-beat                          1         1         1            1           11d
polyaxon-polyaxon-events                        1         1         1            1           11d
polyaxon-polyaxon-hpsearch                      1         1         1            1           11d
polyaxon-polyaxon-k8s-events                    1         1         1            1           11d
polyaxon-polyaxon-monitors                      1         1         1            1           11d
polyaxon-polyaxon-scheduler                     1         1         1            1           11d
polyaxon-postgresql                             1         1         1            1           11d
polyaxon-rabbitmq                               1         1         1            1           11d
polyaxon-redis                                  1         1         1            1           11d
jay@Jays-MacBook-Pro polyaxon_test $kubectl --namespace polyaxon get pod
NAME                                                             READY     STATUS             RESTARTS   AGE
plx-notebook-0a536248ce9b45099dae16f9c8bcbaa3-76dc4565cf-tdbbb   0/1       ImagePullBackOff   0          27m
polyaxon-docker-registry-759d6b595b-jlvzv                        1/1       Running            0          10d
polyaxon-polyaxon-api-6d5b95685-lfgwf                            2/2       Running            0          4d
polyaxon-polyaxon-beat-69d4696cb-qn242                           2/2       Running            0          4d
polyaxon-polyaxon-events-667755cf96-bgmmq                        1/1       Running            0          4d
polyaxon-polyaxon-hpsearch-845c95dbf9-kr6q2                      1/1       Running            0          4d
polyaxon-polyaxon-k8s-events-5fd9b6d95-wmpbf                     1/1       Running            0          4d
polyaxon-polyaxon-monitors-867bdf7687-gvvq2                      2/2       Running            0          4d
polyaxon-polyaxon-resources-t9mbr                                1/1       Running            0          4d
polyaxon-polyaxon-scheduler-fddcdb9d9-l8b5p                      1/1       Running            0          4d
polyaxon-postgresql-857f55f766-mprwz                             1/1       Running            0          10d
polyaxon-rabbitmq-67bf589c-gqlsq                                 1/1       Running            0          10d
polyaxon-redis-7c799674bf-d7n22                                  1/1       Running            0          10d
```

`polyaxon notebook stop` also fails with a 403 error.

So far, the only workaround I've found here is to completely nuke the deployment and start over:

```
helm delete polyaxon --purge
kubectl delete namespaces polyaxon
```

This has been ok for now since I'm just testing, but obviously it's not an option in a production scenario. So while I'd love to have a fix, even just a workaround that would allow me to recover more gracefully in this situation would be very helpful.

**Comment by jayleverett** [comment]
I now have a better idea what's causing this issue, and it is NOT long-running notebook jobs. **The issue occurs when I downscale my cluster to include fewer worker nodes.**

I'm using EKS and scaling worker nodes via CloudFormation as described [here](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html). When I scale up everything is fine, but when I downscale I end up with an error like this:

```
jay@JaysMBP polyaxon_test (master)*$polyaxon dashboard

Could not get cli version.


Error message `Error connecting to Polyaxon server on `http://a88b256d6297811e9b3b812c0552c227-1525383779.us-east-1.elb.amazonaws.com:80/api/v1/versions/cli/`.
An Error `('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))` occurred.
Check your host and ports configuration and your internet connection.`.
```

I assume that this is because the host that Polyaxon is expecting has been terminated. If I run `polyaxon login` I get an error in my browser saying the page received no data.

After running `helm upgrade polyaxon polyaxon/polyaxon -f polyaxon_config.yml`, `polyaxon login` page takes me to the login page as expected, only now I receive an error when attempting to log in (as root and with any user accounts I've created). For what it's worth, the `POLYAXON_IP` remains the same.

I still have no idea how to recover from this, however. My only solution continues to be to delete and reinstall Polyaxon. 

If someone can offer a potential workaround, it would be greatly appreciated.

**Comment by mouradmourafiq** [comment]
Hi @jayleverett, I had some doubts, but thanks for clarifying.

You are seing this issue because the db node is being destroyed as well, and so you are losing all your data (no users => you cannot login).

You need to check this [guide](https://docs.polyaxon.com/customization/postgresql_ha/) to persist your postgres data.

**Comment by jayleverett** [comment]
Awesome, thanks Mourad. Persisting the Postgres data seems to have fixed the issue.

I'm loving Polyaxon btw! Keep up the great work!
