### ISSUE TITLE
[UI] Add [?] to jobs as in experiments

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#332]
### Feature motivation

It would be good to add [?] button to "Jobs" when it fails with a log as it is done for "Experiments" in the dashboard.

### Feature description

This will help to debug Kubernetes problem for example

Experiment:
![screen shot 2019-02-01 at 15 27 44](https://user-images.githubusercontent.com/2459423/52129650-5524a600-2638-11e9-8375-5e3ad86dec90.png)

Job:
![screen shot 2019-02-01 at 14 40 40](https://user-images.githubusercontent.com/2459423/52129651-5524a600-2638-11e9-9d52-bafbd3008891.png)

Thanks

**Comment by mouradmourafiq** [comment]
jobs now have a complete view, with details about their statuses.
