### ISSUE TITLE
Version mismatch?

### ISSUE THREAD

**Issue by naetherm** [polyaxon/polyaxon#334]
### Describe the bug
Today we upgraded the CLI and Server software to 0.3.8, after checking the version we receive the following through:
* ```polyaxon version```:
```Current cli version: 0.3.8.

Supported cli versions:

--------------  -----
latest_version  0.3.0
min_version     0.3.8
--------------  -----
```

* ```polyaxon version --platform```:
```
Current platform version: 0.3.8.

Supported platform versions:

--------------  -----
latest_version  0.3.1
min_version     0.3.8
--------------  -----

```

### Expected behavior
Thought that ```latest_version``` will be ```0.3.8``` instead of ```0.3.0/0.3.1```.

**Comment by mouradmourafiq** [comment]
Thanks for reporting, it was fixed, but the commit was not part of the release, sorry about that.
