### ISSUE TITLE
Support multiple secret names in ingress tls

### ISSUE THREAD

**Issue by paktek123** [polyaxon/polyaxon#335]
Im trying to add multiple ingress hosts with different TLS secret names but looks like the chart only supports one TLS secret for multiple hosts.

https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/templates/ing.yaml#L26

Are there any plans to add multiple secret for different hosts?

**Comment by mouradmourafiq** [comment]
The ingress in helm chart was update to accept a list for the `ingress.tsl` field. This change will be part of v0.4.3.

**Comment by paktek123** [comment]
thanks!
