### ISSUE TITLE
Empty reason when creating an experiment

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#337]
I have the following error when I create 2nd time the experiment with name `xp_check_nvidia-smi`, but the first experiment with the same name I previously deleted:
```
$ polyaxon run -u -f xp_check_nvidia-smi.yaml --name=xp_check_nvidia-smi
$ polyaxon experiment delete
$ polyaxon run -u -f xp_check_nvidia-smi.yaml --name=xp_check_nvidia-smi
[================================] 596/596 - 00:00:00

Files uploaded.

Creating an independent experiment.
Request to http://IP:PORT/api/v1/root/sanity_checks/experiments/ failed with status code 405. 
Reason: 
Error while creating experiment.: None

Could not create experiment.


Error message `405 on http://IP:PORT/api/v1/root/sanity_checks/experiments/.`.
```

Thanks

PS.: I was also wondering whether we could not have by default a behaviour such that experiment name becomes `polyaxonfile.N` inherited from `polyaxon run -f polyaxonfile.yaml` ?
To avoid `--name=polyaxonfile[.N]`

**Comment by vfdev-5** [comment]
> I was thinking about that as well, but this could confuse the users further when they search for their experiments?

Maybe it can confuse users too. Actually, we have the following behaviour:

- User launch 3 experiments as (it can happen that the content between launches could change)
``` 
polyaxon run -u -f xp_train_r50.yaml
```
and then 2 times
``` 
polyaxon run -f xp_train_x101.yaml
```
In the dashboard user will see
```
username.project_name.1
username.project_name.2
username.project_name.3
username.project_name.4
username.project_name.5
```
So, by default if he/she does not  provide any tags or description of experiment it is very difficult to know what is where. 
In case if experiment name inherits of config file name (and eventually adding username) we would have
```
username.xp_train_r50.1
username.xp_train_r50.2
username.xp_train_r50.3
username.xp_train_x101.1
username.xp_train_x101.2
```

Maybe we could keep by default current behaviour and add what I proposed as some customization options.  @mouradmourafiq what do you think ?

**Comment by mouradmourafiq** [comment]
Sounds good, I will first introduce the unrachiving behaviour so that people at least know that the experiments/jobs/projects are still not deleted, and then introduce this behaviour for naming entities.

**Comment by mouradmourafiq** [comment]
The next v0.3.9 will have 2 button to distinguish between the 2 uses case:

* Delete: stop the job/build/xp if running and delete the record and any logs/outputs
* Archive: set archive flag and schedule for deletion with possibility to restore.

This will solve the issue you are seeing with name error after deletion.

**Comment by mouradmourafiq** [comment]
So future behaviour for unique names (builds, jobs, exps, groups):
 * better validation and exceptions
 * name will have a counter when the entity is created with cli/api: `foo`, then `foo-1`, `foo-2`, ...

Closing this for now, feel free to reopen if you have the same issue after upgrading to v0.3.9.
