### ISSUE TITLE
Remove outputs when removing experiments

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#339]
### Feature motivation
It seems that outputs remain in the storage even if we remove experiments with both of CLI and the web UI. In terms of the used storage size of outputs in NFS, how to remove unnecessary files can be crucial.

### Feature description
1. When we remove experiments with the web UI, the outputs (and logs) are deleted.
2. When we remove experiments with CLI, the outputs (and logs) are deleted.

**Comment by mouradmourafiq** [comment]
what version are you running?

By Web UI, do you mean the admin interface?

**Comment by yu-iskw** [comment]
We use polyaxon 0.3.7. And I mean, the web UI is not admin interface. It is a regular project page.
I tested deleting an experiments and an experiment group with the web UI, but the data on NFS remained.

**Comment by mouradmourafiq** [comment]
this is related to #337, it will be fixed in v0.3.9

**Comment by yu-iskw** [comment]
I see. Thank you for answering my questions.

**Comment by mouradmourafiq** [comment]
The next v0.3.9 will have 2 button to distinguish between the 2 uses case: 
 * Delete: stop the job/build/xp if running and delete the record and any logs/outputs
 * Archive: set archive flag and schedule for deletion with possibility to restore.

Closing this as the change is already made.
