### ISSUE TITLE
Regexp search bar in metrics tab

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#344]
### Feature motivation

It could be useful to have a regexp search bar (as in Tensorboard) in metrics tab of a single experiment (or experiment group).

**Comment by mouradmourafiq** [comment]
This is the new default behaviour, similar to #661 (which is on experiment level), dashboard are are created on project level and can be promoted to org level, both for experiment and for multi-experiments.
The change also solves #346, search bar can be used to restrict the runs to compare (either based on metrics query, e.g. `metrics.loss:<0.1` or a regex `name:%foo` (all runs ending with foo))

<img width="1270" alt="Screenshot 2020-04-07 at 21 25 00" src="https://user-images.githubusercontent.com/1261626/78710838-4c072700-7916-11ea-9e44-7ccc3d94819f.png">
