### ISSUE TITLE
API unreachable after a few hours

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#348]
### Describe the bug
After I let the cluster run over night, the api and webinterface were not available anymore. The AWS ELB reports all attached instances as `OutOfService`. Upon checking the pods I noticed that `polyaxon-polyaxon-api-5b966d9768-...` was reported as `Running` with `0/2` ready

last events:
```
LAST SEEN   FIRST SEEN   COUNT     NAME                                                      KIND      SUBOBJECT                           TYPE      REASON      SOURCE                                                MESSAGE
16m         1h           96        polyaxon-polyaxon-api-5b966d9768-m4h2h.15815bbe4f1ab648   Pod       spec.containers{polyaxon-api}       Warning   Unhealthy   kubelet, ip-172-20-42-75.eu-west-1.compute.internal   Liveness probe failed: Get http://100.96.4.35:80/_health/: dial tcp 100.96.4.35:80: getsockopt: connection refused
10m         1h           111       polyaxon-polyaxon-api-5b966d9768-m4h2h.15815bc0faefa1eb   Pod       spec.containers{polyaxon-api}       Warning   Unhealthy   kubelet, ip-172-20-42-75.eu-west-1.compute.internal   Readiness probe failed: Get http://100.96.4.35:80/_health/: dial tcp 100.96.4.35:80: getsockopt: connection refused
1m          1h           115       polyaxon-polyaxon-api-5b966d9768-m4h2h.15815bc28edb7d8d   Pod       spec.containers{polyaxon-streams}   Warning   Unhealthy   kubelet, ip-172-20-42-75.eu-west-1.compute.internal   Readiness probe failed: Get http://100.96.4.35:1337/_health/: dial tcp 100.96.4.35:1337: getsockopt: connection refused
36m         1h           8         polyaxon-polyaxon-api-5b966d9768-m4h2h.15815c043ca18df3   Pod       spec.containers{polyaxon-api}       Normal    Killing     kubelet, ip-172-20-42-75.eu-west-1.compute.internal   Killing container with id docker://polyaxon-api:Container failed liveness probe.. Container will be killed and recreated.
```
### To Reproduce
No idea, but I'm open to suggestions

### Environment
Polyaxon: `v0.3.8`
Kubernetes: `v1.10.12`  
node OS: `Debian GNU/Linux 9 (stretch)`
node Kernel:   `4.9.0-7-amd64`
Docker: `17.3.2`
### Note
The occurence coincided with rabbitmq draining cpu credits on the t2.small instance where the api pod was located besides the rabbitmq (#309)
Replacing the node with a fresh one did not solve the issue though.

**Comment by Mofef** [comment]
I'm still not sure why it happened in the first place, but I found out how to resolve it:
* log in to the `polyaxon/polyaxon-api` docker container with `docker exec -it <containerID> bash`
  * when doing `python3 polyaxon/manage.py showmigrations --plan` You will find a list of migrations, that none of them were completed and apparently not even started (the container was waiting for this to finish)
  * run `python3 polyaxon/manage.py migrate` to do the migration
* wait a few minutes, then the api should be back up 

I hope that's helpful :)

**Comment by mouradmourafiq** [comment]
it's seems that your deployment did not complete or timed out, Polyaxon provides hooks to execute those migrations as well as other important steps.

I suspect that it's a resource issue, i.e. you mentioned the CPU problem. I will close the issue, feel free to reopen it. You might add some restriction on the containers, similar to the e2e test case in the `polyaxon-chart` repo.

**Comment by Mofef** [comment]
Thank you. I will have a look :) 
Just to make sure we are on the same page: Polyaxon was sucessfully deployed and did work but then stopped working.
If I experience the same issue again I'll let you know

**Comment by mouradmourafiq** [comment]
thanks 👍
