### ISSUE TITLE
A easy way to interact with a built dockerimage. E.g. launch container and exec bash

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#350]
### Feature motivation
When running a `Job` (/`Experiment`/whatever) you might have a dependency problem that is not all that obvious to fix.  

### Feature description
It would be great to then jump into the container and investigate the problem, but the pod is already `Completed`/`Failed` so `exec -it bash` does not work. Starting a container with the built image could be an easy solution.

**Comment by mouradmourafiq** [comment]
Can you put a time sleep in your code, this is will prevent it from failing, then you can exec -it.
Is local testing an option as well?

**Comment by Mofef** [comment]
Ok that sounds very hacky, but if its the easiest way to go I will give it a try. Thanks :)
Local testing as in running that image on my local machine? Sure! I just didn't find out where the Image is stored nor how to access it.

**Comment by mouradmourafiq** [comment]
I think this is related to this feature request #351 ?

**Comment by Mofef** [comment]
So what we are doing so far is add a sleep, rerunning, then attach to the pod with kubectl exec. So I will close this. 
... though, I think it would be very handy feature if polyaxon would offer this functionality directly :)
