### ISSUE TITLE
Customizable model_dir with get_tf_config

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#353]
## Motivation
We sometimes have data sets on google cloud storage for tensorflow and we didn't created them with polyaxon jobs. For instance, we use apache beam with google data flow in order to create a TFRecord dataset at scale, since we sometimes deal with millions of data points. That is,

1. We store the training/testing data outside of polyaxon on GCS.
2. We run distributed training with the created data on GCS and store the models in a custom GCS path.

However, `Experiment.get_tf_config` uses `get_output_path` by default.  Technically, we can overwrite `TF_CONFIG` after calling the method. But it is a little bothersome.
```
experiment = Experiment()
tf_config = experiment.get_tf_config()
tf_config['model_dir'] = YOUR_PATH
os.environ['TF_CONFIG'] = json.dumps(tf_config)
```
https://github.com/polyaxon/polyaxon-client/blob/5c969c5771ecb1b4cab9d9de7a7c373b457b9e18/polyaxon_client/tracking/experiment.py#L373

## Feature Specification
It would be great to have a feature to custormize `model_dir` with `get_tf_config`.

```
experiment = Experiment()
experiment.get_tf_config(model_dir="gs://.......")
```

**Comment by yu-iskw** [comment]
You are correct. When we use GCS as a storage of polyaxon, polyaxon automatically use the GCS. But, if some users use only NFS, but they want to save the model on GCS. In such a case, it would be great to customize `model_dir`.

**Comment by mouradmourafiq** [comment]
that will make the platform behave in a very inconsistent way. The outputs UI/CLI will be return 404, lineage/dependency will not work...
