### ISSUE TITLE
Support AWS IAM authentication for s3 storage

### ISSUE THREAD

**Issue by danielchalef** [polyaxon/polyaxon#357]
### Feature motivation

Many AWS users strongly prefer not to use stored IAM credentials (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY) for authentication and authorization to AWS services. Rather, role-based authentication is used.

When configuring Polyaxon, these credential fields appear to be mandatory for setup of s3 storage. Most AWS SDKs are capable of operating in a mode that utilizes roles rather than provided credentials. Removing this requirement would make use of role-based authentication possible.

### Feature description

Remove requirement for AWS credentials when configuring s3 storage.

### Feature implementation

Note: The simplest approach to supporting this is described above. Role implementation (using any number of methods) would be left to the end-user.

**Comment by mouradmourafiq** [comment]
The `annotations` section is exposed under `environment`  in v1.1 specification.
