### ISSUE TITLE
[UI] Update tags of multiple experiments

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#361]
### Feature motivation

It would be useful and helpful to be able to update tags of multiple experiments afterwards. 
@mouradmourafiq what do you think ?

**Comment by mouradmourafiq** [comment]
Yes, but that a too much UI work to prioritize. Another option, which I will do, is to provide a small guide on how to use the client or the API to programatically query experiment based on some criteria, and update them.

The UI will be refactored and simplified (smaller packages) so if people want to jump in and help with this issue.

**Comment by mouradmourafiq** [comment]
Not sure when the new UI will be available to everyone, but this got requested a couple of more times, so it's now part of the multi-runs actions:

![Screenshot 2020-03-17 at 23 34 34](https://user-images.githubusercontent.com/1261626/76907974-e7712300-68a7-11ea-8cc4-873228fecdf4.png)

Closing the issue.
