### ISSUE TITLE
Add `annotations` to `environment` in `polyaxon.yaml`

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#365]
### Feature motivation

In order to give some experiments/jobs access to a s3 bucket I'd like to use https://github.com/jtblin/kube2iam (I'm open for alternatives)
kube2iam assignes IAM roles to pods based on their annotations. 
I didn't find a way to do that. Might be I overlooked something though.

### Feature description

Accept `metadata`/`annotations` under `environment` in a polyaxon yaml
(I ran into #356 when I was just trying that)

**Comment by mouradmourafiq** [comment]
This is related to #357.

v0.3.9 will be released today, if you have still see #356, please let me know. Thanks.

**Comment by Mofef** [comment]
Cool, thanks! I'll let you know.
I wasn't even aware of the fact that polyaxon supports credential based authentication. For now that's enough to continue our tests. :) In general I would agree with #357.

**Comment by stratospark** [comment]
@mouradmourafiq Is it now possible to add annotations to pods?

I am using kubernetes cluster-autoscaler and need to prevent it from moving notebook and experiment pods around. To do so, they [recommend](https://github.com/kubernetes/autoscaler/blob/640a72481455480828921953ffbb56c529736722/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node) adding this annotation: `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"`

Even better, would it be possible to set default annotations on these types of pods?

**Comment by mouradmourafiq** [comment]
I completely forgot about this one, I did not include it in the roadmap. A release is coming tomorrow/after tomorrow, and will not include the annotations. But I promise to add it for the the short term roadmap, so it will be in one of the minors of v0.5, (several minor release will follow the v0.5, i.e. days not months :) )

**Comment by mouradmourafiq** [comment]
Will be part of v0.5.1.

Closing the issue.
