### ISSUE TITLE
Set resource requests for build jobs

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#376]
### Feature motivation

Sometimes a build job gets scheduled on a node that has 1000m of its 1 CPU already booked (and in this case is completely out of credits because of #309) I notice this only when after 15 min a build is still not finished and I start to investigate the issue

### Feature description

If a build job pod would request at least 50m that would already prevent it from getting scheduled on node that is already booked out. For some users it may make sense to have this value configurable.

**Comment by mouradmourafiq** [comment]
You might need to take advantage of the [scheduling](https://docs.polyaxon.com/configuration/custom-node-scheduling/) the platform offers.

Builds are also a primitive that the platform exposes: `kind: build` where you can just build the code and use the environment section.

What's missing is the possibility to use/link to an image built in-cluster/by Polyaxon. This will offer the users the possibility to pre-bake a large build for instance using the `kind: build` primitive, and then link to that image in as many experiments/jobs as needed.

**Comment by Mofef** [comment]
I see. Doing the build separately and then using the resulting image afterwards would be a nice workaround. (And a useful feature anyway)
I'm aware of the scheduling features (and I use for example tainted gpu nodes and repective tolerations for experiments). But I don't see what you are suggesting... Btw, what I did in the meanwhile is just to `cordon` the respective node.

**Comment by mouradmourafiq** [comment]
This should be possible in the next release v0.4.2. No need to use the primitive to set the environment section for the build inside jobs and experiments.
