### ISSUE TITLE
Build status should be failed when pulling a image is failed.

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#378]
### Describe the bug
Since docker hub had an issue to push/pull image, so our polyaxon can't pull image from docker hub as the error log was below. But the build status was succeeded.

```
Building: Step 1/9 : FROM tensorflow/tensorflow:1.12.0-gpu
ERROR: error parsing HTTP 404 response body: invalid character 'p' after top-level value: "404 page not found\n"
```
https://status.docker.com/pages/history/533c6539221ae15e3f000031#

<img width="933" alt="screen shot 2019-02-22 at 2 22 24 pm" src="https://user-images.githubusercontent.com/1523515/53274855-b5de5600-36ad-11e9-91c2-1129bd6bbc25.png">

### To Reproduce
It might be quite hard to reproduce.

### Expected behavior
Build status should be failed, but succeeded.
<img width="426" alt="screen shot 2019-02-22 at 2 22 47 pm" src="https://user-images.githubusercontent.com/1523515/53274848-aeb74800-36ad-11e9-92ad-066d4c4e2853.png">

### Environment
- polyaxon: 0.3.9

**Comment by mouradmourafiq** [comment]
Some of these issues were solved in the v0.4.0, not sure if this one in particular was solved, but I am sure that some issues related to status transition were solved.

v0.4.0 is already out, I will be writing about it and announcing it.

**Comment by mouradmourafiq** [comment]
Closing this issue as no other incident has been noticed since the creation of this issue.

Please feel free to reopen in case this happens again.

**Comment by hollowgalaxy** [comment]
@mouradmourafiq  not sure if same issue but I'm having a build that is still running even though I can see in the logs (on kubectl that it failed)

specifically
Logs say:
```
  Normal   Created    10m                  kubelet, aks-agentpool-15009679-vmss000000  Created container polyaxon-init-dockerfile-56611e5960
  Normal   Started    10m                  kubelet, aks-agentpool-15009679-vmss000000  Started container polyaxon-init-dockerfile-56611e5960
  Warning  Failed     10m                  kubelet, aks-agentpool-15009679-vmss000000  Failed to pull image "test_image:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for test_image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Normal   Pulling    10m                  kubelet, aks-agentpool-15009679-vmss000000  Pulling image "polyaxon/polyaxon-sidecar:1.3.2"
  Normal   Started    10m                  kubelet, aks-agentpool-15009679-vmss000000  Started container polyaxon-sidecar
  Normal   Pulled     10m                  kubelet, aks-agentpool-15009679-vmss000000  Successfully pulled image "polyaxon/polyaxon-sidecar:1.3.2"
  Normal   Created    10m                  kubelet, aks-agentpool-15009679-vmss000000  Created container polyaxon-sidecar
  Normal   BackOff    9m59s (x2 over 10m)  kubelet, aks-agentpool-15009679-vmss000000  Back-off pulling image "test_image:latest"
  Normal   Pulling    9m47s (x2 over 10m)  kubelet, aks-agentpool-15009679-vmss000000  Pulling image "test_image:latest"
  Warning  Failed     9m46s (x2 over 10m)  kubelet, aks-agentpool-15009679-vmss000000  Error: ErrImagePull
  Warning  Failed     5s (x42 over 10m)    kubelet, aks-agentpool-15009679-vmss000000  Error: ImagePullBackOff

```
while on ui....

![image](https://user-images.githubusercontent.com/52365584/99312759-59bd4d00-2813-11eb-84da-6aef80490dcb.png)

**Comment by hollowgalaxy** [comment]
could be possible that I have malformed yml file see 
https://github.com/polyaxon/polyaxon/issues/1164#issuecomment-728349097
