### ISSUE TITLE
Command polyaxon project list does not show notebook

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#383]
### Describe the bug

I started a jupyter lab using `polyaxon notebook start -f file` and when I have notebook available I run the following:
```
polyaxon project list
```
The output does not show that the current project has a notebook:
```
Projects for current user
Navigation:
-----  -
count  3
-----  -
Projects:
  id  name               user    tags    is_public    has_code    created_at      updated_at      has_tensorboard    has_notebook
----  -----------------  ------  ------  -----------  ----------  --------------  --------------  -----------------  --------------
  38  demo-tb            vfn             True         False       48 minutes ago  48 minutes ago  False              False
```

Version: Polyaxon 0.4.0

**Comment by mouradmourafiq** [comment]
seems like the notebook creation did not succeed. A much better UI/UX similar to build jobs/jobs/experiments will be available for notebooks and tensorboards, to be able to debug what's happening.

**Comment by mouradmourafiq** [comment]
Notebooks/Tensorboards will have their own UI with statuses, these new UI pages will show you if an error happened during the creation of the service.

The change will be part of v0.4.3.
