### ISSUE TITLE
Readme editor's text input div in dashboard not filling the entire parent div.

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polyaxon#385]
### Describe the bug
The dashboard's Readme editor do not let you click to edit within the entire text box only the first line. I believe this worked as expected a couple of months ago but I could be wrong.

It seems to be the this div that does not fill the entire parent div.

```css
div.react-mde.react-mde-tabbed-layout div.mde-text div.DraftEditor-root div.DraftEditor-editorContainer div.notranslate.public-DraftEditor-content
```
### To Reproduce
Try to edit an experiment or project Readme text. 
### Expected behavior
One can click inside the entire text field to start entering text not only a small part of it.

### Environment
Polyaxon 0.4.0 with Firefox 66.0b10

**Comment by mouradmourafiq** [comment]
there was a style issue, should be fixed in v0.4.1.
