### ISSUE TITLE
HPTuning link in the specification reference is 404

### ISSUE THREAD

**Issue by mdaniel** [polyaxon/polyaxon#392]
### Missing Documentation

The `HPTuning` link for the specification is 404: https://docs.polyaxon.com/references/polyaxonfile-yaml-specification/hptuning/

However, [the file listing](https://github.com/polyaxon/polyaxon/tree/0.4.1/docs/references/polyaxonfile-yaml-specification) shows the file is actually erroneously named `hptunning.md`

**Comment by mouradmourafiq** [comment]
Thanks for letting me know, there's a typo in the file name.

**Comment by mouradmourafiq** [comment]
It should work now.
