### ISSUE TITLE
Got empty files when downloading experiment outputs from GCS

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#393]
### Describe the bug
We use google cloud storage for data, outputs and logs. When we tried to download the files on the web UI, we got the empty tar.gz file.

### To Reproduce
- Use GCS for outputs
- Download the outputs on the web UI in an experiment.

### Expected behavior
We expect the downloaded tar.gz file contains the outputs of experiment.

### Environment
- Polyaxon 0.4.1
- Google Cloud Storage

**Comment by mouradmourafiq** [comment]
Do you see anything on the web UI for the outputs?

**Comment by yu-iskw** [comment]
Yes, I do. The followings are the web UI which shows the outputs. Ant the data size of downloaded file is 4.1k. It means it is empty.

```
du -s --si yu.mercari-us-ml-weight-suggestion.experiments.3473.tar.gz
4.1k	yu.mercari-us-ml-weight-suggestion.experiments.3473.tar.gz
```

<img width="1194" alt="screen shot 2019-03-05 at 11 13 11 am" src="https://user-images.githubusercontent.com/1523515/53830666-d329e480-3f37-11e9-9256-88c22f46bcb9.png">

**Comment by mouradmourafiq** [comment]
ok then that's probably a bug, I was confused by your message from the other post about `polyaxon experiment copy` command.

**Comment by mouradmourafiq** [comment]
There was a bug, it should be fixed in the release v0.4.2.

**Comment by mouradmourafiq** [comment]
Next release will also allow to download individual files.
<img width="846" alt="Screenshot 2019-03-10 at 13 02 37" src="https://user-images.githubusercontent.com/1261626/54084747-e58b9000-4334-11e9-9053-2ea4f2a6ba84.png">

**Comment by yu-iskw** [comment]
I appreciate fixing it. I look forward to v0.4.2!
