### ISSUE TITLE
No pg_hba.conf entry for host

### ISSUE THREAD

**Issue by notsimon** [polyaxon/polyaxon#394]
I'm moving toward more persistence in my setup, as such I added an NFS PV with a claim for Postgresql. When deploying Polyaxon on the cluster, the sync-db jobs fail. The error coming from their logs follows:

```
django.db.utils.OperationalError: FATAL:  no pg_hba.conf entry for host "10.244.0.103", user "polyaxon", database "polyaxon", SSL off
```

Effectively, the pg_hba.conf (which ends up with the other postgresql files in my NFS folder) contains:

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                trust
#host    replication     postgres        127.0.0.1/32            trust
#host    replication     postgres        ::1/128                 trust
```

Any ideas on what might be happening ?

**Comment by notsimon** [comment]
Reinstalling Polyaxon and carefully removing everything in my NFS folder somehow "solved" this issue. It might be due to some state remaining from a previous setup that conflicted with this one... I'll test to remove/reinstall Polyaxon without deleting postgresql and reopen this issue if it doesn't work.

**Comment by mouradmourafiq** [comment]
Sorry for late reply, and thank for taking the time to debug it, please let me know what is the end result and if you managed to fix it.
