### ISSUE TITLE
Nginx resolvers are invalid with custom DNS domain.

### ISSUE THREAD

**Issue by log0ymxm** [polyaxon/polyaxon#395]
### Describe the bug

DNS domain isn't always `cluster.local`. I'm working on a cluster that used kubespray for k8s setup, and the [`cluster_name` is custom configured](https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml#L126). This has the consequence of changing the DNS domain, so [the hardcoded `resolver` lines in each nginx config](https://github.com/polyaxon/polyaxon/blob/master/web/nginx.conf#L41) don't work.

The address `kube-dns.kube-system.svc.cluster.local` does not resolve in our cluster, instead we have `kube-dns.kube-system.svc.custom.cluster.name`.

Why are these resolver declarations require for nginx, is there not lower level components that handle name resolution for nginx?

### To Reproduce

Create a cluster with a non-standard DNS domain, and install polyaxon-api (We're doing this using the helm chart).

Initial output of the pod logs `k logs polyaxon-polyaxon-api-858545fbfd-s2bvn -c polyaxon-api`:

```
Running...
mkdir: cannot create directory ‘/polyaxon/logs’: File exists
nginx: [emerg] host not found in resolver "kube-dns.kube-system.svc.cluster.local" in /etc/nginx/sites-enabled/polyaxon.conf:41
nginx: configuration file /etc/nginx/nginx.conf test failed
 * nginx is not running
 * Restarting nginx nginx
   ...fail!
 * nginx is not running
...
```

### Expected behavior

DNS resolution in the nginx config works regardless of custom DNS domain.

**Comment by mouradmourafiq** [comment]
Yes, there's an issue to support core dns #358, and probably make programatic nginx config, you might also hav a look at this issue #349 it could solve your problem temporarily.

**Comment by log0ymxm** [comment]
#358 is probably the end solution. Issue #349 is relevant, though we're already using kube-dns and have the name resolution issue, so I don't see any relevant temporary fix in that thread. We're looking at if we can attach a second dns record to the kube-dns configuration that allows us to have multiple valid domain names so we can still resolve the cluster.local record. I'm not sure what's possible yet. Thank you all the same.

**Comment by mouradmourafiq** [comment]
Will be providing an env var `POLYAXON_CUSTOM_CLUSTER_DNS` to define custom domains, default will be `cluster.local`, based on this [ref](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records).

**Comment by mouradmourafiq** [comment]
Closing this issue, a solution to handle different use cases will part of the following release v0.4.3,

**Comment by mouradmourafiq** [comment]
Just for reference, the [docs](https://github.com/polyaxon/polyaxon/blob/master/docs/configuration/cluster-dns.md) for next release.
