### ISSUE TITLE
Time series jupyter notebook

### ISSUE THREAD

**Issue by ichgaertnerin** [polyaxon/polyaxon#4]
Hello there,
when I want to execute the notebook on time series, I get the error 

KeyError Traceback (most recent call last)
<ipython-input-8-dfb14f762726> in <module>() ---> 16 predicted = [i['results'] for i in exp.estimator.predict(get_test_inputs(), hooks=[])]

The key 'results' does not seem to exist and I tried to solve this problem, but it did not work out.
Thanks for your help!

**Comment by mouradmourafiq** [comment]
Hi thanks for reporting the error, yes indeed there's a small issue with the code, the file [timeseries.py](https://github.com/polyaxon/polyaxon/blob/master/examples/timeseries.py) is training on `sin_cos` function and the the file [timeseries.ipynb](https://github.com/polyaxon/polyaxon/blob/master/examples/timeseries.ipynb) is predicting on `sin` function. I pushed code to master, the change will be part of the next release. Other examples might be broken also, hopefully all example will be stable starting from next release.
