### ISSUE TITLE
How to deploy polyaxon offline and no GPU？

### ISSUE THREAD

**Issue by leozhangj66** [polyaxon/polyaxon#40]
I want to deploy polyaxon in CPU，But there has always been amistake？The polyaxon requie the GPU，what should I do？

**Comment by mouradmourafiq** [comment]
@leozhangj66 Can you please give more details about your problem. Polyaxon can be deployed offline and it does not require GPU to run.

**Comment by leozhangj66** [comment]
I get the polyaxon-0.0.2.tgz from https://charts.polyaxon.com/polyaxon-0.0.2.tgz and use helm to deploy it in kubernetes.
```bash
helm install polyaxon-0.0.2.tgz --name=polyaxon --namespace=polyaxon -f config.yml
```
But I get a Error
```bash
Error: release polyaxon failed: DaemonSet.apps "polyaxon-polyaxon-resources" is invalid: [spec.template.spec.volumes[1].hostPath.path: Required value, spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.volumes[3].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[1].name: Not found: "nvidia-lib", spec.template.spec.containers[0].volumeMounts[2].name: Not found: "nvidia-bin", spec.template.spec.containers[0].volumeMounts[3].name: Not found: "nvidia-libcuda"]
```
And the imageTag is 0.0.2 in values.yaml which I see in https://hub.docker.com only hava one tags master

**Comment by allenzhang010** [comment]
I have the same issue, as I just want to setup polyaxon in CPU box. any update?

**Comment by mouradmourafiq** [comment]
I will look at the issue, maybe by mistake I made those volumes required.

**Comment by littlecarpenter** [comment]
> @leozhangj66 Can you please give more details about your problem. Polyaxon can be deployed offline and it does not require GPU to run.

HELM does not work if offline ? can you provide a guide for offline install?

MANY thanks
