### ISSUE TITLE
Validation of polyaxonfile of distributed training with tensorflow doesn't work in 0.4.2

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#404]
### Describe the bug
I was not able to pass a polyaxonfile of distributed training with tensorflow at polyaxon 0.4.2.

### To Reproduce
- https://github.com/yu-iskw/polyaxon-tf-distributed-training/tree/v0.4.2
```
$ polyaxon check -f polyaxonfile_distributed.yml

✗ Polyaxonfile is not valid.

Error message `{'environment': {'tensorflow': ['Unknown field.']}}`.
```

### Expected behavior
Distributed training should work.

### Environment
- Polyaxon 0.4.2

**Comment by yu-iskw** [comment]
Was the specification of polyaxonfile for distributed eventually changed recently?

**Comment by mouradmourafiq** [comment]
Hi the spec changed, we added `framework` which could be used for all experiment, it will be useful for search, generating micro service, metadata, ...
Some frameworks have special behaviour when the `replicas` subsection of `environment` is present.

So basically, you need to change `tensorflow` to `replicas` and add section `framework: tensorflow`

**Comment by yu-iskw** [comment]
I tottally understand the specification change. I will close the issue soon. Sorry for bothering you.
https://github.com/polyaxon/polyaxon-examples/tree/11910dfa2053d50bd3e7ae42ab957f393d9c5476/in_cluster/tensorflow/mnist
