### ISSUE TITLE
Mistake in Customize Run Environment Documentation

### ISSUE THREAD

**Issue by flackbash** [polyaxon/polyaxon#413]
In the code box of the [using gpus](https://docs.polyaxon.com/configuration/custom-run-environment/#using-gpus) paragraph, the _requests_ field in the environment section is falsly named _request_ in the gpu field. Similarly in the tpu field [here](https://docs.polyaxon.com/configuration/custom-run-environment/#using-tpus).

**Comment by mouradmourafiq** [comment]
Yes, that a typo, I pushed a fix to replace it in several places.
