### ISSUE TITLE
Upgrade rabbitmq dependency

### ISSUE THREAD

**Issue by patrungel** [polyaxon/polyaxon#416]
current version of polyaxon chart (0.4.2) depends on rabbitmq v0.6.15 which is quite outdated (it namely does not allow enabling metrics).

**Comment by mouradmourafiq** [comment]
As I am preparing the v0.4.3 release, I will try to update default version as well.

**Comment by mouradmourafiq** [comment]
Next release v0.5, Polyaxon will be using the the latest std helm chart, plus the possibility to disable the in-cluster one in favor of a managed or na external rabbitmq.
So closing this for now.
