### ISSUE TITLE
Dynamic change concurrency for experiment group

### ISSUE THREAD

**Issue by zewelor** [polyaxon/polyaxon#419]
### Unclear documentation

Is it possible to change concurrency for already running experiment group ? Like for example ability to downscale concurrency for few days and then change it up again etc ?

**Comment by mouradmourafiq** [comment]
It's possible, but there's no easy way to do it at the moment. I marked it as a feature request to expose an API and UI to be able to update the concurrency.

**Comment by zewelor** [comment]
Great, thanks for info !

**Comment by mouradmourafiq** [comment]
This is unfortunately not possible in the Open source atm. Concurrency, priority, and queues management are part of a larger system called agents, which is not currently open source.
