### ISSUE TITLE
Adapt TF_CONFIG: master to chief

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#42]

**Comment by sfujiwara** [comment]
I'm looking forward to release this feature!

I guess it's better that we can choose arbitrary task name in our yaml file.
In some cases, developer assume not `chief` but 'master', though `master` might be deprecated.
For example, we use `master` when running `tf.estimator.train_and_evaluate` without [DistributeStrategy](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute):
https://github.com/tensorflow/tensorflow/blob/783cdae78c3fdce1de859f974dfdcafdb38d4251/tensorflow/python/distribute/estimator_training.py#L160-L162

If we can use arbitrary task name, we can also use `evaluator` #67.

**Comment by mouradmourafiq** [comment]
This is implemented in v1. Closing the issue.
