### ISSUE TITLE
Add setup instructions for polyaxon on microk8s

### ISSUE THREAD

**Issue by sotte** [polyaxon/polyaxon#424]
The goal of this issue is to have a "from zero to polyaxon with microk8s" guide (and maybe adjust some install scripts/notes).

Here are the current installation instructions (WIP):
https://gist.github.com/sotte/e514c5322959f4bffee4b43037dea557

(This issue is a result of some discussions on slack. I put it here to have a more permanent place.)

TODOs:
- [x] basic outline
- [ ] figure out docker/contianerd problem
- [ ] walk through "getting started guide"
- [ ] verify install instructions
- [ ] write some prose
- [ ] create PR

**Comment by sotte** [comment]
Quick update: I have some reproducibility issues that I have to figure out first before finishing this guide

Note to self:
`polyaxon deploy -f config.yml`
Sometimes, not always, gives the following error:
`Error: release polyaxon failed: DaemonSet.apps "polyaxon-polyaxon-resources" is invalid: spec.template.spec.containers[0].securityContext.
privileged: Forbidden: disallowed by cluster policy
`

**Comment by sotte** [comment]
`fluentd` and `ingress` were necessary to avoid the error.

```
microk8s.enable \
  dashboard \
  dns \
  fluentd \
  gpu \
  ingress \
  metrics-server \
  prometheus \
  registry \
  storage
```

**Comment by valeriano-manassero** [comment]
> `fluentd` and `ingress` were necessary to avoid the error.

This is because enabling them adds `--allow-privileged=true` to kicrok8s installation.

You can get same results manually following this procedure:
https://gist.githubusercontent.com/antonfisher/d4cb83ff204b196058d79f513fd135a6/raw/a92d66bcede323ce7b9748d215f356b1fb45ceb9/allow-privileged-for-microk8s.md

**Comment by mouradmourafiq** [comment]
I think `--allow-priviliged=true` should be enabled in any case. @valeriano-manassero thanks for chiming in.

@sotte Can you make a PR with the current progress you have until now, you can create a file in this path: `polyaxon/polyaxon/docs/setup/microk8s.md`

I think we can refine the guide from there, and of course you can also make further PRs.

Thanks a lot @sotte.

**Comment by valeriano-manassero** [comment]
https://github.com/polyaxon/polyaxon/issues/457

**Comment by sotte** [comment]
@mouradmourafiq I'll create a PR later today. Still struggling with #202 though, but we can maybe discuss the details in the PR.
Also @valeriano-manassero feel free to chime in! :)

**Comment by mouradmourafiq** [comment]
@sotte I think we can recommend using `kaniko` as a build backend to circumvent that issue for now.

**Comment by valeriano-manassero** [comment]
@sotte try to put 
```
build:
  backend: kaniko
```
in your polyaxon file.
For some reason I need to explicitly set it because changing `defaultBackend` is not working for me.

**Comment by mouradmourafiq** [comment]
Closing this issue, the privileged mode is not necessary anymore starting from next release v0.5.1.
