### ISSUE TITLE
Build jobs status not updated

### ISSUE THREAD

**Issue by patrungel** [polyaxon/polyaxon#427]
### Describe the bug
After several days of uptime build jobs for experiments are perpetually reported to be "Scheduled" despite that corresponding kubernetes jobs have completed successfully.

This prevents the whole experiment from progressing further.
### To Reproduce

Run multiple (unrelated) experiments, observe the builds to remain in "Scheduled" state, cross-check with actual status of pods.

### Expected behavior
build job statuses are timely updated.
### Environment
k8s: 1.13.4
polyaxon:0.4.2

**Comment by mouradmourafiq** [comment]
Do you see this issue only in the 0.4.2 or was it also happening before in previous versions?

**Comment by patrungel** [comment]
Not 100% sure but it appears like a new thing in 0.4.2.

**Comment by patrungel** [comment]
Restarting 'polyaxon-polyaxon-monitors' seems to help temporarily: build jobs got statuses reflected properly.

**Comment by mouradmourafiq** [comment]
After restarting the monitor, does it show the same behaviour, i.e. not watching the statuses correctly. I should also assume that this is not only happening to builds, but to experiments as well?

**Comment by patrungel** [comment]
After restarting the monitor the status of builds is updated okay for some time (previous restart was made last Friday afternoon and experiments went smoothly until today morning, so it's some jobs during a weekend and a pretty much loaded Monday).
I can't tell if this only happening to builds or to experiments too since builds are quick tasks and seen stuck within minutes. On the contrary the stuck jobs might not be noticed for hours. Plus, when a build job is stuck (that is the symptoms are present), the actual jobs can't start altogether.

**Comment by mouradmourafiq** [comment]
Do you still see this issue after upgrading to the 0.4.4?

**Comment by patrungel** [comment]
With v.0.4.4 the issue is no longer reproduced for about a week, thanks so much!
