### ISSUE TITLE
Horovod Backend doesn't pass the environmental variables to workers.

### ISSUE THREAD

**Issue by joeyearsley** [polyaxon/polyaxon#429]
### Describe the bug
If you try and access environmental variables from a worker node in the distributed horovod backend then they aren't accessible since MPI hides env vars.

### To Reproduce
N/A

### Expected behavior
Workers can also access the same environmental variables as the master node.
### Fix
https://github.com/horovod/horovod/blob/f884cdab0f40e43172cf0a0beed6f2abfc8ea89c/horovod/run/run.py

Copy the env variables like horovod does.

**Comment by hollowgalaxy** [comment]
Doesn't that mean we can't access `polyaxon_client.tracking.get_data_paths()` in the workers because it requires [ensure_is_managed](https://github.com/polyaxon/polyaxon-client/blob/master/polyaxon_client/tracking/is_managed.py) function to work. Which is required for `get_data_paths()` which mentioned in all documentation (gcs, s3, azure) where you need to fetch data.

**Comment by hollowgalaxy** [comment]
I found out that the mpirun command created [here](https://github.com/polyaxon/polyaxon/blob/6aa3b5dee66e17592182335db73f65e4f0259386/platform/core/polyaxon/polypod/templates/pod_cmd.py) allows you to pass arguments to master as well as workers.
Something like this would work: `-x MY_ENV_VAR=my_value -x MY_ENV_VAR2=another_value python ...` 
This allows workers to receive the commands. 


Bonus: you can use `-x MY_ENV_VAR2={{ env_var2 }}` and have those values as input argument in the yml.

**Comment by mouradmourafiq** [comment]
We expose the full container spec in v1, I think that should not limit how you expose the container's env vars, or how you can construct the command and args. 

And similar answer to #453, we expose the full spec for MPI Operator, so you can have full control over the replicas as well.
