### ISSUE TITLE
Add a command for the admin to invalidate the registry cache

### ISSUE THREAD

**Issue by tpimentelms** [polyaxon/polyaxon#430]
### Feature motivation

Polyaxon uses a cache for it's build commands and there is currently no way to invalidate it without changing the commands in that environment explicitly. If the build references a `requirements.txt` file, a change in that file will not trigger an invalidation of the cache to be rebuilt.

### Feature description

A `renew_cache` flag in the build environment, similar to `nocache`, but which invalidates or removes the old cache. Or an admin command to invalidate the current cache.

**Comment by mouradmourafiq** [comment]
there will be a new cli command to invalidate cache for a build or all builds under a project. A button in the UI if it's merged might make it as well.

Closing this is as it will be possible to at least invalidate builds cache.
