### ISSUE TITLE
Restore deleted projects

### ISSUE THREAD

**Issue by joeyearsley** [polyaxon/polyaxon#431]
### Feature motivation

It is currently easy to accidentally delete projects, yet when you go to re-create one with the same name it fails. 
It would be good to allow the project to be brought back.

### Feature description

Not sure, presume DB is still populated with old projects.

**Comment by mouradmourafiq** [comment]
it actually takes time before the project gets completely deleted, files, logs, metrics, all need to be deleted. In the meantime the project will be available as it gets deleted in the `archives`.

You can also archive the Project, and let polyaxon delete it automatically at a defined interval, default 7 days.

**Comment by mouradmourafiq** [comment]
Maybe we should:

1.  add a status deletion in process to allow users to see that the deletion is happening.
2.  as suggested by another user, force user to enter the project name in the modal dialogue.

**Comment by joeyearsley** [comment]
Ah nice I found it! I like option 2!

**Comment by mouradmourafiq** [comment]
Option2 was implemented and was released, see #484.
