### ISSUE TITLE
Upgrade docker-registry helm chart version

### ISSUE THREAD

**Issue by rapatel0** [polyaxon/polyaxon#432]
Currently, we cannot point to a PVC to handle the docker-registry in polyaxon because the chart requirements point to a really old version of the docker-registry helm chart. 

I doubt that anything will change with a version update, it would be great if the version could be updated.

**Comment by mouradmourafiq** [comment]
Closing this, next release v0.5, Polyaxon will use the std latest stable helm chart for docker-registry. Will be testing in the meantime the stability of the deployments.
