### ISSUE TITLE
[UI] file view does not keep tabs

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#433]
### Describe the bug

Currently in "Output" tab, when viewing output files, e.g. python files the tabs/spaces inside the files are not rendered. For example, the following text 
```python
def foo():
    pass
```
will be displayed as 
```python
def foo():
pass
```

### Environment
Polyaxon : 0.4.4

**Comment by mouradmourafiq** [comment]
We will provide proper editors for all code extensions similar to the config/dockerfile editors.

**Comment by mouradmourafiq** [comment]
The outputs tabs has been improved significantly, and all files are now rendered properly using a code editor with language detection, images and other medias are using proper html tags.
