### ISSUE TITLE
Missing files in the output tab on Polyaxon Dashboard of past experiments after upgrading from 0.4.2 to 0.4.4 

### ISSUE THREAD

**Issue by lmontier** [polyaxon/polyaxon#434]
### Describe the bug
After upgrading Polyaxon from 0.4.2 to 0.4.4, I cannot see nor download the files in the output tab of the Polyaxon Dashboard of past experiments. However, the output tab is OK for experiments started after the upgrade of Polyaxon

### To Reproduce
1. Run an experiment with Polyaxon 0.4.2 and setup outputs so that you can output files in the output tab of the Polyaxon Dashboard
2. Upgrade Polyaxon from 0.4.2 to 0.4.4
3. Check the output tab of your experiment in the Polyaxon Dashboard

### Expected behavior
Access to the files in the output tabs of the experiments started before the upgrade of Polyaxon.

### Environment
Polyaxon is installed on Ubuntu 18.04 with MicroK8s.

**Comment by mouradmourafiq** [comment]
It should work, did you change something in your deployment config?

**Comment by lmontier** [comment]
Thanks a lot, I had a typo on the name of the persistent output in my deployment config. I fixed the typo then I deployed Polyaxon and now everything works: I can see again the output files in the Dashboard.

Thank you very much and sorry for posting a "bad" issue.

**Comment by mouradmourafiq** [comment]
No problem and glad it's working again as expected :)
