### ISSUE TITLE
When restarting an experiment from an experiment group it creates a new experiment not in the group

### ISSUE THREAD

**Issue by jamescook106** [polyaxon/polyaxon#444]
When restarting an experiment from an experiment group it creates a new experiment not in the group. I want it to start in the same experiment group

**Comment by mouradmourafiq** [comment]
This is a regression, or an unintentional bug, but definitely makes sense, should be resolved in the v0.5.

**Comment by mouradmourafiq** [comment]
Will be fixed in the next release v0.5. Closing the issue for now.
