### ISSUE TITLE
Installation hangs with RDS Postgres 9.6.1

### ISSUE THREAD

**Issue by edmeister** [polyaxon/polyaxon#449]
### Describe the bug

I'm trying to run polyaxon with a RDS Postgres instance. The `sync_db` job keeps retrying, but does not succeed.

```
$ kubectl logs -f polyaxon-sync-db-vclj9
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
Preparing...
```

The Postgres cluster is accessible from the K8S cluster. Security groups have been validated. The Postgres credentials are definitely correct.

When I change the configuration to the in-cluster Postgres, everything works as expected.

### To Reproduce

```
$ cat config.yaml
...
postgresql:
  enabled: false
  postgresUser: our-postgres-user
  postgresPassword: our-postgres-password
  postgresDatabase: polyaxon
  externalPostgresHost: polyaxon.*****.eu-west-1.rds.amazonaws.com
...
```

**Comment by edmeister** [comment]
Any advice how to increase the log level in those pods?

**Comment by mouradmourafiq** [comment]
You can use ‘logLevel: info’ to show more info.

Le lun. 6 mai 2019 à 03:54, Jeroen Schepens <notifications@github.com> a
écrit :

**Comment by edmeister** [comment]
I did try `logLevel: debug` yesterday, but that had no effect on the sync-db jobs.

**Comment by mouradmourafiq** [comment]
you need to check if you have to enable the internal dns to route connexions. Please check the [answer of this stackoverflow question](https://stackoverflow.com/questions/53571908/kubernetes-have-no-access-from-eks-pod-to-rds-postgres?answertab=votes#tab-top)
The minimum log level is `info`.

**Comment by edmeister** [comment]
We don't run EKS, so that's not applicable. The postgres URL resolves fine from withing the polyaxon-api pod:

```
root@polyaxon-polyaxon-api-8544778d74-z87ll:/polyaxon# nc -zv polyaxon.****.eu-west-1.rds.amazonaws.com 5432
DNS fwd/rev mismatch: polyaxon.****.eu-west-1.rds.amazonaws.com != ip-172-***-***-***.eu-west-1.compute.internal
polyaxon.****.eu-west-1.rds.amazonaws.com [172.***.***.***] 5432 (postgresql) open
```

Also: the logLevel unfortunately has no effect on the output in the sync-db Pod.

**Comment by mouradmourafiq** [comment]
actually that's weird, `polyaxon-sync-db` should not be preparing at all, it should just execute. What version are you running?

**Comment by edmeister** [comment]
I'm running the latest version (0.4.4).

**Comment by mouradmourafiq** [comment]
Please feel free to try with polyaxon v0.5.2 and reopen this issue if you have the same problem.
