### ISSUE TITLE
Additional config options for github SSO provider

### ISSUE THREAD

**Issue by gehring** [polyaxon/polyaxon#450]
### Feature description
It would be very helpful if the github provider could be configured beyond just the client id and secret.

Common configuration needs:
- Custom url for the github could be customized to support private/enterprise github websites.
- Authorize only specific github organizations or teams, e.g., by providing a whitelist.

**Comment by mouradmourafiq** [comment]
Closing this issue as wontfix. Advance auth mechanisms are not part of the open source.
