### ISSUE TITLE
Support ANSI escape codes in log viewer

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#451]
### Feature motivation

A lot of loggers or CLIs can make use of [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to add color the terminal output or support progressbars.

### Feature description

It would be great if the log viewer in the web UI would support this. Since many machine learning applications make extensive use of progressbars which otherwise don't show up correctly.

### Feature implementation

I used [`ansi-to-react`](https://github.com/nteract/nteract/tree/master/packages/ansi-to-react) in the past which is based on [`anser`](https://github.com/IonicaBizau/anser) and correctly handles colors and carriage returns (for progress bars) but there are many other ANSI libraries on `npm`.
This obviously adds more computation to the UI so performance might become a problem for huge logs. To reduce computation one can [safely pre-escape carriage returns](https://github.com/lgeiger/escape-carriage) returns on the backend which can be useful when dealing with long progress bars.

**Comment by mouradmourafiq** [comment]
This is a great package, and easy to use. There's an impact on the rendering performance but I think it's worth it. thank you @lgeiger.

**Comment by lgeiger** [comment]
👍 Thanks, looking forward to v1.1
