### ISSUE TITLE
Logs are not persisted if experiment fails

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#452]
### Describe the bug

If an experiment crashes (e.g. due to TensorFlow running out of GPU memory) the logs are not persisted. Both the UI and the CLI and cannot find the logs. I don't think this is a UI or CLI bug since the logs are also not visible on the NFS server. Logs can only be recovered by looking at the stack-driver logs on GKE.

### To Reproduce

I haven't found a simple way to reproduce this yet. For normal exceptions the logs are persistet.
After some quick testing it seams like this can be reproduced when an experiment rans out of RAM.

### Expected behavior

Logs from failed jobs are persisted

### Environment
GKE autoscaled preemptible GPU nodes
polyaxon version 0.4.4
log are stored using https://github.com/polyaxon/polyaxon-nfs-provisioner/

**Comment by lgeiger** [comment]
This might be related to TensorFlow logging massive amounts of data (~100 logs/ms) when it runs out of memory: https://github.com/tensorflow/tensorflow/issues/20998#issuecomment-407017935

Maybe polyaxon (or our setup) can't keep up with that much data.

**Comment by lgeiger** [comment]
Unfortunately massive logging of ten TensorFlow isn't the issue. Logs disappear (and jobs randomly crash) even with TensorFlow logging disabled.

**Comment by jorgemf** [comment]
Logs are not persisted in general. For me, if I launch an experiment I can see the logs without issues. If I reboot the computer (my cluster is only one computer) the logs disappear for all the experiments.

**Comment by mouradmourafiq** [comment]
@jorgemf I think you have the default config for the logs? if that's the case, your logs are hosted on `tmp` dir.

**Comment by jorgemf** [comment]
Thanks @mouradmourafiq

**Comment by lgeiger** [comment]
I am now able to reliably reproduce this issue. The issue appears when a node get's preempted or a pod/container get's evicted due to e.g. the node running out of memory.

**Comment by mouradmourafiq** [comment]
makes sense, Polyaxon has no way to recover the logs at this point, not sure what a proper solution for this particular use-case.

**Comment by lgeiger** [comment]
> Polyaxon has no way to recover the logs at this point, not sure what a proper solution for this particular use-case.

Wouldn't it be enough to handle the SIGTERM signals inside the docker container and store the logs then similar to how the workflow is when users are stopping an experiment from the Polyaxon UI?
For translating preemption events into proper pod terminations people can then use something like https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/

**Comment by mouradmourafiq** [comment]
Polyaxon implements a finalizer for collecting logs, please refer to this [comment](https://github.com/polyaxon/polyaxon/issues/470#issuecomment-596691888) for more details.
