### ISSUE TITLE
Horovod master node fails if worker nodes are not started before it

### ISSUE THREAD

**Issue by cheongwy** [polyaxon/polyaxon#453]
### Describe the bug
When starting an experiment using horovod as the framework, the experiment will fail when the worker nodes are not started in time before the master node tries to connect to them.

Following the examples in the polyaxon-examples repo here:

https://github.com/polyaxon/polyaxon-examples/tree/master/in_cluster/horovod/keras

I was initially unable to run it successfully consistently on my polyaxon cluster. Runs would mostly fail but would sometimes succeed. After taking a closer look at how polyaxon spawns up the horovod based experiment's master and worker nodes, it appears that the problem I faced is likely due to initial communication between the master and worker nodes. The experiment was able to run more consistently under the following situations:

1. Only a single master node was used. ie. commenting out the replicas section here:

https://github.com/polyaxon/polyaxon-examples/blob/master/in_cluster/horovod/keras/polyaxonfile-mnist.yml

2. Adding a "sleep x" before "mpirun.real" to this line in the Dockerfile:

https://github.com/polyaxon/polyaxon-examples/blob/master/in_cluster/horovod/keras/Dockerfile#L59

So that the call to mpi will not start even after the container for master has started. This ensures sufficient time for the workers to start. The experiment in this case may still fail if the sleep introduced is insufficient for the worker nodes to start. (especially when the image is big and not cached on the node yet)

When running the example w/o the above modifications, the following errors were encountered very frequently:

> ORTE was unable to reliably start one or more daemons.
> 
> This usually is caused by:
> 
> * not finding the required libraries and/or binaries on
> 
> one or more nodes. Please check your PATH and LD_LIBRARY_PATH
> 
> settings, or configure OMPI with --enable-orterun-prefix-by-default
> 
> * lack of authority to execute on one or more specified nodes.
> 
> Please verify your allocation and authorities.
> 
> * the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
> 
> Please check with your sys admin to determine the correct location to use.
> 
> * compilation of the orted with dynamic libraries when static are required
> 
> (e.g., on Cray). Please check your configure cmd line and consider using
> 
> one of the contrib/platform definitions for your system type.
> 
> * an inability to create a connection back to mpirun due to a
> 
> lack of common network interfaces and/or no route found between
> 
> them. Please check network connectivity (including firewalls
> 
> and network routing requirements).
> 

### To Reproduce

The easiest way to reproduce the above behaviour is possibly on a new cluster where the image used for the experiment have not been cached on the nodes yet. Using a image with large size (eg. > 10GB) will also likely help in surfacing the issue.

### Expected behavior

Master nodes should wait for worker nodes before starting actual experiment run. A timeout can possibly be set to eventually fail the experiment if some workers are still not started thereafter.

### Environment

Polyaxon v 0.4.2 on Kubernetes v 1.12.7

**Comment by mouradmourafiq** [comment]
Thanks for the detailed issues, I am aware of this. A timeout is probably the easiest way to solve this issue, a better solution would be to have a initial check phase.

**Comment by mouradmourafiq** [comment]
Polyaxon has much better integration with the MPI Operator, and exposes all its interfaces natively in v1. 
Horovod will be available only through the Operators, I think Pytorch/TF Operators have an implementation as well, but in any case they are all natively supported now.
