### ISSUE TITLE
Private git repo is not working

### ISSUE THREAD

**Issue by edmeister** [polyaxon/polyaxon#456]
### Describe the bug
We don't succeed in entering a private git repository (Bitbucket server). The UI always reports an error. We notice through the access logs of our bitbucket server that polyaxon does not send a request. When we select `Public`, requests do come in (but obviously fail).

### Environment
Polyaxon 0.4.4 on K8S 1.10.x

**Comment by mouradmourafiq** [comment]
Can you please try with v0.5.2 and report back. It's easier to try on the new version, you can use a UI for it.
Please feel free to reopen.
