### ISSUE TITLE
Tensorboard trace viewer can't load page

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#458]
### Describe the bug

TensorFlow 2.0 and 1.14 nightly introduced the ability to view a trace inside TensorBoard: https://www.tensorflow.org/tensorboard/r2/tensorboard_profiling_keras#trace_viewer

Unfortunately Polyaxon can't load the page inside TensorBoard and fails with:
`https://polyaxon.mydomain.com/trace_viewer_index.html?trace_data_url=%2Fdata%2Fplugin%2Fprofile%2Fdata%3Fhost%3Dlocal.%26run%3D2019-05-18_12-39-54%26tag%3Dtrace_viewer&is_streaming=false Failed to load resource: the server responded with a status of 404 ()`

It seams to try to load the asset from `https://polyaxon.mydomain.com/` instead of from `https://polyaxon.mydomain.com/tensorboard/user/project/id/3882/`.
### To Reproduce
- Train a `tf.keras` model with the TensorBoard callback using TensorFlow 2.0 or 1.14 nightly.
- Start TensorBoard and try to access the Profile Tab:
![polyaxon mydomain com_tensorboard_lgeiger_bi-real-net_experiments_3882_](https://user-images.githubusercontent.com/13285808/57970744-f08a1e80-797c-11e9-8fa0-17e419a26129.png)

### Expected behavior
Profile viewer loads correctly.

### Environment
Poylaxon 0.4.4
GKE with ingress and https://github.com/polyaxon/polyaxon-chart/pull/42
Note that this might be similar to #422

**Comment by mouradmourafiq** [comment]
Thanks for the detailed bug report.

**Comment by mouradmourafiq** [comment]
I will be investigating this issues and #422 to include a fix next release.

**Comment by mouradmourafiq** [comment]
@lgeiger  Can you provide a minimal tf2 code example that breaks?

**Comment by lgeiger** [comment]
> @lgeiger Can you provide a minimal tf2 code example that breaks?

I can provide one tomorrow. Have you tried https://www.tensorflow.org/tensorboard/r2/tensorboard_profiling_keras#trace_viewer with Tensorflow 2.0 nightly

**Comment by mouradmourafiq** [comment]
How did you create a docker image for the nightly version, seems like tf does not find GPUs, and some issues are saying that it requires cuda10.

**Comment by lgeiger** [comment]
I built my own docker image based on CUDA 10 and Python 3.7, but you can try `tensorflow/tensorflow:nightly-gpu-py3` or the CPU version.

**Comment by mouradmourafiq** [comment]
Thanks, could not find the `tensorflow/tensorflow:nightly-gpu-py3` easily, so I thought it was not there.

**Comment by lgeiger** [comment]
Here is a simple code example using `tensorflow/tensorflow:nightly-gpu-py3` for experiments and tensorboard jobs:
```python
import tensorflow as tf
import tensorflow_datasets as tfds

mnist_train = tfds.load(name="mnist", split=tfds.Split.TRAIN, as_supervised=True)


def scale(image, label):
    image = tf.cast(image, tf.float32)
    image /= 255
    return image, label


train_dataset = mnist_train.shuffle(1000).batch(256)

model = tf.keras.Sequential(
    [
        tf.keras.layers.Conv2D(32, 3, activation="relu", input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=tf.keras.optimizers.Adam(),
    metrics=["accuracy"],
)

model.fit(
    train_dataset,
    epochs=10,
    callbacks=[tf.keras.callbacks.TensorBoard(log_dir="./mnist")],
)
```

**Comment by mouradmourafiq** [comment]
So after some investigation, it seems that the trace_viewer plugin does not work correctly behind reverse proxies, an [issue](https://github.com/tensorflow/tensorboard/issues/2263) was submitted.

**Comment by lgeiger** [comment]
Thanks for investigating

**Comment by mouradmourafiq** [comment]
There is already a PR to fix the issue, the problem was very simple to solve. So I guess as soon as they distribute a new version, you should not see any problem with loading the trace viewer.

The next Polyaxon's release has also some enhancement, to avoid at least some complicated edge cases, e.g. the jupyterlab case for instance.

Closing this issue, a [PR](https://github.com/tensorflow/tensorboard/pull/2276) is under review.

**Comment by lgeiger** [comment]
Thanks for investigating! Saw the PR 👍
