### ISSUE TITLE
Experiment restart --copy creates additional folder

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#461]
### Describe the bug

Using `experiment restart --copy` creates an additional output folder in the new experiment with the id of the restarted experiment, instead of copying just the content. Is this intended behaviour?

### To Reproduce
- `polyaxon experiment -xp 23 restart --copy`
- Output of experiment 24 includes directoy named `23` with the output of the restarted experiment

### Expected behavior
- `polyaxon experiment -xp 23 restart --copy`
- Output of experiment 24 includes a copy of the output of experiment 23 without an additional folder

### Environment
Polyaxon v0.4.4
Outputs on NFS with https://github.com/polyaxon/polyaxon-nfs-provisioner/

**Comment by mouradmourafiq** [comment]
Closing this as well as it's fixed for v0.5.
