### ISSUE TITLE
Default tensorboard pods don't include resource requests

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#462]
### Describe the bug
When starting TensorBoards with the default image defined in the deployment helm chart, polyaxon doesn't assign resource requests (and limits) to the pod. This means cluster providers won't scale up node pools when many tensorboards are opened since (at least in GKE) autoscalers only look at resource requests to determine weather to scale up.

### To Reproduce
- `polyaxon tensorboard start`
- Look at the deployed pod spec

### Expected behavior
Polyaxon should define sane defaults for the TensorBoard pods since they need a lot of memory (rarely below 300M) or allow users to specify this in the polyaxon helm chart.

### Environment
- Polyaxon 0.4.4
- GKE

**Comment by mouradmourafiq** [comment]
Since the project is going to expose dynamic configs, a new option settings will be available to configure default resources for: xps, jobs, builds, notebooks, tensorboads.

Closing this issue, it will be part of v0.5.

**Comment by lgeiger** [comment]
That's cool, though I think good defaults for the resources would be really handy for inexperienced users as well.
