### ISSUE TITLE
COPY command in Dockerfile failed with massage 'no source files were specified'

### ISSUE THREAD

**Issue by lmishii** [polyaxon/polyaxon#463]
### Describe the bug
COPY command in Dockerfile failed with message 'no source files were specified'

### To Reproduce
```
polyaxon project create --name=test --description='test'
polyaxon project -p test git --url="<Github repository URL>"
mkdir test; cd test
polyaxon init test --polyaxonfile
```

polyaxonfile.yaml is as follows.
```
---
version: 1

kind: experiment

build:
  dockerfile: docker/Dockerfile
  commit: xxxx

run:
  cmd: echo "Hello"
```

when I execute `polyaxon run` build failed with following message.
```
Building: Step 22/40 : COPY xxx/*requirements.txt /tmp/requirements/
Building:
ERROR: COPY failed: no source files were specified
Traceback (most recent call last):
File "dockerizer/build_cmd.py", line 37, in <module>
nocache=nocache)
File "/polyaxon/polyaxon/dockerizer/dockerizer/builders/native.py", line 160, in build
raise BuildException('The docker image could not be built.')
builders.exceptions.BuildException: The docker image could not be built.
```

directory structure
```
<Git repository root directory>
  docker
    + Dockerfile
  xxx
    + cpu.requirements.txt
```

When I execute 
```
cd <Git repository root directory>
docker build -f docker/Dockerfile .
```
I can build docker image successfully.

### Expected behavior
can build successfully in `polyaxon run` command

### Environment
kubernetes 1.13
polyaxon 0.4.4 (helm install)

**Comment by ifokeev** [comment]
looks like you should run ```polyaxon upload``` before the run

**Comment by mouradmourafiq** [comment]
I think the issue is that you did not reference the correct location of where Polyaxon provides the code context. The code is copied in `/code` so you need to have the correct path in your COPY command.

If you still have the same error, please feel free to reopen.
