### ISSUE TITLE
Sort files in outputs

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#464]
### Feature motivation

Currently the files are not sorted in the outputs tab. When an experiment create a lot of files it is hard to find the file you are interested in. It will be easier if the files were sorted. 

### Feature description

The files could be sorted by name or maybe by the last time they were updated (recently updated on top). I prefer the sorting by last time updated but any type of sorting which makes sense will work.

**Comment by mouradmourafiq** [comment]
just published a new version of polystores with sorting for keys and dirs alphabetically. Further enhancement will be done at later stage, probably giving the user the possibility to change the sorting.

**Comment by mouradmourafiq** [comment]
closing the issue, a default sort will by name will be part of next release v0.5.
