### ISSUE TITLE
Logout from a notebook keeps the notebook running but not in polyaxon

### ISSUE THREAD

**Issue by jorgemf** [polyaxon/polyaxon#467]
### Describe the bug

Logout from a notebook keeps the notebook running but not in polyaxon

### To Reproduce

1. Launch a notebook
2. Logout from the notebook (with the botton in the notebook)

The notebook keeps running, probably because kubernetes restarted it, but polyaxon doesn't show it. (you can see it with kubectl)

### Expected behavior

Notebook shouldn't be restarted

### Environment

Polyaxon 0.4.4
Kubernetes 1.14.1

**Comment by gmrukwa** [comment]
The same here, also with `Quit` button. I tried already removing the pod, but it keeps respawning.

**Comment by mouradmourafiq** [comment]
`Logout` or `Quit` does not stop the server, you can stop the notebook similar to other services using Polyaxon API/CLI/UI.
