### ISSUE TITLE
Docker registry memory leak

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#468]
### Describe the bug
The memory usage of the polyaxon docker registry increases until the node runs out of memory and the pod gets evicted. Even if the cluster isn't used the memory usage doesn't decrease.

### To Reproduce
Normal usage with large NVIDIA CUDA or TensorFlow images. Observe memory usage of docker registry increase until pod gets evicted:
<img width="347" alt="Bildschirmfoto 2019-05-29 um 00 53 20" src="https://user-images.githubusercontent.com/13285808/58519678-89564080-81ac-11e9-9262-6eb80b01133f.png">

I am not sure if this is a know bug that is already fixed by #432 and #441. Will Polyaxon 0.5 support external docker registries, so this issue can be worked around?

### Expected behavior
Memory usage stays at a reasonable size and decreases when cluster is not in use

### Environment
Polyaxon 0.4.4
GKE

**Comment by mouradmourafiq** [comment]
Next release the chart will be using latest stable registry chart, also it will support using an external registry: GCR, Private docker hub, ECR, ...

**Comment by lgeiger** [comment]
I am not sure anymore if this is a memory leak or the inmemory cache just filling up. Since 0.5 now uses the upstream chart, resource limits can be set to prevent the registry from eating up all the available memory on a node.
