### ISSUE TITLE
Unable to login to Polyaxon dashboard

### ISSUE THREAD

**Issue by abimur-123** [polyaxon/polyaxon#479]
### Describe the bug
Unable to login to the dashboard 
Possible reason: Rabbit MQ deployment fails because it cannot find the image

### To Reproduce
Ran the steps in this link https://docs.polyaxon.com/setup/kubernetes/

### Expected behavior
Login to dashboard as super user

### Environment
Helm version
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

### Images showing failure event 
![image](https://user-images.githubusercontent.com/14052278/59722790-989c3d00-91f2-11e9-925c-a654621b0f2c.png)

![image](https://user-images.githubusercontent.com/14052278/59722695-51ae4780-91f2-11e9-87d6-69094777d062.png)

![image](https://user-images.githubusercontent.com/14052278/59722726-6b4f8f00-91f2-11e9-9052-c4cf912be56b.png)

**Comment by mouradmourafiq** [comment]
Did you manage to solve your issue? if not can you please share a bit more info about your setup.

**Comment by abimur-123** [comment]
I haven't been able to solve this yet

Info about my setup - 
config.yml file 
```
rbac:
  enabled: false
ingress:
  enabled: false
serviceType: LoadBalancer
```

I am using kubernetes hosted on the Azure cloud

Apart from this, I just followed the instructions to deploy to kubernetes on this page - https://docs.polyaxon.com/setup/kubernetes/

**Comment by mouradmourafiq** [comment]
I would suggest to enable rbac on your azure cluster and set the `rbac` to `enabled` and try again. It's a bit weird that it cannot resolve the rabbitmq container.

Did you check that the container is running correctly, also any more info about the nodes resources would be useful.

**Comment by mouradmourafiq** [comment]
closing this issue, next release v0.5 coming this week will allow to switch broker backend from rabbitmq to redis, this could be useful for small clusters.
