### ISSUE TITLE
Make project deletion harder

### ISSUE THREAD

**Issue by maltebaumann** [polyaxon/polyaxon#484]
### Feature motivation

Right now, it's way too easy to accidentally delete an entire project. The UX flow is exactly the same for experiments, tensorboards and projects, one just needs to hit the […] at the top instead of the one for a single experiment. And, after clicking away the "Do you really want to…" dialog, that always appears, months of work are immediately deleted without a way to go back.

### Feature description

I'd suggest to introduce an additional barrier, e.g. "Please enter the name of the project you're about to delete."

**Comment by mouradmourafiq** [comment]
Project deletion will require entering the project name starting from v0.5.3.

Please also consider archiving, the default archiving period is 7 days, any entity that has been archived for more than the archive period will be deleted automatically, this way you have always a way to recover entities. The archiving period is configurable.

Closing the issue for now.
