### ISSUE TITLE
Debug mode to troubleshoot experiments/jobs in K8S cluster.

### ISSUE THREAD

**Issue by DXist** [polyaxon/polyaxon#488]
### Feature motivation

It's often useful to troubleshoot experiments running in containers. Ability to interact with container environment is handy feature.

### Feature description

User can run experiment/job/build job in debug mode. Instead of configured command experiment or job will run 'sleep inf'. Then it will be possible to interact with the running container.

Minimal implementation could just show a 'kubectl exec' command to run interactive shell in the container.

Convenient workflow might be a single command that runs the sleep container and execs a shell when it's ready. There will be an issue with kubectl context support if 'kubectl exec' is used directly because in general case current kubectl context may point to another k8s cluster. This can be mitigated by configurable kube-context to use.

For extra convenience the experiment may be stopped after interactive shell exit.

**Comment by polyaxon-team** [comment]
fixed in #1367
