### ISSUE TITLE
Not all experiments are shown in online dashboard

### ISSUE THREAD

**Issue by hagax8** [polyaxon/polyaxon#490]
### Describe the bug
Experiments are not all shown in the polyaxon dashboard. It seems to be a bug with the "Next" button in the view displaying the experiments table.

### To Reproduce
I ran a group of 192 experiments. The online dashboard only shows 6 pages of 20 experiments (so, 120 experiments, missing 72) and then the "Next" button greys out. On the other hand, I can access all experiments from the command line without any problem (9 pages of 20 and 1 page of 12).

### Expected behavior
Have all experiments displayed in the dashboard.

### Environment
polyaxon 0.4.4

**Comment by mouradmourafiq** [comment]
I think this is fixed in later versions of Polyaxon, definitely fixed in v1. 
0.4.4 is very old.
