### ISSUE TITLE
Security Issue in Jupyter Notebooks

### ISSUE THREAD

**Issue by waltsims** [polyaxon/polyaxon#491]
### Describe the bug

When running a Jupyter notebook users can open a terminal with root access to datasets and output folders of all users.

### To Reproduce
create jupyter notebook (in UI or CLI)
create new terminal (top right: new --> terminal)
```
$ cd /data/{everything}/
$ touch test
$ rm test
```

### Expected behavior
Users should not have access to `/data` or `/output` but rather only `/data/{selected-dataset}/` `/output/{user}/.  In this case the `{selected-dataset}` could be a required param in the polyaxon file for example.

### Environment
- polyaxon v0.4.3
- build:
```
image: pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime
  buid_steps:
     - pip install jupyter
```

**Comment by mouradmourafiq** [comment]
Yes, you are right, it should normally only mount a subpath for that specific project.

**Comment by mouradmourafiq** [comment]
I think this is not the case anymore:
 * Users can opt to use the auto-artifacts management to load outputs from other runs without mounting the volume to the user container.
 * For the commercial version there's a full isolation mechanism:
   * Polyaxon won't allow running a job if the user or project does not have access to a specific artifact, so the security is up-to the project admins to authorize specific artifacts/paths.
   * Read-only users can be authorize to view a read-only version of notebooks using voila or a custom dashboard.
