### ISSUE TITLE
[Polyaxon 0.5] Add end-to-end example about using GCR

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#493]
### Unclear documentation

Polyaxon 0.5 now provides support for externally managed docker registries. This is great 👍

I tried to follow https://docs.polyaxon.com/integrations/gcr/ to setup GCR, but I cannot get the properly authenticate the docker build to have access to the registry.
It would be great to have an end-to-end example on how to set this up with GCR and proper authentication. All combinations I tried so far result in the build failing with:
```
Building: Successfully tagged eu.gcr.io/my-project/polyaxon/polyaxon-05_49:103e3622f3114f9b8cde0bd186c98f8d
Traceback (most recent call last):
File "dockerizer/build_cmd.py", line 40, in <module>
registries=settings.PRIVATE_REGISTRIES)
File "/usr/local/lib/python3.6/site-packages/polyaxon_dockerizer/builder.py", line 240, in build_and_push
push(docker_builder, max_retries=max_retries, sleep_interval=sleep_interval)
File "/usr/local/lib/python3.6/site-packages/polyaxon_dockerizer/builder.py", line 208, in push
raise BuildException('The docker image could not be pushed.')
polyaxon_dockerizer.exceptions.BuildException: The docker image could not be pushed.
ERROR: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```
It seams like the secret (which has `storage.admin` rights) isn't recognised properly by the build job. I am happy to send a PR to improve the docs, once I can get this to work in our cluster.

**Comment by mouradmourafiq** [comment]
Can you also try with Kaniko.

By way, the dockerizer is completely independent: https://github.com/polyaxon/polyaxon-dockerizer, and can be tested separately.

I remember that I tried on different clouds, but may be I was also attaching different secrets. 

Can you check this: https://github.com/docker/compose/issues/6374#issuecomment-442431578

**Comment by lgeiger** [comment]
Both switching to Kaniko or to `gcr.io` still fails.

I think for me the problem is, how to properly add `k8s_secrets` via the UI since the `privateRegistries` field isn't available in the Helm chart anymore:
```
$ polyaxon admin upgrade -f configs/polyaxon-config.yaml --check
Polyaxon deployment file is not valid 
Error message `{'privateRegistries': ['Unknown field.']}`.
```

**Comment by mouradmourafiq** [comment]
I think for now a service account secret is the way to go, the other solution needs another secret that I thought was merged in the CE, but it was not.

**Comment by lgeiger** [comment]
Great, I'll try it on Monday and will report back.

**Comment by mouradmourafiq** [comment]
well I followed the steps on a newly created cluster, and it works both using the native and kaniko.

**Comment by lgeiger** [comment]
Thanks for the tutorial. I also tried it with kaniko, but needed to upgrade the default kaniko docker image from `v0.7.0` to `v0.10.0` to make it work.

**Comment by mouradmourafiq** [comment]
I wanted to check as well to update the default image, but forgot, for me kaniko worked with 0.7, it shows some logs at the first because it tries the internal cred helper, but it works afterwards.

**Comment by mouradmourafiq** [comment]
v0.9.0 seems to be stable and fast compared to v0.7.0, I had some issues with v0.10.0, it does not fall back to anonymous builds.

**Comment by Mofef** [comment]
Hey there, 

I was following https://docs.polyaxon.com/integrations/gcr/ and also had this error
```
ERROR: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

But, thanks to this thread I tried `backend: kaniko` inside the polyaxonfile and that made it work.

So I went back to the settings page and set gcr as default registry. Since then I couldn't make it work again :/ Is there a way to undo this?

The error I get now with kaniko:
```
2019-10-02 15:11:27 UTC -- [36mINFO[0m[0000] Downloading base image eu.gcr.io/muenst-test/mag-ros-melodic

2019-10-02 15:11:27 UTC -- error building image: getting stage builder for stage 0: no token in bearer response:

2019-10-02 15:11:27 UTC -- {"errors":[{"code":"UNAUTHORIZED","message":"Not Authorized."}]}
```

**Comment by mouradmourafiq** [comment]
You mean not using GCR as default? just delete the entry and it will fall back to the normal behaviour.

**Comment by Mofef** [comment]
Cool that worked! So I removed the entry and recreated it. not setting it default this time. Now I can access the private GCR without problems (only with kaniko backend). Any idea why setting it as default breaks it though?
