### ISSUE TITLE
[Polyaxon 0.5] Unable to start TensorBoards for a project via the UI

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#494]
### Describe the bug

Starting a TensorBoard for a project from the UI via the `New` button doesn't work. 
If the TensorBoard is started from the CLI for the same project via `polyaxon tensorboard -p <project name> start` everything works as expected. Starting TensorBoards for a single experiment works from both the UI and the CLI.

### To Reproduce
- Go to a Polyaxon project
- Click on the `New` button and select `Start tensorboard`
- Polyaxon redirects to the following page and doesn't allow to create a TensorBoard:
  ![Bildschirmfoto 2019-07-08 um 15 40 05](https://user-images.githubusercontent.com/13285808/60819980-70bc4b80-a198-11e9-80fb-ef23443ad931.png)

### Expected behaviour

Polyaxon should redirect to
![Bildschirmfoto 2019-07-08 um 15 56 30](https://user-images.githubusercontent.com/13285808/60820249-fb04af80-a198-11e9-9361-8c79156a95fb.png)

### Environment

Polyaxon 0.5.0

**Comment by mouradmourafiq** [comment]
Good catch, bad order of routes, fixed.

**Comment by lgeiger** [comment]
Awesome thanks for the fast fix.
