### ISSUE TITLE
PolyaxonClientException: Please provide a valid project.

### ISSUE THREAD

**Issue by danchyy** [polyaxon/polyaxon#498]
### Describe the bug

When running the experiment I recieve the following stack trace:

```
Traceback (most recent call last):
File "train.py", line 139, in <module>
experiment = Experiment()
File "/usr/local/lib/python3.7/dist-packages/polyaxon_client/tracking/no_op.py", line 27, in wrapper
return f(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/polyaxon_client/tracking/experiment.py", line 52, in __init__
outputs_store=outputs_store)
File "/usr/local/lib/python3.7/dist-packages/polyaxon_client/tracking/no_op.py", line 27, in wrapper
return f(*args, **kwargs)
File "/usr/local/lib/python3.7/dist-packages/polyaxon_client/tracking/base.py", line 36, in __init__
raise PolyaxonClientException('Please provide a valid project.')
polyaxon_client.exceptions.PolyaxonClientException: Please provide a valid project.
```

### To Reproduce
I really don't know how to reproduce it, some projects work well, some give previous stack trace. 

### Environment
Servers run on Ubuntu 18.04.02 LTS, local environment is Mac OS Mojave 10.14.5.

**Comment by grgurkovac** [comment]
I managed to reproduce this error using the following files. 
yml file:
```
version: 1
kind: experiment
environment:
  resources:
    cpu:
      limits: 100
      requests: 3
    gpu:
      limits: 1
      requests: 1
    memory:
      limits: 4000
      requests: 100

build:
  image: 'pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-devel'

  build_steps:
    - python3 -m pip install -U --no-cache-dir polyaxon_client

run:
  cmd: python3 main.py
```
main.py:
```
from polyaxon_client.tracking import Experiment
experiment = Experiment()
```

The error seems to be caused by the flag IN_CLUSTER being false because after inserting the project name in the Experiment construction the following error happens:
`polyaxon_client.exceptions.PolyaxonClientException: Api config requires at least a host if not running in-cluster.`

`polyaxon cluster` return the correct cluster info.

**Comment by mouradmourafiq** [comment]
If you are running polyaxon v0.4.4, I would suggest to pin the version in the pip install `polyaxon_client ==0.4.4`

**Comment by grgurkovac** [comment]
Yes, that solves the problem. 
Thank you very much.
