### ISSUE TITLE
Specify slack channel to send notifications in polyaxon YAML specification

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#499]
### Feature motivation
I like the slack notification when statuses of builds/experiments/jobs are changed. But, sharing all notification in a single slack channel make a mess. It would be great to customize the slack channel to which we want to send notifications.

### Feature description
The polyaxon specification offers a feature to identify a slack channel.

### Feature implementation
```
---
version: 1
...
    notification:
        - url: ${WEBHOOK_SECRET}
        - channel: project-universal-truth
```

**Comment by mouradmourafiq** [comment]
this is actually planned, especially for Polyflow.

**Comment by yu-iskw** [comment]
Cool! 

BTW, is polyflow available in polyaxon 0.5.x CE?

**Comment by yu-iskw** [comment]
I read the article on Medium. I understand we can use polyflow even on 0.5 CE. Thank you for the hard work as always. If there is anything I can help you, please let me know.

https://medium.com/polyaxon/polyaxon-v0-5-released-a275a322088b

**Comment by mouradmourafiq** [comment]
Polyflow is still not generally available, it's still needs a couple of iterations, and requires an extra cluster to not mess with a Polyaxon prod cluster.

After fixing any issue/regression in v0.5, we will make it opt-in and then generally available when it's stable. I will ping you once you you migrate and you are comfortable with the new version.

N.B. the reason we are doing this is to keep get v0.5 to stable very fast and gather as many feedback on Polyflow as possible.

**Comment by shotarok** [comment]
@yu-iskw and I upgraded our cluster to v0.5.2. We don't face a big issue so far. We're ready to use Polyflow. If it's generally available, please ping us. Thanks.

**Comment by yu-iskw** [comment]
@mouradmourafiq We are ready to use polyflow. We are glad to become the first penguin. Please let us know, when you are ready.
