### ISSUE TITLE
Add support for layer caching with external docker registries

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#505]
### Feature motivation

When using an external docker registry such as Google Container Registry, only the final built image is uploaded and the intermediate layers are not cached in the registry.
One of the big selling points of Polyaxon is fast experimentation, which means people are making small code changes and constantly triggering new builds. This results in an entirely new docker image being uploaded to GCR every time a build is triggered. This is quite inefficient and can lead to an unnecessary high storage cost over time.

### Feature description

It would be great to support layer caching on a registry level similar to how the internal registry handles storage.

### Feature implementation

For the Kaniko backend this could be implemented fairly straight forward by adding support for the [`--cache`](https://github.com/GoogleContainerTools/kaniko#--cache) build argument or support for passing arbitrary arguments to the `build` command (see also https://cloud.google.com/cloud-build/docs/kaniko-cache).
I am not sure how this could be handled by the native docker backend or if this would need changes on the registry level.

**Comment by lgeiger** [comment]
> This results in an entirely new docker image being uploaded to GCR every time a build is triggered. This is quite inefficient and can lead to an unnecessary high storage cost over time.

I am not 100% sure about this anymore. I have to check what GCR actually stores behind the scenes.

**Comment by lgeiger** [comment]
Actually GCR properly stores only the layers, which means this feature is more a nice to have than a necessities.

Feel free to close it, if it doesn't fit into the roadmap.

**Comment by Mofef** [comment]
I'm not sure if this is the same issue, but since we switched to a private base image that is hosted on gcr and use kaniko as a build backend I also experienced that every `polyaxon run` with a preceding `polyaxon upload` triggers a new build from scratch. Symptom wise thats exactly what @lgeiger describes in the OP.

**Comment by mouradmourafiq** [comment]
* Builds are not required
 * A default Kaniko component, has a [cache flag](https://github.com/polyaxon/polyaxon-hub/blob/master/kaniko/latest.yaml#L12). For advanced use case the user can define their own component to define more parameters.
