### ISSUE TITLE
Token expired and no way to get a new one (except Admin dashboard)

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#506]
### Describe the bug
After ~a month the api token seemed to be expired. So the CLI always returned errors like 
```
Request to https://polyaxon.magazino.eu:443/api/v1/users/ failed with status code 403. 
Reason: {"detail":"Token expired"}
Could not load user info.
Error message `403 on https://polyaxon.magazino.eu:443/api/v1/users/.`.
```

`polyaxon login` returned with the same error. Also when first doing `poliaxon logout`. Finally we found the option to delete tokens in the admin dashboard. After deletion still the same token was returned. Only after wiping browser cookies and local storage we received a new token on login and were able to make it work again.

### To Reproduce
I assume it can be reproduced by trying to login one month after the first login

### Expected behavior
I think a new token should be generated automatically when the old one expires.

### Environment
GKE, polyaxon 0.4.4

**Comment by mouradmourafiq** [comment]
It should auto-renew the token, I will investigate this further.

**Comment by lgeiger** [comment]
We have experienced the same issue and also solved it by deleting the old token and then logging out of the UI to clear the cookie, before running `polyaxon login` again.

**Comment by mouradmourafiq** [comment]
How did you try to login from the CLI?

**Comment by lgeiger** [comment]
With the token using `polyaxon login`

**Comment by mouradmourafiq** [comment]
Makes sense it would tell you that is expired, login using the password would have refreshed the token,  at least that the current behaviour.

**Comment by mouradmourafiq** [comment]
polyaxon login has also an option to to login with password, that will effectively refresh the token.

For version > v0.5.3, there will be a patch to refresh the token in the other use cases that did not include the check.

Closing the issue, next release will have the fix, so hopefully you will never encounter this problem again.
