### ISSUE TITLE
Relax psutil version requirement

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#508]
### Describe the bug

`polyaxon_client` and `polyaxon` pins `psutil` to version `5.4.7`.
This causes problems when using Polyaxon with dependencies that bundle a newer version of `psutil` and will result in `pkg_resources.ContextualVersionConflict: (psutil 5.6.3 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('psutil==5.4.7'), {'polyaxon-client'})` when trying to install the requirements.

### To Reproduce
Consider the following `requirements.txt` executed in a docker container with TensorFlow preinstalled
```
tensorflow-datasets==1.0.2 # requires psutil and comes bundled with psutil==5.6.3 
polyaxon-client==0.5.2
psutil==5.4.7 # This line is required to satisfy the requirements
```

`pip install -e requirements.txt` will fail with `pkg_resources.ContextualVersionConflict: (psutil 5.6.3 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('psutil==5.4.7'), {'polyaxon-client'})`.

### Expected behavior

It would be great to update or relax the `psutil` requirement for better interoperability with other pip packages.

### Environment
Polyaxon 0.5.2
Python 3.7 + TensorFlow 1.14

**Comment by mouradmourafiq** [comment]
Fixed for v0.5.3.
