### ISSUE TITLE
Make more defensive confirmation dialog before deleting or stopping an entity

### ISSUE THREAD

**Issue by antifriz** [polyaxon/polyaxon#512]
### Feature motivation

Having a more defensive confirm dialog could avoid deleting the wrong project/experiment/job

Deleting experiments vs. project modals are now almost the same
`Are you sure you want to delete the selected experiment(s)`
vs.
`Are you sure you want to delete this project`
and ellipsis buttons to do it are identical, and both on the top right part of the screen.

### Feature description

For all irreversible actions, the UI should provide a more defensive confirmation dialog.

### Feature implementation

Modify modal to prompt the user to confirm the action:
- bold words `project`/`experiment`
- add some warning graphics
- similar to github/gitlab/etc. one must type in project name to delete it

**Comment by mouradmourafiq** [comment]
For the last point `similar to github/gitlab/etc. one must type in project name to delete it` this will take a bit more time, it's also related to #484

**Comment by mouradmourafiq** [comment]
Entities will be bold + there will be a red exclamation mark.
For entering the name before deletion, that will be handled in future commits in the other issue.

Closing this issue, a solution will be part of the next release v0.5.3.
