### ISSUE TITLE
Cannot update code for build docker image for jobs and experiments

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#514]
### Describe the bug
When I submit jobs and experiments, uploaded code is committed in the git repository in the NFS server. But, the uploaded files remains in staging. Moreover, I can't build docker images with the upload code.

By diving into the pod of NFS server in k8s, I saw the changed file is in git staging. Apparently, there is no conflict in the git repository.
```
[root@polyaxon-nfs-provisioner-nfsprovisioner-0 project-xxxx-xxxx]# git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   data.py
```

### To Reproduce
I don't know how to reproduce it. But, when we upgrade polyson from 0.4.2 to 0.4.4 and from 0.5.1 to 0.5.2, the issue occured. 
When we create a new polyaxon project with the same code, the problem didn't occur.

### Expected behavior
The code in NFS should be committed properly. Moreover, build process can use the code at `HEAD`.

### Environment
- GKE
- NFS server as a pod
- polyaxon: 0.5.2

**Comment by mouradmourafiq** [comment]
Did uploading the code a second time fix the issue?

**Comment by yu-iskw** [comment]
Not really. I uploaded the files with “polyaxon upload”, but the code remained in the staging.

**Comment by mouradmourafiq** [comment]
Did you check the API logs. You can simulate the same behaviour by uploading code to the same project again, 2 cases could happen, it will create a commit successfully or it will have the same issue, in that case maybe some errors will show in the logs.

Also does the CLI say that the upload was successful?

**Comment by yu-iskw** [comment]
`poloyaxon upload` and `polyaxon run -u` were definitely succeeded.

```
$ polyaxon upload
[================================] 3078684/3078684 - 00:00:06
Files uploaded.
```

Does API logs means the pods of polyaxon API? Although I saw the logs of pods, there is no meaningful information. If there is another way to see logs, please let me know.

```
Running...
Use default user
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
nginx is not running ... failed!
Restarting nginx: nginx.
nginx is running.
[uWSGI] getting INI configuration from web/uwsgi.nginx.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Jul 16 21:36:54 2019] ***
compiled with version: 6.3.0 20170516 on 13 July 2019 18:10:44
os: Linux-4.14.127+ #1 SMP Tue Jun 18 18:32:10 PDT 2019
nodename: polyaxon-polyaxon-api-7cd64dcc8b-6q9hv
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /polyaxon
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /polyaxon/web/..
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /polyaxon/web/../web/polyaxon.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Jun 11 2019, 01:21:42)  [GCC 6.3.0 20170516]
Python main interpreter initialized at 0x55842ac71b20
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 425960 bytes (415 KB) for 4 cores
*** Operational MODE: preforking ***
added /polyaxon/web/../polyaxon/ to pythonpath.
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55842ac71b20 pid: 80 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 80)
spawned uWSGI worker 1 (pid: 91, cores: 1)
spawned uWSGI worker 2 (pid: 92, cores: 1)
spawned uWSGI worker 3 (pid: 93, cores: 1)
spawned uWSGI worker 4 (pid: 94, cores: 1)
worker 1 lifetime reached, it was running for 14401 second(s)
worker 2 lifetime reached, it was running for 14401 second(s)
worker 3 lifetime reached, it was running for 14401 second(s)
worker 4 lifetime reached, it was running for 14401 second(s)
```

**Comment by yu-iskw** [comment]
`git add` was definitely executed, since I made sure the diff is in staging. But, `git commit` might not be executed appropriately. I understand the process to upload and commit code a little. But I don't still know how to debug it.

**Comment by yu-iskw** [comment]
@mouradmourafiq As the API pods mount the NFS pod/server, file permission issues potentially occurs. In your case, it seems that file permissions under `.git` of a certain polyaxon project in the NFS server were not appropriate. That is, `root` user of the API pods doesn't have write permission to files in `.git`. That is why it could move files to the git staging, but it could not commit.

I don't completely understahd why such a permission change occurs. But, I am doubting updating polyaxon or just restarting API pods can be the trigger. Besides that, I don't know why `git commit` via API doesn't raise error, even though it was not succeeded.

In my opinion, it would be great to have something to keep file permissions and owner of under `.git` appropriately or to reinitialize `.git` with CLI.

**Comment by mouradmourafiq** [comment]
@yu-iskw thanks for debugging this, I think I have seen this before now that you explained the issue, maybe an init container might be good to set correct permissions for the path. I will think about the best to handle this edge case.

**Comment by yu-iskw** [comment]
Sounds great! Thank you for the dedication as always.

**Comment by mouradmourafiq** [comment]
The git integration has been improved, it shows exactly what git commit was used with a link to the repo and commit in the lineage tab.

The upload option will be probably re-enabled for advance users, for now users should push to a proper git repo. some documentation about best practices will be published as well.

**Comment by lgeiger** [comment]
We've been running into the same issue on Polyaxon v0 after changing our repo storage backend to the Polyaxon NFS provisioner.

However we were able to resolve this by switching to the upstream [Helm NFS server provision chart](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) which uses NFSv3 and an newer docker image. We haven't run into this issue again since.

**Comment by mouradmourafiq** [comment]
Thank you so much @lgeiger for the comment, the nfs-provisioner chart was archived, and the documentation points to the main helm reference.
