### ISSUE TITLE
Issue setting experiment artifact_refs

### ISSUE THREAD

**Issue by ajgreine** [polyaxon/polyaxon#524]
### Describe the bug
When attempting to set the `artifact_refs` in an experiment yaml, the CLI will accept the yaml as valid and then throw an error like this:
```
Reason: ["[ErrorDetail(string=\"Persistence outputs value is not valid ['outputs-s3-temp'], it should be a string.\", code='invalid')]"]
```

### To Reproduce
Add the following to an experiment yaml and try to run using the Polyaxon CLI:
```
environment:
  artifact_refs: ['<volume name>']
```
### Expected behavior
Adding the `artifact_refs` to you yaml should allow you to set the output volume to be scheduled to your experiment pod.

### Environment
CLI 0.5.2 MacOS

**Comment by mouradmourafiq** [comment]
A fix will be provided for the v0.5.4.
