### ISSUE TITLE
Unclear documentation on how to configure SSO

### ISSUE THREAD

**Issue by uipo78** [polyaxon/polyaxon#529]
### Unclear documentation

[This section](https://docs.polyaxon.com/integrations/sso-gitlab/) describes how to configure GitLab SSO in the `config.yml`/`values.yaml` file.

### Missing Documentation

There isn't an `auth` section in [the helm chart reference documentation](https://docs.polyaxon.com/references/polyaxon-helm-reference/#how-to-set-the-configuration) and the `polyaxon admin deploy --check -f config.yml` command says that such a key isn't recognized.

There isn't any documentation describing how to configure AzureAD SSO in the `config.yml` file.

**Comment by mouradmourafiq** [comment]
True, it's on the settings page, under auth.

**Comment by mouradmourafiq** [comment]
docs have been updated to reflect the new workflow to setup SSO with Gitlab.

Thanks for reporting.
