### ISSUE TITLE
No SSO buttons appear on login page

### ISSUE THREAD

**Issue by uipo78** [polyaxon/polyaxon#531]
### Describe the bug

No SSO buttons appear on the login page.

### To Reproduce

I followed [these instructions](https://docs.polyaxon.com/integrations/sso-azure/), enabling Azure SSO and including all of the requisite values (client id, client secret, etc.).

### Expected behavior

I expected to see a "Log in with Azure" button (or the like) at the login screen. I also expected that the settings page would reflect the fact that I enabled Azure SSO (the `AUTH_AZURE:ENABLED` section remained blank).

### Environment

Kubernetes. Deployed Polyaxon 0.5.3.

**Comment by mouradmourafiq** [comment]
I think there's a small UI bug, for the enabled dropdown, it need to change to state, just select False, and then True, and then save.

**Comment by mouradmourafiq** [comment]
What browser are you using?

**Comment by uipo78** [comment]
Chrome
