### ISSUE TITLE
Easily version and pause polyaxon notebook.

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#536]
### Feature motivation
1. I want to version notebooks back to github.
After I make notebooks which is worthwhile versioning on polyaxon, I want to give back to github. As you modified to make it downloadable by adding the flag, we can download notebooks manually. However, ideally, it would be great to version back to github.

2. I want to pause notebook pods not to spend money while I am not using.
When I leave notebooks unfinished and I go in weekends, I don't want to spend money for the environment. Pausing the notebook on polyaxon would be convenient to me.

### Feature description
- Easily version modified resources on polyaxon notebook with git.
- Pause polyaxon notebook pods.

**Comment by mouradmourafiq** [comment]
I think the whole notebook experience, apis/client, programatic usage, tracking experience, developer side docs must be improved.

I am even thinking about assigning a whole cycle for that purpose.

**Comment by yu-iskw** [comment]
I totally agree with you. It would be great to consider the whole lifecycle of a machine learning project with polyaxon. The experience of notebook is the part of them.

I would love to join the discussion. And I will prepare for a material that I usually manage the lifecycle.

**Comment by mouradmourafiq** [comment]
All default notebook components:
 * auto-save progress
 * are resumable 
 * github: for pushing changes to github, the best way is to inject  an [ssh connection](https://polyaxon.com/docs/setup/connections/#connections) in the notebook with granular access to the repos you want to have push access to.
 * Client has a lot of promising changes: 
    * You can submit jobs from notebook in variety of ways (based on component hub, from yaml files, from python files, using an imperative API `from polyaxon.polyflow import *` )
    * you can use the client to stream logs for the runs you created or other runs in the project
    * watch conditions
    * wait for condition to monitor a run and drive dependent workflows
    * use polytune for programmatic hyper parameters tuning
    * use the querying, filtering, sorting and visualization to drive insights
* Intergration with voila and commuter component to share read-only versions of your notebooks to other users.
