### ISSUE TITLE
Speed-up k8s autoscaling

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#537]
### Feature motivation

When using Polyaxon on public cloud infrastructure in a small Team with GPU node pools it often makes sense to autoscale to zero to reduce cost. Starting a new experiment can then take a few minutes since the cluster first needs to scale up, install the GPU drivers, etc.

### Feature description

It would be great to be able to speed up this autoscaling process by already triggering the scale up when starting the docker build. This would mean that the scaling up and node booting 
would happen in parallel to the docker build (build times with GPU enabled containers can reach from a few seconds to even minutes depending on the cache).

### Feature implementation

This could be implemented naively by starting a noop probe container with the same resource requests and limits as the experiment job together with the build which triggers a scale up in parallel. This implementation idea would arguably be quite brittle and may cause unnecessary scale up). I am not sure if there is a proper concept for use cases like this in k8s or GKE.

Do you think this feature would make sense for Polyaxon or would it add too much complexity to the platform compared to the amount of users that would benefit from a feature like that?

**Comment by mouradmourafiq** [comment]
I think, one could easily create an echo job with pinned commit (to not retrigger a build) and basically just start that job (maybe call it probe job).

You can trigger the job or restart it from ui or from cli.

I think doing it that in the platform will be just an extra complexity to maintain.

**Comment by lgeiger** [comment]
I don't think this issue is relevant for v1 anymore.
