### ISSUE TITLE
Logging outside of cluster managed by Polyaxon

### ISSUE THREAD

**Issue by Lap1n** [polyaxon/polyaxon#540]
### Unclear documentation

In the documentation, it is mentioned that we can logs outside of a cluster managed by Polyaxon ( https://docs.polyaxon.com/references/polyaxon-tracking-api/other-environments/).
However, it is not working for me, the logs doesn't seems to be stored on the server (I tried 2 configuration, storing at the default location and at a S3 server). 

I tried to upload logs manually for debugging and when it sends logs (send_logs function in experiment.py), the request seems to return 200 (line 270) although I cannot see it in the ui or in the file system.

Note that logging is working with managed experiments (polyaxon run -f config.yml).

Did I missed something (like an environment variable to set)?

**Comment by mouradmourafiq** [comment]
That was a regression.

A fix will be part of v0.5.5.
