### ISSUE TITLE
Support for i18n

### ISSUE THREAD

**Issue by brunowego** [polyaxon/polyaxon#542]
### Feature motivation

Hi everybody! 
Is there any work front for internationalization of the tool?
Multi-language support are really cool feature!

**Comment by mouradmourafiq** [comment]
At the moment there's no plans or work towards i18n, but I am happy if anyone is interested by translating the docs to other languages as a first step.

**Comment by Gabrielglvr** [comment]
Awesome ! Bruno is my teammate and we love the project, i thing we can start to translate the documentations and the project too.
