### ISSUE TITLE
AMD/ROCM support

### ISSUE THREAD

**Issue by boniek83** [polyaxon/polyaxon#543]
### Feature motivation

More hardware choice.

### Feature description

Make AMD hardware first class citizen next to NVidia. You can use consumer cards (e.g. Radeon VII with 16GB HBM2) legally in datacenter as opposed to NVidia.

### Feature implementation

AMD forked a lot of code (with intention to merge it upstream) all available under: https://github.com/RadeonOpenCompute
https://github.com/RadeonOpenCompute/ROCm_Documentation
Intergration of rocm with kubernetes is pretty straightforward (they have kubernetes device plugin). They have some docker images available: https://hub.docker.com/u/rocm
I coudn't get horovod fork (wtih mxnet) to compile, there is no docker with horovod (at least I couldn't find one). Tensorflow seems to be working.

**Comment by mouradmourafiq** [comment]
In v0.5.x you can update the default gpu accelerator key.
In v0.6 you can specify the gpu type directly in the specification.
