### ISSUE TITLE
How to do distributed training with Tensorflow 2.0 ?

### ISSUE THREAD

**Issue by mabhisharma** [polyaxon/polyaxon#546]
Hi All,
I have tried distributed training on tensorflow 1.4 with polyaxon 0.5.4 and the given example for distributed training works. Here is the link for the working example on tensorflow 1.4 :- https://github.com/polyaxon/polyaxon-examples/tree/master/in_cluster/tensorflow/cifar10. 

With the coming new release of Tensorflow 2.0 (which is in Beta right now), I want to know how can I start distributed training ?  I believe with tensorflow 2.0 we have to set `TF_CONFIG` flag on each worker in the cluster. I am able to do distributed training using kubernetes but I was not able to find any examples on how can I use polyaxon to do it. Any example of polyaxon.yaml file for distributed tensorflow 2.0 should be enough to get me started. Any help will be appreciated.

**Comment by mouradmourafiq** [comment]
Hi @mabhisharma 

All workers/ps have a `TF_CONFIG` set by default.

In polyaxon v0.6.0 distributed runs will use TFJob/PytorchJob/MXnetJob by default and transparently.

**Comment by mabhisharma** [comment]
@mouradmourafiq Thank you!
