### ISSUE TITLE
Ghost tensorboard pods after project deletion

### ISSUE THREAD

**Issue by patrungel** [polyaxon/polyaxon#549]
### Describe the bug

Might be a duplicate of https://github.com/polyaxon/polyaxon/issues/526
When projects get deleted ternsorboard pods keep running but unreachable from polyaxon.

### To Reproduce
We had many projects that had tensorboards running (>250) and then we deleted all the projects automatically (using this awful command: 
```
kubectl get pods -n polyaxon --show-labels | \
grep dummy | grep Running | grep tensorboard | \
perl -lne 'print $1 if /project_name=dummy-jobs.(.*-smoke_test-.*),p/' | \
xargs -n 1 -I {} sh -c "yes | \
polyaxon project -p {} delete"
```
).

### Expected behavior

We expected that deleting a project also kills the tensorboard and it did so for about 100 out of the 250. 

However the other 150 kept running (pods were running and tensorboard were reachable) but were unreachable from polyaxon (polyaxon tensorboard -p <project id> didn't show any output), hence couldn't be deleted.

### Environment
k8s: 1.13.4
polyaxon:0.4.4

**Comment by mouradmourafiq** [comment]
I think this bug will be solved automatically once the operator is GA, an initial version will be part of the v0.6.
