### ISSUE TITLE
Add support for downloading code based on a specific commit or experiment

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#550]
### Feature motivation

As discussed in the slack channel:

As a user I should be able to specifiy which commit I want to download code for, currently `polyaxon project download` automatically downloads latest commit by default.

### Feature description

CLI:

* Adding a commit flag for project download `polyaxon download [--commit]`
* `polyaxon experiment code` to download code for an experiment based on the code ref.
* `polyaxon job code` to download code for an experiment based on the code ref.

UI:

 * Add an easy way to download code from UI for jobs/experiments.

**Comment by yu-iskw** [comment]
In addition to downloading the code, I would also like to see the code which was used in an experiment on the UI.

**Comment by mouradmourafiq** [comment]
@yu-iskw The code tab in the UI will handled separately in the #417

**Comment by vfdev-5** [comment]
@mouradmourafiq seems like the documentation of CLI does not show `code` as option...
