### ISSUE TITLE
Show full paths of outputs on the web UI

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#551]
### Feature motivation
Downloding output files on the web UI would be great. Sometimes, I would like to know the paths of outputs, which are on GCS in my case.

### Feature description
Show a full path of an output on the web UI.

![AwesomeScreenshot-localhost-app-yu-mercari-us-ml-weight-suggestion-new-jobs-278-2019-08-09_4_20](https://user-images.githubusercontent.com/1523515/62813797-b040c500-bac1-11e9-8603-674b13a1246c.png)

**Comment by mouradmourafiq** [comment]
This was actually fixed in
