### ISSUE TITLE
Private registry key usage

### ISSUE THREAD

**Issue by KirkHadley** [polyaxon/polyaxon#552]
### Description
Not sure if this warrants a new issue given its closely related to the already closed [#511 ](https://github.com/polyaxon/polyaxon/issues/511), but I think I've got the other side of the issue here.
 Also, total kubernetes newcomer, so apologies if this is terribly dumb. I'm trying to use a private registry (ECR) instead of the in-cluster docker registry for both pushing and pulling images. 

### To Reproduce
I added the secret with kubectl:
`kubectl create secret generic dconf --from-file=sec_config.json=./sec_config.json -n polyaxon`

where the file was like `{"credsStore":"reallyLongPasssword"}`, with the password coming from `aws ecr get-login`. 

### Expected behavior
If I understood the docs correctly, it looks like the key should just be listed in the UI, but I don't see anything there, nor was there anything after I ran an upgrade using the polyaxon CLI tool. 

Any help would be much appreciated!

### Environment
polyaxon 0.5.5
kubernetes+helm

**Comment by mouradmourafiq** [comment]
Once you create the secret you need to make Polyaxon aware of it, the way you do that is by creating a new secret in the secret store. And then you attach that secret to the registry.

**Comment by KirkHadley** [comment]
Thanks for getting back so quick! So the new secret I create in the catalog, that happens in the UI? So what goes in the K8s ref field?

**Comment by mouradmourafiq** [comment]
The ref is the k8s secret name `dconf`

**Comment by KirkHadley** [comment]
Awesome, thank you! Last follow up question for you, how to resolve an error that I don't have correct permissions to start jupyter notebooks? I can start the service, but get a permission denied error when actually trying to create a notebook.

**Comment by mouradmourafiq** [comment]
> I can start the service, but get a permission denied error when actually trying to create a notebook.

Not sure what do you mean by you `can start the service` and `create a notebook`.

I think it's better to create a new issue with a bit more context if you still have problems with notebooks.

I will close this one since the question regarding the registries was clarified.
