### ISSUE TITLE
Resumed experiments no longer resume

### ISSUE THREAD

**Issue by jamescook106** [polyaxon/polyaxon#553]
### Describe the bug

We recently upgraded from Polyaxon 0.5.4 to 0.5.5, and our resume function has stopped working. When I say stopped working, from the UI, it says resumed, but it has not appeared to have copied the outputs from the experiment it has resumed for, and hence we get a restarting behaviour. I have confirmed that in Polyaxon 0.5.4 we do not have this issue by rolling back our deployment to check, however due to #544, we have reverted back to 0.5.5. For now we are using a work around for resuming experiments of
```
polyaxon experiment -xp <id> restart --copy
```

### To Reproduce
Resume an experiment that requires the outputs of the experiment it is resuming from to resume i.e a checkpoint file

### Expected behaviour
As per Polyaxon 0.5.4, experiment resumes
### Environment

Polyaxon 0.5.5
GKE
Google Filestore for outputs

**Comment by mouradmourafiq** [comment]
Sorry about this regression, I can confirm that the it is fixed now.

A new patch v0.5.6 will be released in the next 2 days.
