### ISSUE TITLE
Create selection group with the python client

### ISSUE THREAD

**Issue by Lap1n** [polyaxon/polyaxon#559]
### Feature motivation
I don't know if it is a bug, but it would be useful if we could create selection group by code. It would simplify workflow where we need to create groups when they do not exist yet. Right now, we can only create hyperparameter search type group that requires a configuration file.

### Feature description
Create an experiment group without having to specify a configuration with the python client (the "content" parameter when creating a group). Basically, be able to create selection type group by code.

**Comment by mouradmourafiq** [comment]
it's possible already. For anything programatic, I would suggest that you use the tracking api, as it exposes a simple interface: 
 * [docs](https://docs.polyaxon.com/references/polyaxon-tracking-api/experiment-groups/#creating-a-group)
 * [code section](https://github.com/polyaxon/polyaxon-client/blob/master/polyaxon_client/tracking/group.py#L11)

**Comment by mouradmourafiq** [comment]
I am closing the issue, please feel free to reopen if you think that the current solution is not working.

**Comment by Lap1n** [comment]
Yes, I already tried with the following code : 
```
group = Group(client=client, project="test")
group.create(tags=['foo', 'bar'], description='New group')
```
But I get the following error : 

Reason: {"non_field_errors":["Experiment Group expects a `content`."]}

 I would like to be able to create a group without a configuration (the content parameter).

**Comment by mouradmourafiq** [comment]
Ok then this is a regression, thanks for reporting that.

**Comment by siddygups** [comment]
@mouradmourafiq any updates on this by any chance? More generally should groups be used to organize similar experiments when hptuning is not an objective?

**Comment by mouradmourafiq** [comment]
@siddygups No work have been done on this yet, but it will be part of a patch release planned soon.

The group created is a selection, so I guess it makes sense.

**Comment by mouradmourafiq** [comment]
Selection groups have been removed in favor of just saved searches, when the objective is not hptuning, a search based on a specific tag can be used, the dashboard allows to drive all the viz/comparison without the need to create a selection.
