### ISSUE TITLE
No way to mount actually existing data to process

### ISSUE THREAD

**Issue by jrozansk** [polyaxon/polyaxon#56]
After examining documentation I don't see possibility to mount actually existing volume with data to newly created experiment's pod.
In the polyaxon-examples I see data prefetched from the Internet. It won't work for multi-gigabyte datasets (real-world scenarios).

I imagine it would be possible to specify persistent storage in polyaxonfile that would be attached to pods. Correct me if I am wrong. Then for first experiment data from one place is mounted and for the second one completely different source of data is specified.

-----
I see a way to specify data share via configuration [here](https://docs.polyaxon.com/reference_polyaxon_helm/#persistence) but as I understand it is not easily changeable after deployment. It can be workaround to use just one volume that holds entire data for now.
For the long run I think I would be better to make it configurable per job/experiment.

@mouradmourafiq It is actually up to you to decide which way to go of course. This issue is just my suggestion.

**Comment by mouradmourafiq** [comment]
Hi @jrozansk, yes you are correct the first experiment in the example downloads the data. But of course the volume could already have data beforehand and I would have just pointed to the right path to use in the script.

For the hypothetical scenario that you proposed, you can do that now also, but only with one volume, in other words, you can have multiple data sitting next to each other in the same volume, and you specify in your code which folder to use.

Regarding the proposal of specifying the volumes on the polyaxonfiles, I think it's could be something to do in the future, definitely needs a bit more thinking, but I like the idea.

**Comment by VitaliKaiser** [comment]
I would extend this feature request by binding of HDFS storages like S3, Google Buckets, etc... directly and cached. Readonly would be sufficient for datasets. Maybe it would be possible to integrated this?

https://github.com/s3fs-fuse/s3fs-fuse

**Comment by VitaliKaiser** [comment]
I found this by chance today, I guess it´s easy to add (I am a Kubernetes noob, but it sounds nice):
https://github.com/childsb/s3fs-container

**Comment by ziyitony** [comment]
@mouradmourafiq hello mourad, sorry for disturbing you.
I am a kubernetes noob and new to polyaxon, and I tried 2 days to figure out how to mount path on vm to polyaxon experiment, but failed.
I set up polyaxon successfully and I can run experiments in [polyaxon-example repos](https://github.com/polyaxon/polyaxon-examples) successfully, but I failed mounting volumes in my own [demo project.](https://github.com/ziyitony/my-polyaxon)

I claimed volumes to mount but just can't find files in anyplace. I run polyaxon not in root user.
Please help me, thank you.

**Comment by mouradmourafiq** [comment]
@ziyitony can you give a bit more information about your current cluster?

**Comment by mouradmourafiq** [comment]
It has nothing to do with config file rather with the type of volume you have mounted,  you used hostpath, and you need to create a persistent volume with read [/write] many, please [see](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes)

**Comment by ziyitony** [comment]
thank you very much! You REALLY help me a lot.
Do you have any suggestion which one to choose? can I use nfs?

**Comment by mouradmourafiq** [comment]
In this [tutorial](https://docs.polyaxon.com/tutorials/gke_deployment/kubernetes_on_gke/#gke-kubernetes-cluster) I create an nfs server to mount nfs volumes. It's just a tutorial, and it was using GKE. You should find a tutorial on the internet for setting up any of the options. I would recommend that you choose the simplest option for you to try, and only invest time if you want to have a long running deployment that you would maintain.

**Comment by ziyitony** [comment]
Thanks a lot. I will try it. Hope you a good day.

**Comment by rapatel0** [comment]
> I would extend this feature request by binding of HDFS storages like S3, Google Buckets, etc... directly and cached (would allow local disk speed after the first epoch in training). Readonly would be sufficient for datasets. Maybe it would be possible to integrated this?

PLEASE NO.

**Comment by mouradmourafiq** [comment]
@rapatel0 there's no plan to use *fuse, some people requested gcsfuse as well, but for the same reasons you pointed, latency, there's no plan on doing that by default. Obviously, the user can do that do on their end if they want, but it will not be a default behaviour of the platform.

Right now, the platform can automatically schedule jobs/experiments with all secrets needed to access cloud storages, we just open sourced this store [abstraction](https://github.com/polyaxon/polystores) if people want to use it, but in the future there will be an abstraction to allow the users to put outputs/artifacts to the host node and a builtin sidecar to collect them after the pod is finished, to make it transparent.

**Comment by rapatel0** [comment]
The latter methodology sounds great. Also, if you could add an initialization step to the workflow, (maybe with an init container or something, that would be ideal. We have a use case where a user wants a local cache of really small images (bytes each). Pulling these from cloud stores one at a time is quite slow. 

It could be similar to a container build step, where we pull data from various sources, apply some processing (to collect the data from various sources, and potentially preprocess it ) and then make it available as a mount point. 

One point to note is that kuberetees doesn't enforce volume size constraints on PVs (unless you dynamically provision from a block device I assume) so you can run the risk of filling up a disk quite quickly.

**Comment by mouradmourafiq** [comment]
There's new documentation for using the different types of stores.
Further enhancement are planned to automatically collect artifacts/prepare data #273
