### ISSUE TITLE
Outputs not showing in UI when experiments are created as members of a selection group

### ISSUE THREAD

**Issue by Lap1n** [polyaxon/polyaxon#560]
EDIT: Hum, this is probably related to the fact that i'm uploading the data to the wrong S3 path. It seems that experiment in groups have a different storing path than experiments that are not part of a group. Closing this issue for now.

### Describe the bug
When I create an experiment linked to a selection group (by code, not using the UI), the outputs are not shown when I visualize the outputs tab. The weird part is that the outputs are present in my Minio S3 server, so it really seems that it is an UI related problem.

The outputs are shown however when experiments are already created and I'm using the UI to add them to the selection group.

### To Reproduce
Create an experiments with group id specified and store outputs. 
(My setup uses Minio S3 server for the outputs storing)

### Expected behavior
Be able to see the outputs in the UI
### Environment
Polyaxon 0.5.6
Unmanaged experiments
Minio S3

**Comment by Lap1n** [comment]
Hum, this is probably related to the fact that experiments in groups uses different output path than normal experiments. So, I'm probably uploading the data to the wrong S3 path (I'm setting the outputs path manually in my code since I'm working with unmanaged experiment). Closing this issue for now.

**Comment by mouradmourafiq** [comment]
Yes the selection group is merely an association for fast access as opposed to the hyperparams groups. That being said, there is work to consolidate the paths to make it less confusion to work with for users.

**Comment by Lap1n** [comment]
Yes, I already tried with the following code : 
```
group = Group(client=client, project="test")
group.create(tags=['foo', 'bar'], description='New group')
```
But I get the following error : 

Reason: {"non_field_errors":["Experiment Group expects a `content`."]}

I suspect this is happening because I working with unmanaged experiments.
