### ISSUE TITLE
gitlab authentication redirect is failing with Polyaxon error

### ISSUE THREAD

**Issue by aruninnanje** [polyaxon/polyaxon#568]
### Describe the bug
We have a private gitlab setup and  i am trying to authenticate sso for polyaxon via gitlab

I have followed the instructions in https://docs.polyaxon.com/configuration/sso/

### To Reproduce
1. Create an application in gitlab  for polyaxon
2. set the redirect URL to http://10.10.0.103:31811/oauth/gitlab as described in https://docs.polyaxon.com/configuration/sso/
3. copy clientID and secretkey into AUTH_GITLAB:CLIENT_ID & AUTH_GITLAB:CLIENT_SECRET polyaxon settings
4. set AUTH_GITLAB:URL  to private gitlab url 
5. Login into polyaxon using "login with Gitlab"
6. login with gitlab account
8. get the below error
![image](https://user-images.githubusercontent.com/25972061/64048277-4a36e300-cb3f-11e9-88bb-5031fbb2ee91.png)

#REST URL
http://10.10.0.103:31811/oauth/gitlab?code=9d5ee3066688dbdd106ad9470f2451ff0e558582f421c39c2cd3ceb656fb3bac&state=60328abbf97c438ca08f545155977343
Request Method: GET
Status Code: 500 Internal Server Error

**Comment by axelperschmann** [comment]
same abservation here, except for my redirect URL  does not contain a port number:

```http://a.b.c.d/oauth/gitlab```

Have you been able to solve this issue and enable SSO via gitlab?

**Comment by aruninnanje** [comment]
I am not sure, I gave up after trying several times. Now we had to move to to kubernetes 1.16 and polyaxon wont install.
Probably revisit it some time later

**Comment by mouradmourafiq** [comment]
Closing as wontfix. A much better interface will be exposed for open source users to use their own user management system
