### ISSUE TITLE
Data Tracking

### ISSUE THREAD

**Issue by bmiselis** [polyaxon/polyaxon#576]
### Feature motivation

Polyaxon is advertised as:

> A platform for reproducible and scalable machine learning and deep learning on Kubernetes.

I'm curious, how is data tracking issue solved here? 

### Feature description

I can clearly see the code being tracked by Polyaxon, but let's say I have an original dataset A, which I train model A on. Then I modify some samples from the dataset so that I end up having dataset B, which I train model B on. Now, if I would like to reproduce the results of model A, but now only have dataset B on my machine, how could I somehow "checkout" to the previous version of the dataset?

If such a case cannot be handled by Polyaxon, then what would be a recommended way to do so while using Polyaxon?

**Comment by mouradmourafiq** [comment]
When you apply changes to data A, the result should not be overriding data A in-place, you should rather produce a new artifact: "modified data A: B". This way you can not only retart job with same dataset, but you can also achieve lineage of produced dataset, i.e. dataset B was produced based on dataset A using job 1234.

**Comment by bmiselis** [comment]
Hmm, but imagine my dataset A is 100GB and I only modify a bunch of samples. I'm not sure storing yet another copy of all the data is the best way to go 🤔

**Comment by bmiselis** [comment]
Have you considered integrating Polyaxon with something like [DVC](https://dvc.org) or [pachyderm](https://pachyderm.io)?

**Comment by mouradmourafiq** [comment]
I believe you can use any of those tools with Polyaxon, I don't think the platform prevents or limits the user in using other tools to extend it's functionality.

Regarding the size of the datasets, if only a subset of the dataset is changed, than I believe that artifact should only contain those new changes.

Of course if you are looking for a full diff, Polyaxon will not show that type comparison.

**Comment by bmiselis** [comment]
Okay, that clarifies my question, thank you @mouradmourafiq !

**Comment by mouradmourafiq** [comment]
no problems 👍 
I am closing the issue for now.
