### ISSUE TITLE
Use resulting image of kind: build in jobs/experiments

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#577]
### Unclear documentation
There is documentation on the concept of builds:
https://docs.polyaxon.com/concepts/builds/
and there is doc on the `build:` section of polyaxon files:
https://docs.polyaxon.com/references/polyaxonfile-yaml-specification/build/
Finally here is a example of how to define a standalone Build `kind: build`:
https://github.com/polyaxon/polyaxon-quick-start/blob/master/polyaxonfile_build.yml

What i'm missing is how to use the image resulting from the build. I imagine besides `image:` and the alternative `dockerfile:` there should be sth. like `base-build:` in polyaxonfiles...? Or maybe it's just used differently?

**Comment by mouradmourafiq** [comment]
Next release will have polyflow in Public beta, and this type of dependencies will be possible.

**Comment by Mofef** [comment]
Cool! Looking forward to that!
But  is there some use of "stand-alone" builds at the moment that I'm missing?

**Comment by mouradmourafiq** [comment]
It's possible but not straightforward to do, because the tag depends on the build uuid.

**Comment by mouradmourafiq** [comment]
Closing this, it's possible to build images even outside of Polyaxon and use them for jobs/experiments, the build step is not required anymore, this is will remove many issues and problems.
