### ISSUE TITLE
Ghost tensorboards

### ISSUE THREAD

**Issue by koenhelwegen** [polyaxon/polyaxon#578]
### Describe the bug

On multiple occasions, we have had about a handful of tensorboards running In polyaxon (`.../_admin/db/tensorboardjob/`), while at GCP (kubernetes workloads) we see dozens of tensorboards, and our tensorboard sessions become very slow. It seems as if polyaxon is starting multiple tensorboards which it subsequently looses track off.

May be related to https://github.com/polyaxon/polyaxon/issues/549, but we're not deleting projects.

### To Reproduce
Open a bunch of tensorboards in various parallel projects.

### Expected behavior

Open tensorboards in polyaxon admin dashboard should match tensorboards in GCP (and there shouldn't be 50+ of them).

### Environment

Polyaxon 0.5.6, GCP.

**Comment by mouradmourafiq** [comment]
What status do they have in the admin interface? if they are in failed/stopped/succeeded, that means that tensorboards have been already shutdown. The only number that needs to match, is the number of running tensorboards to the ones running on GCP.

The bug that exists now, is sometimes after stopping a tensorboard, the deployment might keep running, the reconciliation issue is solved for the v0.6.

**Comment by koenhelwegen** [comment]
Could very well be the existing bug then. The admin dashboard itself looks fine - running tensorboards there match the tensorbaords we're actually using at the moment, and old tensorboards are all `stopped` or `failed`. It's just that there are dozens of additional tensorboards running according in GCP that don't show up in polyaxon, and that slow down the tensorboards we do use.

For now we just kill all tensorboards via GCP every now and then. Hopefully v0.6 will fix the issue, otherwise we will let you know :)
