### ISSUE TITLE
private registry and secret setup in polyaxon.

### ISSUE THREAD

**Issue by dongdan39** [polyaxon/polyaxon#581]
Hi, 
  I found my polyaxonfile_hyperparams.yml example on polyaxon v0.5.6 always failed when pushing docker image to my private registry. Checked that pulling and pushing docker images from/to the registry all work fine on all nodes by hand already. I have created the secret properly with:
$kubectl create secret docker-registry regcred --docker-server=192.168.111.118 --docker-username=admin --docker-password=XXXXXXX --docker-email=XXXXXXXX@XXXX.com

$kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
{"auths":{"192.168.111.118":{"username":"admin","password":"XXXXXXX","email":"XXXXXXXX@XXXX.com","auth":"YWRtaW46aGFzTeYi7MTIz"}}}

Then I tried to configure these info into polyaxon and combine the secret with registry, however, no matter how they were set, the jobs always failed with:

2019-09-26 07:25:17 UTC -- Building: Successfully built 63610415a2d6
2019-09-26 07:25:17 UTC -- Building: Successfully tagged 192.168.111.118/library/mnist_1:c8dd441c826741f8b55f67a3d0260aa5
2019-09-26 07:25:17 UTC -- **ERROR: denied: requested access to the resource is denied**

Could anybody shed more light on how to fill them? E.g: for "K8S Ref" I filled the secret I cerated "regcred", but not sure how to fill "Items", what does this mean and any examples?

In "Secrets" menu, 
K8S Ref:  regcred
(The K8S entity reference name.)
Items: <BLANK HERE>
(The K8S entity items to expose, if no key is provided, Polyaxon will expose all items of the resource. Use new lines to separate items.)

The "Registries" menu seems more straight forward, I just filled the private registry IP and match the secret with it. Not clear if any config is wrong in the above? Thanks!

Cheers,
Dan

**Comment by mouradmourafiq** [comment]
Please create  a [generic secret](https://docs.polyaxon.com/integrations/dockerhub/#create-a-secret-containing-the-credentials-to-use-with-docker-hub)

**Comment by dongdan39** [comment]
@mouradmourafiq Exactly! generic secret works here, Thanks so much!
