### ISSUE TITLE
Support TensorBoard 2.0.0

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#583]
### Describe the bug

TensorFlow 2.0.0 was released yesterday.
[TensorBoard 2.0.0 changed the way it is exposed  to the network](https://github.com/tensorflow/tensorboard/releases/tag/2.0.0) which unfortunately makes it unusable in Polyaxon.

### To Reproduce
1. Start a TensorBoard with a docker container that uses `tensorflow==2.0.0`.
2. Observe that TensorBoard pod is running and correctly logs `Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all`
3. Accessing TensorBoard via Polayxon fails due to page not found 

### Expected behavior

TensorBoard opens normally

### Environment

Polyaxon 0.5.6
TensorBoard 2.0.0

**Comment by EAR-Development** [comment]
If i understand the repository correctly, it should be sufficient to add 
--host = 0.0.0.0
to
https://github.com/polyaxon/polyaxon/blob/6aa3b5dee66e17592182335db73f65e4f0259386/platform/core/polyaxon/polypod/tensorboard.py#L198-L205

**Comment by lgeiger** [comment]
For now we've worked around it locally by using the following docker image:

```Dockerfile
FROM python:3.7-slim

RUN pip install tensorflow-cpu==2.1.0rc1 --no-cache-dir

COPY tb_backport.py /usr/local/bin/tensorboard
```

`tb_backport.py`
```python
#!/usr/local/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from tensorboard.main import run_main


if __name__ == "__main__":
    sys.argv = [arg.replace("--logdir", "--logdir_spec") for arg in sys.argv] + ["--bind_all"]
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(run_main())
```

It is not a very nice solution, but it works for now.

**Comment by mouradmourafiq** [comment]
A new release v0.6.1 is coming in the next couple of hours with support for k8s 1.17 and some security fixes.

I am making a fix for this issue as well, this is such a horrible experience and it took so much time, sorry about that.

**Comment by mouradmourafiq** [comment]
I just want to clarify that, the fix will only include the `--host` flag, which is supported by tf2 as well as previous versions.

The comma delimited paths is not fixed in this version unfortunately, that fix is only available in v1 because of the flexibility of creating several components with tags.
