### ISSUE TITLE
Repo for polyaxon-dockerizer behind a proxy

### ISSUE THREAD

**Issue by brunowego** [polyaxon/polyaxon#584]
### Describe the bug

My infrastructure are behind a proxy and I not have access for docker.io. Have a way to configure out the `polyaxon-init-job`?

```sh
Events:
  Type     Reason     Age                    From                   Message
  ----     ------     ----                   ----                   -------
  Normal   Scheduled  4m24s                  default-scheduler      Successfully assigned polyaxon/plx-build-753e9a3c775b462dab920b12a09c6aab to pxl1pscbg014
  Normal   Pulling    2m14s (x4 over 4m23s)  kubelet, pxl1pscbg014  pulling image "polyaxon/polyaxon-dockerizer:0.5.6"
  Warning  Failed     119s (x4 over 4m8s)    kubelet, pxl1pscbg014  Failed to pull image "polyaxon/polyaxon-dockerizer:0.5.6": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     119s (x4 over 4m8s)    kubelet, pxl1pscbg014  Error: ErrImagePull
  Normal   BackOff    107s (x6 over 4m7s)    kubelet, pxl1pscbg014  Back-off pulling image "polyaxon/polyaxon-dockerizer:0.5.6"
  Warning  Failed     95s (x7 over 4m7s)     kubelet, pxl1pscbg014  Error: ImagePullBackOff
```

Perhaps putting this on a config map?

https://github.com/polyaxon/polyaxon/blob/0c47bd220bccf60d5af72af6dc9074f36903c029/polyaxon/options/registry/build_jobs.py#L84

**Comment by mouradmourafiq** [comment]
You can set `BUILD_JOBS:DOCKER_IMAGE` in the settings page > more options, the value can be set to the correct image you want to use.

**Comment by brunowego** [comment]
Thanks @mouradmourafiq 👍

**Comment by brunowego** [comment]
@mouradmourafiq are not saving the option (version 0.5.6):

![Kapture 2019-10-02 at 15 44 47](https://user-images.githubusercontent.com/441774/66072617-c13f0d00-e52b-11e9-82cf-6f9417aaf037.gif)

**Comment by brunowego** [comment]
Sorry @mouradmourafiq. The env are saved in db. Thanks.

<img width="792" alt="Screen Shot 2019-10-03 at 09 09 20" src="https://user-images.githubusercontent.com/441774/66125534-91404a00-e5bd-11e9-8b64-f3392f1a6c95.png">

**Comment by mouradmourafiq** [comment]
There's a cache mechanism depending on the option, so for some options where the value is expected to not change frequently, like this one, it might take some time to take effect.

If you want to make take effect, you need to restart the scheduler.

**Comment by brunowego** [comment]
@mouradmourafiq have a way to set it globally? I see in the db the owner id.

**Comment by brunowego** [comment]
Have a way to set this environment is global?

**Comment by brunowego** [comment]
Sorry again. This is globally.
