### ISSUE TITLE
pip3 install -U polyaxon-cli

### ISSUE THREAD

**Issue by cyrilthank** [polyaxon/polyaxon#585]
### Describe the bug
 
after executing pip3 install -U polyaxon-cli 
polyaxon is not available

we still have to execute 
 
pip  install -U polyaxon-cli 

### To Reproduce

on ubuntu 18.04 LTS
pip3 install -U polyaxon-cli 
### Expected behavior
polyaxon executable to be available

**Comment by mouradmourafiq** [comment]
This will hopefully will be solved, in the next release.

**Comment by olivier-gillet** [comment]
Same for me.
Is the version 0.6.0 should fix this ?
