### ISSUE TITLE
polyaxon deploy fails on kubernetes 1.16.1

### ISSUE THREAD

**Issue by cyrilthank** [polyaxon/polyaxon#586]
### Describe the bug
 the command
polyaxon admin deploy -f config.yml

listed in https://docs.polyaxon.com/setup/kubernetes/

fails as below

polyaxon@polyaxon1:~$ polyaxon admin deploy -f config.yml
Running install command ...
Polyaxon could not be installed.
Error message ``helm` command ('helm', 'install', 'polyaxon/polyaxon', '--name=polyaxon', '--namespace=polyaxon', '-f', 'config.yml') failed with exit status 1
stdout:

stderr:
Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
`.

polyaxon@polyaxon1:~$ helm install polyaxon/polyaxon \
> --name=polyaxon \
> --namespace=polyaxon \
> -f config.yml
Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

### Expected behavior
successfully deploy polyaxon

### Environment
Ubuntu 18.05 LTS
kubernetes 1.16.1

**Comment by cyrilthank** [comment]
related issues

https://github.com/helm/helm/issues/6374#issuecomment-539978846
https://github.com/datawire/ambassador/issues/1848
https://github.com/helm/charts/issues/17511

Please provide workarounds

**Comment by mouradmourafiq** [comment]
What helm version are you using?

**Comment by cyrilthank** [comment]
![image](https://user-images.githubusercontent.com/4562436/67181078-284c3500-f3f9-11e9-9b15-f8a2b2ffd57f.png)

**Comment by mouradmourafiq** [comment]
This is issue was fixed in this [PR](https://github.com/polyaxon/polyaxon-chart/pull/51) thanks to @DXist.

Thank you for opening the issue, and sorry for the bad experience. Closing the issue for now.

**Comment by posix4e** [comment]
I just replicated this
```
posix4e@cloudshell:~$ polyaxon admin deploy -f config.yaml
Running install command ...
Polyaxon could not be installed.
Error message ``helm` command ('helm', 'install', 'polyaxon/polyaxon', '--name=polyaxon', '--namespace=polyaxon', '-f', 'config.yaml') failed with exit status 1
stdout:

stderr:
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
`.
posix4e@cloudshell:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by aruninnanje** [comment]
Even i get the same error 
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

error 
 polyaxon admin deploy -f polyaxon_config_persitance.yaml
Running install command ...
Polyaxon could not be installed.
Error message ``helm` command ('helm', 'install', 'polyaxon/polyaxon', '--name=polyaxon', '--namespace=polyaxon', '-f', 'polyaxon_config_persitance.yaml') failed with exit status 1
stdout:

stderr:
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
`.
