### ISSUE TITLE
 Is there some kind of schedule / roadmap?

### ISSUE THREAD

**Issue by djuelg** [polyaxon/polyaxon#590]
Is there some kind of schedule / roadmap?

I wondered, since there is no stable 1.X release, yet. Is there one coming soon?
What is currently missing, so that polyaxon is currently not considered stable?

Greetings,
Domi

**Comment by mouradmourafiq** [comment]
Hi, Polyaxon is already stable and running in production mode at several organizations, there's a [short term roadmap](https://docs.polyaxon.com/resources/roadmap/) on the docs website.
