### ISSUE TITLE
`polyaxon experiment resources` fails

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#596]
### Describe the bug
When running `polyaxon experiment resources` only `Session ended` is printed and an error is logged in the api pod: `Not Found: /api/v1/my-user/my-project/experiments/1234/resources/`

### To Reproduce
start an experiment, while it's running, run 
```
polyaxon experiment resources
```

### Expected behavior
Get info about resources instead of
`Session ended`

### Environment
```
$ polyaxon version

Current cli version: 0.5.6.


Supported cli versions:

--------------  -----
latest_version  0.5.6
min_version     0.5.0
--------------  -----
$ polyaxon version --platform

Current platform version: 0.5.6.


Supported platform versions:

--------------  -----
latest_version  0.5.6
min_version     0.5.0
--------------  -----
```

**Comment by mouradmourafiq** [comment]
Resources can be viewed in the dashboard:

<img width="1274" alt="Screenshot 2020-05-02 at 23 00 27" src="https://user-images.githubusercontent.com/1261626/80892104-c3876680-8cc8-11ea-8526-8a762306bbf6.png">


The cli command has been removed for now, there's an api for tailing the resources, but I am not sure if this command will come back anytime soon. I will tag it as a feature.
