### ISSUE TITLE
Unable to Deploy on Polyaxon with helm v2.16.0 (No kind Job is registered for version batch/v1)

### ISSUE THREAD

**Issue by TariqAHassan** [polyaxon/polyaxon#601]
### Describe the bug

Following the instructions [here](https://docs.polyaxon.com/setup/kubernetes/) I have been unable to deploy on google cloud using GKE. 

Unfortunately, the instructions provided [here](https://github.com/polyaxon/polyaxon/blob/master/docs/guides/polyaxon-gke-nfs.md) 
no longer appear to be valid because the link for `click-to-deploy single-node file server` is no longer working (not clear this service is still available).

### To Reproduce

1. Create a new cluster

```
$ gcloud beta container \
    --project "PROJECT-NAME-HERE" clusters create "polyaxon-test" \
    --zone "us-west1-a" \
    --username "admin" \
    --machine-type "n1-standard-2" \
    --image-type "COS" \
    --disk-size "10" \
    --num-nodes "3" \
    --network "default"
```

2. Follow the instructions provided [here](https://docs.polyaxon.com/setup/kubernetes/) up to `polyaxon admin deploy...`, which gives:

```
Polyaxon could not be installed.
Error message ``helm` command ('helm', 'install', 'polyaxon/polyaxon', '--name=polyaxon', '--namespace=polyaxon') failed with exit status 1
stdout:

stderr:
Error: no kind "Job" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

### Expected behavior

For Polyaxon to deploy.

### Environment

I have tried updating the client version of `kubectl` to the latest version and the server version to the latest version that google currently provides (`v1.14.8-gke.2`).

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.2", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-10-21T20:01:24Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Helm is the latest version (`v2.16.0` for client and server)

Please let me know if can provided any additional information.

**Comment by mouradmourafiq** [comment]
Hi, that's because the the distributed helm chart does not target support 1.16 yet. A fix has been already merged, and just need to be released.

You can try to deploy Polyaxon directly based on the master branch https://github.com/polyaxon/polyaxon-chart

A minor release will be pushed in the following days.

**Comment by TariqAHassan** [comment]
Thanks for the fast reply @mouradmourafiq.

Forgive the tedious question, but how would I go about deploying directly based on the master branch?

**Comment by mouradmourafiq** [comment]
It turned out that the error you mentioned is related to a helm [issue](https://github.com/helm/helm/issues/6894), downgrading to Helm 2.15.2 :
```
curl https://raw.githubusercontent.com/kubernetes/helm/v2.15.2/scripts/get | bash
```

You will then to update tiller, try : `helm init --force-upgrade` and check if the server version is updated otherwise, you need to run `helm reset`.

**Comment by TariqAHassan** [comment]
I had to specify `-v v2.15.2` in order to force a downgrade...but with that, it worked!

Thanks for all of your help!

**Comment by mouradmourafiq** [comment]
Great, I will close this issue and pin it as a reference for other people until the helm team fix the bug and release a new version.
