### ISSUE TITLE
restarting experiments - reproducibility

### ISSUE THREAD

**Issue by thomashossler** [polyaxon/polyaxon#604]
### Unclear documentation

I have been trying to reproduce unsuccessfully an old experiment. I have been following this post
https://medium.com/polyaxon/saving-resuming-and-restarting-experiments-with-polyaxon-7812b0450358

On my local machine, I run the following:
`polyaxon group -g 566 experiments`

and get:
```
Experiments for experiment group `566`.


Navigation:

-----  -
count  3
-----  -

Experiments:

  id  unique_name              user    build_job                  last_status    created_at    started_at    finished_at    total_run
----  -----------------------  ------  -------------------------  -------------  ------------  ------------  -------------  -----------
3342  thomas.skyfall.566.3342  thomas  thomas.skyfall.builds.873  failed         6 weeks ago   6 weeks ago   6 weeks ago    21h 3m
3341  thomas.skyfall.566.3341  thomas  thomas.skyfall.builds.873  failed         6 weeks ago   6 weeks ago   6 weeks ago    21h 3m
3340  thomas.skyfall.566.3340  thomas  thomas.skyfall.builds.873  failed         6 weeks ago   6 weeks ago   6 weeks ago    21h 3m

```

However, when I run:
`polyaxon experiment -xp 3340 restart --copy`
I get a build error:
`Could not download code to build the image.`

What am I doing wrong? On another note, what's the best way to get the version of the code I used to run that experiment? I am launching the experiment from my local machine directly (without pointing to a github repo). It would be nice to have a way to access the commit used for that particular experiment.

**Comment by mouradmourafiq** [comment]
`polyaxon experiment -xp 3340 code` should allow you to download the version of code used for that specific experiment.

I don't think this is a bug, because the issue could be how the code is stored, if the repos are stored on a  host node (default) then if the node is restarted all data is lost, please check: https://docs.polyaxon.com/configuration/custom-repos-storage/

**Comment by thomashossler** [comment]
I am getting the following when trying the `polyaxon experiment -xp 3340 code`.

```Error while downloading project repo.: None
Could not download outputs for experiment `3340`.
Error message `500 on http://3.80.182.94:31811/api/v1/thomas/skyfall/repo/download/.`.```

**Comment by thomashossler** [comment]
> `polyaxon experiment -xp 3340 code` should allow you to download the version of code used for that specific experiment.
> 
> I don't think this is a bug, because the issue could be how the code is stored, if the repos are stored on a host node (default) then if the node is restarted all data is lost, please check: https://docs.polyaxon.com/configuration/custom-repos-storage/

**Comment by thomashossler** [comment]
hey so I followed your link and started using a persistent volume for repos and logs (I was already doing it for outputs). The command to download the code works great on new experiments. I was just wondering if you could explain the folder structure. My code is saved at:
`/mnt/polyaxon/repos/thomas/skyfall/skyfall` and I am wondering why the path is not `<VOLUME>/<USER>/<PROJECT>/groups/<GROUP NUMBER>` like it for outputs or logs for example

**Comment by mouradmourafiq** [comment]
I am not sure, you should provide the deployment config (the repos config section) because it just follows the definition you provide.
