### ISSUE TITLE
Notebook deletion after stop

### ISSUE THREAD

**Issue by kontrabas380** [polyaxon/polyaxon#606]
Hello,

I couldn't find the solution online to my question/problem. After stopping the notebook on polyaxon (polyaxon notebook stop), the whole notebook is deleted and I can't go back to this version after starting it again. Is it normal or maybe configuration problem?

Greetings!

**Comment by mouradmourafiq** [comment]
> After stopping the notebook on polyaxon (polyaxon notebook stop), the whole notebook is delete
Yes, that expected behaviour.
> I can't go back to this version after starting it again.
Depending on your deployment config you can recover outputs and meta data, for code changes, it's currently a limitation in the notebook integration that we are changing to allow users to be able to commit the changes.

**Comment by kontrabas380** [comment]
> Depending on your deployment config you can recover outputs and meta data, for code changes, it's currently a limitation in the notebook integration that we are changing to allow users to be able to commit the changes.

Ok, I understand. So, how can I set my deployment config to recover code from notebook after I stopped it?

**Comment by mouradmourafiq** [comment]
This is handled in the default jupyter (notebook and hub) components in Polyaxon v1. All outputs will be synced to the artifacts store including the notebook itself and initialized if the notebook is resumed.
