### ISSUE TITLE
Outputs in sub-folder: web UI stuck in 'loading'

### ISSUE THREAD

**Issue by MatthiasKohl** [polyaxon/polyaxon#607]
### Describe the bug
Make an experiment which creates 1000s of output files in a sub-folder of the outputs path.
Go to experiment->outputs in the web UI. Click on the sub-folder. Web UI is stuck in 'loading' state.

Slightly different scenario: Create a sub-folder with a few files in it.
Go to experiment->outputs in the web UI. Click on the sub-folder. Click on 'Refresh'. Web UI is stuck in 'loading' state.

### Expected behavior
Either the UI should say that there are too many outputs to load or they are unavailable, or it should show them.

### Environment
Polyaxon 0.5.6 on Kubernetes 1.15.4

**Comment by mouradmourafiq** [comment]
Similar to #264, the state management, and this was fixed as a side effect of that change.
