### ISSUE TITLE
Download a selection of outputs (or just a sub-folder)

### ISSUE THREAD

**Issue by MatthiasKohl** [polyaxon/polyaxon#609]
### Feature motivation

Outputs could be very large (when saving many weights etc.). As of now, it seems like we can only download all outputs or single files.

### Feature description

Allow to download a selection of files/folders or at least a sub-folder instead of single files or everything only.

### Feature implementation

Unsure how the web UI is implemented but essentially just needs to allow selection of multiple outputs and a button to download them.

**Comment by mouradmourafiq** [comment]
Not sure when the new UI will be available to everyone, but this is Possible in v1 both using the APIs, Client, and UI.

![Screenshot 2020-03-20 at 12 03 29](https://user-images.githubusercontent.com/1261626/77158188-143d5a00-6aa3-11ea-84d0-c9bff586baa9.png)
