### ISSUE TITLE
Problem with big files

### ISSUE THREAD

**Issue by kontrabas380** [polyaxon/polyaxon#611]
Hello,

I want to do calculations on polyaxon and I have big csv file (~ 2GB) of data which I'm using in project. When I'm running my script on polyaxon (polyaxon run -u), it stops and shows the error:

> You are uploading 10.0MiB, there's a hard limit of 150.0MiB.
> If you have data files in the current directory, please make sure to add them to .polyaxonignore or add them directly to your data volume, or upload them separately using `polyaxon data` command and remove them from here.
> 
> Error while updating project repo.: Files too large to sync, please keep it under 150.0MiB.
> If you have data files in the current directory, please add them directly to your data volume, or upload them separately using `polyaxon data` command and remove them from here.

What is more, command "polyaxon data" is doing nothing. How can I upload this file to polyaxon in a different way or how can I change the limit of uploading files with this way?

Greetings!

**Comment by mouradmourafiq** [comment]
The value `POLYAXON_MAX_UPLOAD_SIZE` is set to `1024 * 1024 * 150` you can set an env var with the limit you wish to use.

**Comment by kontrabas380** [comment]
Thank you for your reply. But how can i change it? I tried with this:
https://docs.polyaxon.com/configuration/custom-run-environment/#environment-variables

But it still doesn't work.

**Comment by mouradmourafiq** [comment]
Sorry, that's a value that you should export in your local environment, the CLI does the check to alert users about large files, so basically `export POLYAXON_MAX_UPLOAD_SIZE=...`, the api allows up to 4GB of upload I think.

**Comment by kontrabas380** [comment]
Thank you for your reply, it kinda work, because I could upload and run experiment with csv file (about 300 mb). But I tried to do this with bigger csv file (2.2 GB) and I've got this error:

> You are uploading 10.0MiB, there's a hard limit of 2.3GiB.
> If you have data files in the current directory, please make sure to add them to .polyaxonignore or add them directly to your data volume, or upload them separately using `polyaxon data` command and remove them from here.
> 
> Request to xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx failed with status code 504. 
> Reason: 
> [================================] 1002446563/1002446563 - 00:12:54
> Error while updating project repo.: None
> Could not upload code for project `test-generator`.
> Error message `504 on xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.`.
> Check the project exists, and that you have access rights, this could happen as well when uploading large files. Please also make sure that you have enough space to upload the data.

Project exists and there is enough space. What can I do with this issue?

**Comment by kontrabas380** [comment]
@mouradmourafiq, do you have any solutions?

**Comment by mouradmourafiq** [comment]
You need to provide more info about your deployment, it's seems like nginx should be customized as it seems to timeout.
I also do not think that uploading data through Polyaxon is an expected workflow, you should normally have your data either on a volume or blob storage.

Can you provide more information about your deployment config ?

**Comment by hollowgalaxy** [comment]
It wouldn't make sense for the data to be on blob storage, because if its big, you would not want to download it on every experiment.

What does `polyaxon data` do? Don't see any documentation on it.

**Comment by mouradmourafiq** [comment]
> It wouldn't make sense for the data to be on blob storage, because if its big, you would not want to download it on every experiment.

Uploading an experiment on every experiment does not make sense either. If the data is large enough, you need to download it one time to a mount storage, and have your experiments just access to it.

`polyaxon data` will be removed, in v1.x there's a notion of initializers that users can use to auto-download data, but for use-cases where data is large, it definitely makes sense to have it cached wither on node level / or on network level.

**Comment by hollowgalaxy** [comment]
For mount storage, are you referring to nfs? Or is there a better approach?

**Comment by mouradmourafiq** [comment]
Well you can mount data to a specific node, and have all experiments scheduled on that node, or you can use some system like NFS, GlusterFS, Minio, ... to access the data shared between multiple nodes. Unfortuntely  it's very hard to give advice about the best solution, some companies are using paid tools to optimize data access for specific hardware or accelerators. But uploading data through Polyaxon (which is not an optimized for that type of workload, let alone to which node) is not an ideal solution.
