### ISSUE TITLE
Run polyaxon locally - resource allocations & other

### ISSUE THREAD

**Issue by thomashossler** [polyaxon/polyaxon#615]
I am trying to get my experiments to run locally with the new `--local` flag. I was facing two problems:
- mounting volumes: The default mounted volume is `/tmp/.polaxyon`. I solved that one by updating the polyaxon-cli and adding this to my yaml file:
```
environment:
  data_refs: ['/folder1:/folder2']
```
Not sure if this the way to go?

- parameters: the documentation says we can run the command with updated params, for example: `polyaxon run -p project1 -f file.yaml -P param1=234.2 -P param2=relu`. I tried updating my learning rate by doing: `polyaxon run -f configs/polyaxon/faster_rcnn.yml --local -P lr=0.1` and get the following:
```
Polyaxonfile is not valid.
Error message `{'_schema': ['You should only use `params`.']}`.
```
It works with this example though https://docs.polyaxon.com/concepts/experiments/. Does it mean I can override `inputs` but not `declarations`? 

- resources allocation: my yaml file looks like this but this does not run docker with gpu. I am wondering how I can get it to work? My current hack is to add an extra argument `--gpus 0` in `polyaxon-cli/run/docker.py`.

```
environment:
  data_refs: ['/folder1:/folder2']
  resources:
    gpu:
      requests: 1
      limits: 1
```

**Comment by mouradmourafiq** [comment]
> resources allocation

Local run is just for test purposes, it's not supposed to have feature parity with k8s.

> You should only use `params`.

Declaration is deprecated, and when params and declarations are used at the same time, an error is raised.

**Comment by thomashossler** [comment]
Ok but how do I test my pipeline if I cannot allocate resources like gpu or memory?

**Comment by mouradmourafiq** [comment]
Closing this issue as wontfix, local support is very limited and will not have feature parity with k8s.
