### ISSUE TITLE
Slack link is not active anymore

### ISSUE THREAD

**Issue by wsxiaoys** [polyaxon/polyaxon#617]
### Describe the bug
Slack link is not active anymore.

**Comment by mouradmourafiq** [comment]
Hi @wsxiaoys what slack link is not working anymore?

**Comment by wsxiaoys** [comment]
The join link listed on github.com/polyaxon/polyaxon:

https://join.slack.com/t/polyaxon/shared_invite/enQtMzQ0ODc2MDg1ODc0LWY2ZTdkMTNmZjBlZmRmNjQxYmYwMTBiMDZiMWJhODI2ZTk0MDU4Mjg5YzA5M2NhYzc5ZjhiMjczMDllYmQ2MDg

"This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available."

**Comment by mouradmourafiq** [comment]
Thanks for letting me know, it's fixed 👍

**Comment by AGKhalil** [comment]
I think the link is no longer active. Could you please post a working one?

**Comment by mouradmourafiq** [comment]
The one on github and the documentation page are working, can you share the page where the link was not working?

**Comment by AGKhalil** [comment]
https://docs.polyaxon.com/concepts/introduction/

**Comment by AGKhalil** [comment]
https://github.com/polyaxon/polyaxon/blob/c8a19ff7246791333806f71e31e2b46b0d3a3787/docs/concepts/contributing.md

**Comment by mouradmourafiq** [comment]
I see, thank you, the footer has a link, as well as the banner on the docs pages, the repo readme has an updated link also.
