### ISSUE TITLE
Build without uploading code is failed

### ISSUE THREAD

**Issue by bestksw** [polyaxon/polyaxon#621]
### Describe the bug
Build failed with
`Could not download code to build the image.`
with no uploaded code.

### To Reproduce
From clean project, run build or others without uploading code.

### Expected behavior
Run build successfully even if there's no code in the internal repo of polyaxon.
I don't want upload code anything. I just want to run yml file only without any code. My code is already built in Docker Image.

### Environment
Polyaxon 2.2.4-rc23 in rancher2 with own cluster.

**Comment by mouradmourafiq** [comment]
I agree and it's already the case for the upcoming version of Polyaxon, i.e. build are not required.
