### ISSUE TITLE
logs streaming maxes out at  a few messages per second

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#623]
### Describe the bug
I like the feature of streaming logs to a terminal e.g. with `polyaxon build -b 555 logs` however when the job is already running some time it may take minutes until the streaming process caught up with the most recent messages as it seems to print only ~ 10 messages per second

### Expected behavior
print past messages within 1-3 seconds, continue streaming new messages as they are generated inside the job

### Environment
ployaxon 0.5.6 both server and cli

**Comment by mouradmourafiq** [comment]
Logs handling have been changed in the upcoming version, the new behaviour will have a rotation interval for collecting logs to files directly, the logs collected during a rotation will be streamed(cli/ui), no throttling of messages will occur, though, the stream will have a sleep interval of minimum period, e.g. 3 seconds. This behaviour will also solve slow api calls for fetching logs for long running jobs.

**Comment by Mofef** [comment]
@mouradmourafiq I didnt check 0.6 yet, but is this resolved yet?

**Comment by mouradmourafiq** [comment]
No, v0.6 has only some small bug fixes and an update of packages with security issues. Unfortunately this one is a big feature. I would like to leave v0 stable and long term supported by minor fixes and security fixes only. So this is something on v1 only.
