### ISSUE TITLE
Incorrect sorting of a metric

### ISSUE THREAD

**Issue by bestksw** [polyaxon/polyaxon#628]
### Describe the bug
Similair issue #509
It works when I use log_metrics('key', 'value') without space, but if I insert space like log_metrics('key 1', 'value') it doesn't work correctly.

### To Reproduce
Run your experiment group with below code.
```
>>> import random
>>> from polyaxon_client.tracking import Experiment
>>> plx_exp = Experiment()
>>> plx_exp.log_metrics('key', random.randint(1,1000))  # Sorting works in web interface
>>> plx_exp.log_metrics('key 1', random.randint(1,1000))  # Sorting doen't work in web interface
```
then, try to sort with 'key' or 'key 1' in web interface or console.

### Expected behavior
Mube be sorted in ascent/descent order correctly in web interface and console.

### Environment
v0.5.6 in Rancher 2 with own cluster.

**Comment by mouradmourafiq** [comment]
I think we need to slugify the keys to make sure the db sorting work.

Just as a general rule, spaces are not supported .

**Comment by mouradmourafiq** [comment]
All events are converted to fully qualified names, in the case of space like the example `'key 1'` a dash will  be used `'key-1'`.
