### ISSUE TITLE
Azure Single Sign On (SSO) error

### ISSUE THREAD

**Issue by axelperschmann** [polyaxon/polyaxon#631]
### Describe the bug
Microsoft Azure Single Sign On fails with `Invalid Request`

### To Reproduce

- Via **Polyaxon Dashboard** -> Settings -> add Azure Auth information
- Log Out
- Log In with Microsoft
- Observe the following error: 

```
AADSTS165000: Invalid Request: The request tokens do not match the user context. Do not copy the user context values (cookies; form fields; headers) between different requests or user sessions; always maintain the ALL of the supplied values across a complete single user flow. Failure Reasons:[Token values do not match;]
```

### Expected behavior
Login should work

**Comment by mouradmourafiq** [comment]
Closing as wontfix. A much better interface will be exposed for open source users to use their own user management system
