### ISSUE TITLE
Tensorboard filter tags are reset/synced when multiple tensorboard instances are running

### ISSUE THREAD

**Issue by yigitsoy** [polyaxon/polyaxon#636]
### Describe the bug
When multiple tensorboard instances are running under the same or different projects, updating/modifying filter tags of one of tensorboard leads to the same change in all other tensorboard instances.

If a new tensorboard is started, this causes a reset in the filter tags of all other running tensorboard instances.

### To Reproduce
Start a tensorboard (TB1) for experiment or group either using the Polyaxon Web UI or CLI. Apply some filter tags. Start another tensorboard (TB2) for another experiment or group from the same or another project. Filter tags of TB1 should be reset. 

Now, apply some filter tags in one of the tensorboards. The same filter tags should appear in the other one.

### Expected behavior
Different instances of tensorboards, regardless of the same or of different projects, should have independent states.

### Environment
Polyaxon version: 0.5.6
Google Chrome: 79.0.3945.79 (Official Build) (64-bit) (cohort: 79_Win_79)
OS: Windows 10 OS Version 1709 (Build 16299.1481)
JavaScript: V8 7.9.317.31
Flash: 32.0.0.303 
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Comment by mouradmourafiq** [comment]
I assume you are using NFS as an output storage backend?

**Comment by yigitsoy** [comment]
Yes, that is right.

**Comment by mouradmourafiq** [comment]
Can you confirm if this behaviour happens also when you start an individual tensorboard for 2 different experiments without groups, e.g. TB1 -> EXP1 and TB2 -> EXP2.

**Comment by yigitsoy** [comment]
Just tested. Yes, the behavior is the same.

**Comment by polyaxon-team** [comment]
Feel free to reopen if this happens in the latest version.
