### ISSUE TITLE
Private repo path

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon#639]
### Unclear documentation
There is a command to link the private repo. But no documentation on how to use the linked repo. 
1.Where is the working directory?
2.How to specify path to Dockerfile? (I was using the cli for this)

https://docs.polyaxon.com/concepts/quick-start-external-repo/

**Comment by mouradmourafiq** [comment]
1. By running experiments, Polyaxon will pull by default latest commit unless you specify the commit to use, [docs for using commit/branch](https://docs.polyaxon.com/references/polyaxonfile-yaml-specification/build/#example-using-commit)
2. You either use the build section or provide a path to the dockerfile, from the docs [1](https://docs.polyaxon.com/references/polyaxonfile-yaml-specification/build/#example-using-a-dockerfile), [2](https://docs.polyaxon.com/references/polyaxonfile-yaml-specification/build/#example-using-a-dockerfile-and-a-context)

**Comment by hollowgalaxy** [comment]
I figured it out  some time ago, but forgot about this question. I meant that when you are using your Dockerfile ( in your private repo, to specify the path unto which your repo is pulled you do `ADD build /code`
This is a small detail that I noticed only when looking at the example Dockerfiles, however I think this should be part of the documentation as well.

**Comment by mouradmourafiq** [comment]
@hollowgalaxy several non-optimal design decisions have been improved from in v1.x, the user will have full control where to mount the code, dockerfiles, data, and even the generated the dockerfile like (build section).

**Comment by hollowgalaxy** [comment]
Any timeline for these changes?

**Comment by mouradmourafiq** [comment]
it's hard to give a definite timeline, there are some other priorities, but we are really pushing to get an open source release very soon.
