### ISSUE TITLE
Specify project for upload via -p/--project

### ISSUE THREAD

**Issue by Anton-Velikodnyy** [polyaxon/polyaxon#640]
### Feature motivation
[switching-context](https://docs.polyaxon.com/references/polyaxon-cli/#switching-context) page in the documentation says that all commands can use -p or --project to specify project. Not true at all. `polyaxon upload` throws error when using -p option. 

### Feature description

adding -p/--project to upload command

**Comment by mouradmourafiq** [comment]
Upload is the only exception, if you check the `docs` or the `--help` flag, you will see if a command uses the cache mechanism (`Uses [Caching](/references/polyaxon-cli/#caching)`)

Upload cannot support context switching because it requires a specific project to be initialized, and it depends on the `.polyaxonignore`

Closing the issue.

**Comment by hollowgalaxy** [comment]
What if you want to maintain 2 different projects with same code? Like a debug project for testing and a main project that's has only clean experiments?

**Comment by mouradmourafiq** [comment]
that's a good question, and something that I have been thinking about as well, the `.polyaxon` configs folder should probably not live inside the code at all, and probably should be centralized to handle the remote code (e.g. github). Maybe only the `.polyaxonignore` file should be in the code repo.

**Comment by joeyearsley** [comment]
Running into this issue with a codebase like https://github.com/facebookresearch/detectron2.

Wish to upload the entire library but have different sub-projects.

**Comment by mouradmourafiq** [comment]
Pushing hard to make an open-source release for the new Polyaxon soon, but I will give a bit information about how users can structure their using the new version:

 * It's possible to use multiple git project in a single run
 * It's possible to manipulate the path where the projects will be cloned
 * Build process is optional, users can create a base image for requirements, and clone the code on the fly before the run process.

I assume that the new spec will allow to fix most of these issues, I will label this issue as in v1 as well.
