### ISSUE TITLE
How to define ENV_VARS in the setting page?

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#645]
### Unclear documentation
https://docs.polyaxon.com/configuration/custom-run-environment/#env-vars
> In order to set the default environment variables, you can update the ENV_VARS in the setting page for every primitive.

It is not clear in what format the environmentvariables should be defined. 

When entering sth. like `{'key': 'val'}` the form validator complains with 
_Env vars configuration for build jobs
Cannot convert value `{'key': 'val'}` (key: `ENV_VARS:BUILD_JOBS`) to `<class 'list'>`_

When entering `[['key', 'val']]` (like it works in the polyaxonfiles) the input gets converted to a string i.e. `"[['key', 'val']]"`.
That seems to have no effect as a build step like `echo "key = $key"` just prints `key =`

So what would be the right format?

**Comment by mouradmourafiq** [comment]
This looks like a bug, by the way the env section has been converted to dict, it will lose some validation, but it's less confusing.

As for why the env vars are not injected, I am not completely sure, maybe it's still in the cache? do you still see the same behaviour after a couple of minutes of setting those values.

In any case I would suggest to have them on the polyaxonfiles for now.

**Comment by Mofef** [comment]
Usually such changes were applied within seconds, In this case I was testing for at least 30 minutes until I gave up on it. So after 30 minutes the change was apparently still not applied...?
