### ISSUE TITLE
Refreshing webpage removes added columns

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#648]
### Describe the bug
I don't know whether it is desired behavior, but refreshing a webpage (in the browser's F5 shortcut or manually) removes all previously added columns in experiment view.

### To Reproduce

1. Open a view with group of experiments.
2. Add a column with your parameters / metrics to a table.
3. Refresh the webpage (F5).

### Expected behavior
All the columns should stay added. 

### Environment
* Mozilla Firefox 71.0
* Ubuntu 18.04
* Polyaxon 0.5.6

**Comment by mouradmourafiq** [comment]
This is related to  #213

**Comment by mateuszpieniak** [comment]
Thanks.
