### ISSUE TITLE
Sorting experiments in descending order

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#649]
### Describe the bug
I would like to take a look at the temporarily best validation score. 

Let's assume. I scheduled N experiments in the HP tuning. There are finished M experiments, where M is lower than N. Sorting experiments by metric in ascending order works well, but descending order prefers experiments with `Created` status. 

![image](https://user-images.githubusercontent.com/31375424/71995855-855ac880-323b-11ea-87e3-b38407b7701a.png)

### To Reproduce
1. Schedule N experiments in HP search.
2. Wait until M experiments are finished, but N << M.
3. Add any column to the table in the experiments view.
4. Sort values by any column in the descending column.

### Expected behavior
All experiments that haven't been run should be pushed down.

### Environment
* Mozilla Firefox 71.0
* Ubuntu 18.04
* Polyaxon 0.5.6

**Comment by mouradmourafiq** [comment]
There's probably a default order by at code/db level, it should be removed then.

**Comment by mateuszpieniak** [comment]
Well, I just noticed that I can solve it by filtering out experiments using `Succeded` status in `Searches button`, but it's not very convenient.

**Comment by mouradmourafiq** [comment]
Closing this issue, a fix will be part of the next patch release.
