### ISSUE TITLE
Propagate group experiment description and tags to its children

### ISSUE THREAD

**Issue by leonoverweel** [polyaxon/polyaxon#654]
### Feature motivation

When viewing the overall list of experiments for a project, experiments spawned by a group experiment are included. However, these experiments have no description or tags, even if the parent experiment group did. This makes it hard to search for experiments from groups in the overview, for example when searching for all experiments tagged with a certain dataset or model name.

### Feature description

Adding functionality to automatically add the tags and description of an experiment group to all the experiments it spawns.

### Feature implementation

I'm not familiar enough with the Polyaxon codebase to provide much useful input here.

**Comment by mouradmourafiq** [comment]
This is the behavior in the v1.x, tags, description, and other metadata are propagated to children runs in parallel mode, unfortunetely this will be implemented in v0.x.

I will keep the issue open as a reference, until v1.x is GA to everyone.
