### ISSUE TITLE
polyaxon installation fail:  unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1

### ISSUE THREAD

**Issue by aruninnanje** [polyaxon/polyaxon#656]
### Describe the bug
Related to polyaxon deploy fails on kubernetes 1.16.1 #586

### To Reproduce

kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
arun@uiiusls04:/mnt/homes/arun/polyaxon/polyaxon$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}

helm repo add polyaxon https://charts.polyaxon.com
helm repo update
polyaxon admin deploy -f polyaxon_config_persitance.yaml
Polyaxon could not be installed.
Error message ``helm` command ('helm', 'install', 'polyaxon/polyaxon', '--name=polyaxon', '--namespace=polyaxon', '-f', 'polyaxon_config_persitance.yaml') failed with exit status 1
stdout:

stderr:
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
`.

**Comment by mouradmourafiq** [comment]
I assume you are trying to deploy polyaxon on 1.16 or 1.17 k8s cluster. You need o disable the built-in postgresql and provide your own (either on a cloud provider or by deploying an official helm chart). The built-in postgresql chart is not yet compatible with k8s 1.16. Please check this [section of the docs](https://docs.polyaxon.com/configuration/postgresql-ha/#external-postgresql) to configure an already running postgres service.

**Comment by aruninnanje** [comment]
Thanks @mouradmourafiq . I'll try this. Appreciate your help!
