### ISSUE TITLE
Updating histogram doesn't work 

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#660]
### Describe the bug
I cannot update the histogram on the saved viewed for group of experiments.

### To Reproduce
1. Create a group of experiments.
2. Go to `Metrics` tab and create a view with multiple histograms.
3. Save the view.
4. Try updating one of the histograms by switching the y-axis (different variable).

Nothing happens. I don't know whether it's related to a save view or current view.

### Expected behavior
The plot updates.

### Environment
* Mozilla Firefox 71.0
* Ubuntu 18.04
* Polyaxon 0.5.6

**Comment by mouradmourafiq** [comment]
I am closing this as it does not appear to happen in the new UI, so I assume that it's a bug in the previous version that was solved.
