### ISSUE TITLE
Share saved metric view across experiments

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#661]
### Feature motivation
I would like to easily compare charts across experiments within the same experimental group. 

During training, I add multiple of metrics. Some of them are not really related to my task but are worth adding for debugging purposes. Another metric I add is `metric:best_validation_score`, because then I can easily sort experiments by the best score for example while hyperparameter tuning. Polyaxon automatically creates a chart for it. I would like to filter them out & save the view so it's reusable.

### Feature description
Saved views in the `Metrics` tab should be available across experiments at least in the same experimental group.

**Comment by mouradmourafiq** [comment]
Closing this one as this is the new default behaviour, dashboard are are created on project level and can be promoted to org level, both for experiment and for multi-experiments.

![Screenshot 2020-04-07 at 21 20 56](https://user-images.githubusercontent.com/1261626/78710506-bc617880-7915-11ea-8bc2-6b4f2b8e356e.png)
