### ISSUE TITLE
Allow to compare train / validation learning curves

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#662]
### Feature motivation
A classical ML approach is to overlay the train & validation curve on the same plot. As far as I know, Polyaxon doesn't support it know.

### Feature description
Allow creating line plot with multiple values on the y-axis.

**Comment by mouradmourafiq** [comment]
I think it's possible to add several metrics/lines to the same plot.

**Comment by mateuszpieniak** [comment]
It is from UI, but is it possible to do it from Tracking API? I would like to have preconfigured "charts views" across experiments for same / different experiment group.
