### ISSUE TITLE
Real-time chart updates with new experiments finished

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#663]
### Feature motivation
I created some view of the group of experiments. Some of the experiments were still running. 
Since I didn't specify, which experiments I am interested in, I expected that it takes them all. I saved the view. It seems like the list of experiments is saved in the view. In other words, when new experiments were finished, then the view wasn't updated.

I don't know how it works for learning curves. They are updated in real-time, but what does happen if I save an unfinished view?

### Feature description
Allow real-time updates for the created view in `Metrics` tab for a group of experiments.

**Comment by mateuszpieniak** [comment]
I am a bit confused because it seems like it works, but with some lag. I am 100% that were some not updated experiments. I added some new charts and noticed that there is something missing in the old ones. I refreshed a page, clicked "Refresh" button, but it didn't refresh it. A few seconds ago I went again to the `Metrics` tab & old charts were updated.

**Comment by mouradmourafiq** [comment]
It depends on how many experiments are running at the same time, how many metrics are sent at the same time (from different experiments), the concurrency (num of workers) of the scheduler are running. Metrics collection is done asynchronously, and in the experiments the metrics are batched in a background thread before being sent, so you might see a delay based on one or many factors.
