### ISSUE TITLE
Download results from experiment group

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#664]
### Feature motivation

I would like to download/obtain the results from training to make further conclusions. There is a CLI command:
```
polyaxon group -g 147 experiments --params --metrics
```
but:
1) `--params` and `--metrics` cannot be used simultaneously
2) I cannot select the columns I need
3) It has weird navigation CLI like `--page=2` i.e. it doesn't show all the content at once.

### Feature description
Extend CLI to download results as CSV or make a button in the created view. It will allow users to manually read data and create plots that Polyaxon doesn't handle now.

**Comment by mateuszpieniak** [comment]
@mouradmourafiq Any update on such a feature? I have around 600 experiments in the group (different folds, different datasets), therefore currently I cannot easily compare hyperparameters unless I manually copy-paste all of them into Excel.

**Comment by mouradmourafiq** [comment]
No progress on this yet, but as a workaround you can probably use the api to fetch the data related to an experiment group, it will include the params and metrics of all experiments under the group, you can then transform that into a datarame.

**Comment by mateuszpieniak** [comment]
@mouradmourafiq Thanks for the tip. I wrote a small script that goes through all pages of results and dumps a CSV.

**Comment by mouradmourafiq** [comment]
Great, ideally this should be either on the UI or a simple CLI command.

**Comment by OodapowUiPath** [comment]
@mouradmourafiq this issue seems to be almost the same as #175 ; you could also find an example script on that issue

**Comment by mouradmourafiq** [comment]
Closing this issue, a new flag was introduced in v1.1.8 `--to-csv`.
