### ISSUE TITLE
Cannot add an experiment to the group

### ISSUE THREAD

**Issue by mateuszpieniak** [polyaxon/polyaxon#665]
### Describe the bug
I cannot add a running experiment to a group with `Done` status.

### To Reproduce
1. Create an experiment group from YAML file. Write down its ID.
2. Wait until it is finished.
3. Run a separate experiment outside the group.
4. Select the running experiment in the experiment lists.
5. Click `Add to selection`, then type the written down group ID.

Nothing happens.

### Expected behavior
The experiment is added to the group.

### Environment
* Mozilla Firefox 71.0
* Ubuntu 18.04
* Polyaxon 0.5.6

**Comment by mouradmourafiq** [comment]
Selection are logical groups, you cannot add an experiment to an already done or running hyper-tuning group (at least not from the UI). However you can create a selection with all the experiments in the group + the experiments you want to add. This is not ideal, but the behaviour has already changed anyways.

**Comment by mouradmourafiq** [comment]
Closing this issue, an answer can be found in here #559 since a similar request.
