### ISSUE TITLE
Import/Export polyaxon configuration

### ISSUE THREAD

**Issue by Mofef** [polyaxon/polyaxon#671]
### Feature motivation

Exporting the settings would allow the configuration to be managed with a VCS. It would also allow  the configuration of polyaxon to be moved or copied to another cluster
Prior to 0.5 that was possible as configuration was done by overriding configuration values of the helm chart

### Feature description

For admin users there should be a commandline function (or webUI button or both) to download the current configuration from polyaxon as a yaml file and to upload such a file to set the configuration of polyaxon. I assume it makes sense to also include the settings under "Stores"

**Comment by mouradmourafiq** [comment]
Yes that was a big mistake, for the open source version of Polyaxon, configurations will revert to using yaml.

**Comment by Mofef** [comment]
Well, it was nice that one didn't need to do a helm upgrade to change the config. So that was nice!
But the current implementation has this limitation that the config is not avaialbele as code anymore. :/

**Comment by mouradmourafiq** [comment]
This one should have been closed in #690
