### ISSUE TITLE
Notebook always goes to "failed" 

### ISSUE THREAD

**Issue by vaskokj** [polyaxon/polyaxon#674]
In the UI

I created a project and then went to create a notebook by doing "Start Notebook" under the "+New" option. 

In the Docker Image I gave it:

`python:3`

In the build Steps I gave it:

`pip3 install tensorflow`

I give it a name and then it will start to make the image and then a few moments later after I refresh it will state "Failed" with no other information. 

What am I doing wrong?

**Comment by mouradmourafiq** [comment]
what does fail the notebook or the build?

**Comment by vaskokj** [comment]
@mouradmourafiq 

I assume in the build phase. This is what I see.

![image](https://user-images.githubusercontent.com/59578/74045490-79753a00-4992-11ea-9c76-91fbe8bfbcb2.png)

**Comment by mouradmourafiq** [comment]
Can you check the build tab for more details, why the builds are failing?

**Comment by vaskokj** [comment]
This is all it shows.

![image](https://user-images.githubusercontent.com/59578/74062301-940bdb00-49b3-11ea-9a6f-595ad58c074a.png)

![image](https://user-images.githubusercontent.com/59578/74062324-a259f700-49b3-11ea-9e97-d57921539901.png)

**Comment by mouradmourafiq** [comment]
What k8s version are you running?

**Comment by vaskokj** [comment]
@mouradmourafiq 1.15.3

kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mouradmourafiq** [comment]
are you still having the same issue?

Can share your deployment configuration as well as how many nodes on your cluster?

**Comment by vaskokj** [comment]
@mouradmourafiq 

I am. I couldn't figure out why this was happening before I got pulled off to something else. There is only 1 node in my test cluster. Has there been a release since I opened this ticket? If so I'll try deploying it again with the new release and see if it happens again.

**Comment by mouradmourafiq** [comment]
A new release is coming today which brings support for k8s 1.17, but I doubt that your issue is related to something else.

In that case, I will close this issue, if you redeploy and encounter the same problem feel free to reopen.
