### ISSUE TITLE
Copy experiment via UI

### ISSUE THREAD

**Issue by DXist** [polyaxon/polyaxon#681]
### Feature motivation
There is no UI analog for CLI command `polyaxon-cli restart --copy ...`

### Feature description
Add option to do copy restart of selected experiment in Polyaxon UI.

### Feature implementation

Dropdown list with experiment actions can be extended with `Restart & Copy outputs` option.

**Comment by mouradmourafiq** [comment]
A new modal form has been added to pass override config and a switch to enable the copy mode.
