### ISSUE TITLE
Add Column not persistant

### ISSUE THREAD

**Issue by waltsims** [polyaxon/polyaxon#682]
### Feature motivation

It would be great if adding a column to the experiment list of a project in the web interface would be a mutable persistent view of that project for either:
1.  that web session or 
1. the life of the project. 

### Feature description

see above.

### Feature implementation

Nothing concrete. Perhaps via cookie or an entry in the project database? Both have their challenges I guess.

**Comment by mouradmourafiq** [comment]
Similar to #716 and should be implemented in the same PR I guess.
