### ISSUE TITLE
Erroneous GET request for `#` in directory name

### ISSUE THREAD

**Issue by waltsims** [polyaxon/polyaxon#683]
### Describe the bug
If an experiment creates a output sub-directory with a name that includes a `#`, the subsequent GET request from the client to the API is cut at the char before the # and the client only sees the status "Loading"

### To Reproduce

Full Output Directory path:  `/api/v1/user/project/experiments/123/outputs/dirname_#3/`

clicking on the subdirectory `dirname_#3` the contents of the directory is not resolved and the status "loading..." is perpetually shown.

polyaxon-api logs show:
```
WARNING 2020-02-27 16:57:07,908 log 5299 140424238085888 Bad Request: /api/v1/user/project/experiments/123/outputs/tree
[pid: 5299|app: 0|req: 250579/1002796] 10.244.0.0 () {54 vars in 1265 bytes} [Thu Feb 27 16:57:07 2020] GET /api/v1/user/project/experiments/123/outputs/tree?path=dirname_ => generated 65 bytes in 36 msecs (HTTP/1.1 400) 5 headers in 150 bytes
```
### Expected behavior
I would expect to be able to resolve all directory names that can be used in linux
### Environment
Polyaxon v0.6.0

**Comment by mouradmourafiq** [comment]
Paths are passed as query params in v1, so I assume it won't have this issue.
