### ISSUE TITLE
polyaxon api pod never starts.

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon#692]
### Describe the bug
Polyaxon api pod stuck restarting, extremely high restart count.
Here is the logs

![image](https://user-images.githubusercontent.com/30283914/76714327-a5977f80-66e3-11ea-8021-44a3f1b08bfa.png)

Here are the pod events
![image](https://user-images.githubusercontent.com/52365584/76714881-d331f800-66e6-11ea-8157-14bef8c3ef23.png)

### To Reproduce
Not sure, however error has occured twice now. One suspect is cluster resources get filled, api crashes and restarts, and can never recover (even if resources are now available).

### Expected behavior
polyaxon api pod should not be failing.
### Environment
GCP
nothing special, only adding secret and mount, which works (when the polyaxon api was not failing)

**Comment by mouradmourafiq** [comment]
Can you check that your database instance is working?

**Comment by hollowgalaxy** [comment]
Re-installation of polyaxon on the cluster made the issue go away. Will reopen if it appears.
