### ISSUE TITLE
Consider Computer Vision Annotation Tool (CVAT) integration

### ISSUE THREAD

**Issue by AntonFriberg** [polyaxon/polyaxon#693]
### Feature motivation

Many companies are currently evaluating different machine learning platforms and one alternative to polyaxon that I have heard mentioned is https://www.onepanel.io/ which is a proprietary solution. A major selling point that I have heard in comparison with Polyaxon is that it has direct integration with CVAT which provides interactive video and image annotation tooling for computer vision tasks.
https://github.com/opencv/cvat#computer-vision-annotation-tool-cvat

### Feature description

It would be great to see similar levels of integration to onepanels offering: 
https://www.onepanel.io/video-image-annotation-workflow

But simply providing the ability to link to a CVAT deployment and share for instance access rights and deployment configuration would be a major benefit.

### Feature implementation

CVATs architecture is underneath very similar to Polyaxon in that its backend is Django with data in Postgres and redis and a seperate Frontend. No doubt that an integration would be a lot of work but it could provide a lot of additional value as well.

CVATs license seems to be MIT which is another major enabler https://github.com/opencv/cvat/blob/develop/LICENSE

**Comment by mouradmourafiq** [comment]
@AntonFriberg Thank you for opening this issue, I can see how beneficial an integration with such a tool could be, but bundling a stateful deployment with several dependencies into Polyaxon, will make it very hard to deploy correctly.

I think any team that wants to use this tool or other tools should be able to do so with Polyaxon using the apis or the polyaxonfile instead.

I will close this as wontfix.
