### ISSUE TITLE
When sidecar container is failed and job container is completed job is considered failed

### ISSUE THREAD

**Issue by DXist** [polyaxon/polyaxon#695]
### Describe the bug
During running an experiment job sidecar container failed to connect to Polyaxon API server and experiment job is finished with status FAILED and detail message 'Completed'.

Polyaxon API was down for quite long time because only single instance of API server was deployed to single Kubernetes master node and this node was rebooted.

### To Reproduce

Sidecar container should fail when job is running. Job should finish successfuly.

### Expected behavior
1. Successfully finished job container should represent success of job/experiment.
Currently it's not true if sidecar container is failed for some reason. [Example logs](http://ix.io/2eKl) of failed sidecar container.

2. Sidecar container should tolerate longer down periods of Polyaxon API 
### Environment
Polyaxon 0.6.1

**Comment by mouradmourafiq** [comment]
Already in v1
 * Sidecar just retries and then stops, [see](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/cli/components/sidecar.py#L58)
 * Users have more control over the sidecar container
 * the sidecar will be disabled if the functionality it provides is not used in the job (i.e. automatic collection of artifacts, ...)

**Comment by DXist** [comment]
@mouradmourafiq thank you for prompt reply!

**Comment by mouradmourafiq** [comment]
Another thing that I missed to mention, I will add it as comment for future references:

 * Logs of Polyaxon's sidecar, and any sidecar injected by the user, can also be streamed and stored, this will make it easier to debug (currently, the user has to check the k8s pod which is not convenient for a data scientist), more details about logs in this thread #569.

**Comment by DXist** [comment]
@mouradmourafiq Cool! Thank you for the link!
