### ISSUE TITLE
Option to provide data persistence volume dedicated to each user/project?

### ISSUE THREAD

**Issue by yoshihikoueno** [polyaxon/polyaxon#696]
### Feature motivation

It would be safer and more secure if a user can access only the data belong to itself. Someone may accidentally overwrite or delete someone else's data on a persistence volume during an experiment. With the current implementation, there's basically no way to prevent this kind of incident.
For this reason, I want to have a way to somehow separate the accessible data depending on user or project.

### Feature description

Since multiple users might be assigned to a project, where everyone in a project should be able to access the same data, it would make more sense to give project-dedicated data.

### Feature implementation
Ways I can think of to achieve this scope separation are:

- have dedicated pvc for each project
- have a single pvc just like the current implementation, but create a directory dedicated to a project. Then when running a docker container, it should be possible to mount this directory in the container environment.

For me, the second one seems to be more realistic and easier to implement.
 
Thank you.

**Comment by mouradmourafiq** [comment]
The features requested are already implemented in the commercial version. Namespacing, isolation, RBAC, ACLs are not part of the open source version.

For the open source, you can have multiple PVCs/blob storages, but the users will have to organize themselves in terms of access or you need to build on top of Polyaxon to provide the functionality yourself.

Thank you for opening this issue, I will close as wontfix
