### ISSUE TITLE
Job Lifecycle

### ISSUE THREAD

**Issue by compete369** [polyaxon/polyaxon#697]
I am reading the code and document these days. I am very confused about the job lifecycle, is there any "Stopping" phase? Because Polyaxon is fully asynced, when "Stop" called, there is a short moment that the real state of job being in "Stopping" status? Pls correct me, thanks very much!

**Comment by mouradmourafiq** [comment]
Stopping phase was not persisted in v0 and it's persisted in v1 that's why you see the short stopping phase in the UI in v0.

**Comment by huangyanjuner** [comment]
Thanks very much, v1 means version 1.0?

**Comment by mouradmourafiq** [comment]
1.0 or higher, It means the v1.x series :)

**Comment by huangyanjuner** [comment]
Thanks, but how could we get v1.x, in github? or it is just for enterprise edition?

**Comment by mouradmourafiq** [comment]
Currently only paying customers have access to v1, but the open source version should be accessible to everyone very soon. The charts, core, operator, and sdks have been already merged to github, the rest will follow soon.

**Comment by huangyanjuner** [comment]
@mouradmourafiq when the v1 is open source available, big features? I see the code of master branch changes a lot, would you pls advice me? thanks

**Comment by mouradmourafiq** [comment]
I answered your questions in #701
