### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by huangyanjuner** [polyaxon/polyaxon#701]
1. When will you publish the V1.0?
2. How the Quota Management works? any general idea will be welcome, is it included in the next open source version?
3. I am playing with v0.66. I could not see any TF Operator, Pytorch Operator  installed on the Cluster, however I see the Python code call or wrap the Operator. Would you pls clarify me?

**Comment by mouradmourafiq** [comment]
1. The first release of the v1 open source will be v1.1 (currently the project is in v1.0.76)
2. Quota management handled by Polyaxon is only on the commercial version, however users can add their own logic to the open source to achieve custom workflows.
3. Polyaxon v0 has 2 ways for achieving distributed traning: a built-in and a kubeflow integration. The kubeflow operators do not get deployed automatically, they are optional, please check the documentation for that: https://docs.polyaxon.com/integrations/kubeflow/
In v1, we dropped the built-in distributed logic in favor of better Kubeflow integration.

**Comment by mouradmourafiq** [comment]
>     1. The first release of the v1 open source will be v1.1 (currently the project is in v1.0.76)
> 
>     2. Quota management handled by Polyaxon is only on the commercial version, however users can add their own logic to the open source to achieve custom workflows.
> 
>     3. Polyaxon v0 has 2 ways for achieving distributed traning: a built-in and a kubeflow integration. The kubeflow operators do not get deployed automatically, they are optional, please check the documentation for that: https://docs.polyaxon.com/integrations/kubeflow/
>        In v1, we dropped the built-in distributed logic in favor of a better Kubeflow integration.
> 
> 
>     * More details on the workflow engine in  v1 is in this blog post: https://medium.com/polyaxon/streamlining-the-machine-learning-lifecycle-52867eeea29e
> 
>     * In the last one month and half the ui has seen a major rework, a new blog post about the new UI/Ux experience will be coming soon, as promised in this [comment](https://github.com/polyaxon/polyaxon/issues/708#issuecomment-612163250).
> 
>     * To check all issues raised by other users and fixed in v1, you can follow the label: [in-v1](https://github.com/polyaxon/polyaxon/issues?q=label%3Ain-v1+is%3Aclosed)

**Comment by huangyanjuner** [comment]
This is really good news. Thanks very much! To go towards the Kubeflow is really exciting.
How could we see the source code of v1.0.76? In the current main branch, the DB part, Celery, API have no code? Please correct me.
