### ISSUE TITLE
Custom visualization with images on the web UI

### ISSUE THREAD

**Issue by yu-iskw** [polyaxon/polyaxon#708]
### Feature motivation
I love the metrics visualization, but that is sometimes sufficient, such as AUC and ROC curve as well as it is impossible to support any type of vizualization methods on the web UI. So, if we can show images which are created in an experiment on the web UI, that would be very helpful. 

### Feature description
I am not sure the best place to show created images in an experiment on the web UI. The candidates are probably overview or outputs.

**Comment by mouradmourafiq** [comment]
Definitely something planned, a lot of viz features are in beta allowing to log [custom charts](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/tracking/__init__.py#L185) or [images](https://github.com/polyaxon/polyaxon/blob/master/core/polyaxon/tracking/__init__.py#L56), but predefined AUC/ROC/Confusion are also planned.

![Screenshot 2020-04-10 at 20 40 03](https://user-images.githubusercontent.com/1261626/79014589-7aca0b00-7b6b-11ea-8303-6fd10c2e8912.png)

I am also planning a blog post to introduce the new dashboard experience.

**Comment by yu-iskw** [comment]
That sounds very exciting!

**Comment by mouradmourafiq** [comment]
The new dashboard has been tested for over 10 days in production mode at some customers, it has still some bugs, but they reported more productivity compared to previous version. Polyaxon v1.0.8 will be released today for paying customers and it has a simple way to log roc/auc curve and pr curve in addition to the methods I linked to in the previous comment for logging custom plots.

The feature will be accessible to all Polyaxon open source users in v1.1.

<img width="1274" alt="Screenshot 2020-04-20 at 10 39 14" src="https://user-images.githubusercontent.com/1261626/79732284-be531080-82f3-11ea-9a5d-8a239042a719.png">

**Comment by yu-iskw** [comment]
Thank you for sharing. It sounds v1.1 will come soon. I can't wait!

**Comment by tangyong** [comment]
> Thank you for sharing. It sounds v1.1 will come soon. I can't wait!

+1 I can't wait!
