### ISSUE TITLE
Crash: Tensorboard event file has been deleted

### ISSUE THREAD

**Issue by ONordander** [polyaxon/polyaxon#710]
### Describe the bug
When running a training with Tensorboard logging, it fails randomly because the Tensorboard log file has been removed. It works fine up until the crash. Sometimes it crashes after 1000 iterations, sometimes after 10000.
`tensorflow.python.framework.errors_impl.UnknownError: The events file /polyaxon-outputs/root/training_pipeline/experiments/546/logs/train/events.out.tfevents.1586874951.plx-53a4089c2ae74fe08c529c5b14975334-master-0.1.3001.v2 has disappeared.`
### To Reproduce
Create PV/PVC for output paths.
Run a Keras training with a callback: Tensorboard(log_dir=get_outputs_path() + "/logs")

### Expected behavior
No crash

### Environment
In Kubernetes cluster, Tensorflow==2.0.0

**Comment by mouradmourafiq** [comment]
> because the Tensorboard log file has been removed.
How does the logs get removed?

**Comment by ONordander** [comment]
I don't know, the file just disappeared, I was thinking Polyaxon removed it somehow.
BTW, is that the intended way to use Tensorboard, just use the outputs_path for storage?

**Comment by mouradmourafiq** [comment]
> I don't know, the file just disappeared, I was thinking Polyaxon removed it somehow.

There must be something else, what type of PVC are you running, Polyaxon does not delete files, unless users push a button that says so, so I guess, there might be an issue, are you running a nfs volumne?

> BTW, is that the intended way to use Tensorboard, just use the outputs_path for storage?

Yes, in v1 the synstax has changed a bit, but it's required to pass a path where you want to store the logs, there's no monkey patching to give flexibility to the end user.

**Comment by mouradmourafiq** [comment]
Since there's no feedback, I am closing this issue. Most probably an issue with the user's cluster.

**Comment by ONordander** [comment]
Agree, I will check our storage configuration. Thanks for the quick reply!
