### ISSUE TITLE
Support for OAuth and external authenticators

### ISSUE THREAD

**Issue by elgalu** [polyaxon/polyaxon#73]
Hi, great project, do you plan support OAuth or external authenticators?

In a similar way [JupyterHub does](https://github.com/jupyterhub/jupyterhub/wiki/Authenticators)?

So far I only see one would need to deal with [user management and passwords within](https://docs.polyaxon.com/management/superusers/#acceptreject-new-user) this tool, which normally is better to outsource this to an external auth provider.

**Comment by mouradmourafiq** [comment]
HI @elgalu, it's definitely on the roadmap for `0.1.0`, both OAuth/external auth APIs as well as LDAP.

**Comment by mouradmourafiq** [comment]
@elgalu Would you be

**Comment by elgalu** [comment]
Hi, unfortunately not, we don't have any capacity left this quarter (Q2). And Q3 will probably be the same.

**Comment by mouradmourafiq** [comment]
What OAuth service did you have in mind, or you think that is more usable to introduce first?

**Comment by elgalu** [comment]
In our specific use case would be any of http://stups.readthedocs.io/en/latest/appendix/oauth-integrations.html but Google login or Github login would also be enough and probably a more general use case.

Given this project is Python maybe you can re-use JupyterHub auth mechanism. Though idk how coupled to tornado are they: https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/reference/authenticators.md

**Comment by mouradmourafiq** [comment]
Ldap, github, gitlab, and bitbucket are now supported and will be part of the next release.
