### ISSUE TITLE
Add gantt charts for DAG views

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#739]
### Feature motivation

At the moment users get only a view of all runs related to a DAG as a searchable table, although it's possible to use search: query/sort based on complicated combination of statuses and run time, there should be a simpler way for displaying progress.

### Feature description

Several users have been using the DAGs for more complex workflows, and asking for a gantt charts to better understand the pipeline progress.

### Feature implementation

Add a new tab with a gantt chart.

**Comment by denisoliveirac** [comment]
+1 :-)
