### ISSUE TITLE
Citation link

### ISSUE THREAD

**Issue by wkerzendorf** [polyaxon/polyaxon#773]
We are using Polyaxon in academic research and would like to cite your project. Unfortunatley, there is no DOI or other way given to cite this entry (a `bibtex` would be much appreciated). It would be great for this code to have a DOI and I recommend the free (EU and CERN funded) zenodo project that mints DOIs for open source projects. It's very easy. 

Thanks for making this great tool open source!!

**Comment by mouradmourafiq** [comment]
Hi @wkerzendorf, thank you for the nice words, and happy that you find the project useful.

You can refer to the citation page, thank you.
