### ISSUE TITLE
Add logs streaming to web ui

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#81]
Add experiment and job log views to the dashboard

**Comment by lgeiger** [comment]
Streaming logs would be really useful.

One could utilize something like https://mozilla-frontend-infra.github.io/react-lazylog/ to implement this on the react side.

**Comment by mouradmourafiq** [comment]
I will close this issue as fixed, a more detailed answer can be found in this thread #569.
