### ISSUE TITLE
Missing link in docs

### ISSUE THREAD

**Issue by vfdev-5** [polyaxon/polyaxon#814]
### Missing Documentation

1) Bad link to "EE & Cloud versions" in 
> "Has a sustainable business model with EE & Cloud versions ✅"

https://github.com/polyaxon/polyaxon/blob/master/site/docs/core/introduction/index.md

2) "Update page" button sends to missing page

<img width="961" alt="Screen Shot 2020-06-11 at 12 52 10" src="https://user-images.githubusercontent.com/2459423/84377157-79a47100-abe2-11ea-9722-149ab9942b63.png">

**Comment by mouradmourafiq** [comment]
The pricing page is not public yet, so I will keep the link until that page is shared.
