### ISSUE TITLE
User permissions for using different output APIs

### ISSUE THREAD

**Issue by mostafa-mahmoud** [polyaxon/polyaxon#829]
### Use case

In case a restricted user runs some code on the server on some confidential data (which is only present on the server, this user could have a small sample from it for development), then it can be a security flaw if he can download any data through the "outputs", "logs", "notebook" APIs. The flaw can happen by simply running a program that copies the confidential data to the output methods (outputs, API).

This flaw can be overcome if the user has restricted access to some of these APIs, then (s)he can check the results of the experiments through Tensorboard logs or so.

### Feature description

The superuser can change user permissions to download the outputs of an experiment through different APIs. (so they can't do it, or do it with some request permission per experiment or so)

**Comment by mouradmourafiq** [comment]
We have already several [roles](https://polyaxon.com/docs/management/ui/organizations/#organization-roles) for managing this advanced use cases. One way to solve this is to give the user(s) the outsider role. Members can also be demoted on specific team to get the outside role, in that case the user will only have read only mode.

This is not something we will be developing for the the open-source version, however you can put Polyaxon CE behind a reverse-proxy and intercept request and apply further rules that you think would fit your workflow.
