### ISSUE TITLE
duplicate logs on the web ui

### ISSUE THREAD

**Issue by chenglin** [polyaxon/polyaxon#845]
### Describe the bug
duplicate logs on the web ui

### To Reproduce

1. create a project on the web ui
2. polyaxon run -p quick-start2 -f experimentation/simple.yml
3. open web ui, repeat click `click 1` and `click 2`  for serveral times, there will be duplicate logs

![image](https://user-images.githubusercontent.com/1031972/85122320-f1187700-b258-11ea-8df6-ef4b58069de3.png)

4. duplicate logs
![image](https://user-images.githubusercontent.com/1031972/85122543-4c4a6980-b259-11ea-9939-e44ba57ff2ce.png)

5. After refresh by `F5`, there is one one left

note for reproduce:
1. delete image `polyaxon/polyaxon-quick-start`
2. limit network to 10M, so it will take long time to download image `polyaxon/polyaxon-quick-start`, that we can repeat click `click 1` and `click 2` during this.

### Expected behavior
there are no duplicate logs
### Environment
os: ubuntu 20.04
k8s: microk8s 1.18

**Comment by mouradmourafiq** [comment]
A fix will be part of the next release v1.1.6 with several other improvements in the logs viewer:
 * Faster rendering
 * Better handling of state changes
 * While streaming progress bars will update in-place instead of creating multiple lines
