### ISSUE TITLE
Gitlab login doesn't redirect back to original page

### ISSUE THREAD

**Issue by iliakur** [polyaxon/polyaxon#848]
### Current behavior

We have a polyaxon cluster set up to authenticate through gitlab. Whenever I'm not logged into my polyaxon account (for instance, at the beginning of the work day) and I happen to click on a link to some polyaxon resource like an experiment or a group of experiments, I'm asked to login, which makes sense. What's frustrating is that upon login I'm taken to my account homepage instead of the link I originally clicked. I then have to go back and click it again... 

### Enhancement

Ideally, after authenticating I'd get taken to the link I had to authenticate to access.

**Comment by mouradmourafiq** [comment]
Polyaxon CE does not provide the basic auth as of the last release v1.1.0.

There's a plan to open-source the full system, including auth. team management, and the permission system, but it's not a priority in the near future. 

Closing as wontfix.
