### ISSUE TITLE
Support for Nomad

### ISSUE THREAD

**Issue by notsimon** [polyaxon/polyaxon#854]
Setting up Polyaxon requires a Kubernetes cluster to be up and running, a software that is known to not be straightforward to manage. I find [Nomad](https://www.nomadproject.io) to be a very good alternative for a small-scale self hosted cluster made of heterogeneous machines.

Some time ago I have seen a couple mentions of Nomad on Polyaxon's home page, which is not the case anymore. It is also mentioned in the polyaxon/polyaxon-deploy repository.

What is the state of Nomad's support? What are the issues that might arise with it?

**Comment by mouradmourafiq** [comment]
Thank you so much for opening this issue.

At the moment our main focus is to provide a simple abstraction on top of Kubernetes. I am afraid that unless if Nomad is adopted by the ML community as an orchestration layer for leveraging computation resources across different special hardware and cloud providers, we cannot invest resources to support it.

There was a plan to offer Polyaxon tracking layer for docker-compose/nomad/..., but this is not a top priority right now. Although tracking is one of Polyaxon's features, and we will still provide a rich set of tracking and visualization interfaces,  tracking itself is not the main feature. We will focus on our main offering, i.e. tools for experimentation and automation, so scheduling and orchestration is at the core of what we do and I believe that we can only provide a robust solution by focusing on one orchestration layer which happen to be Kubernetes in this case.
