### ISSUE TITLE
Login to cluster

### ISSUE THREAD

**Issue by anthonytec2** [polyaxon/polyaxon#864]
### Unclear documentation

https://polyaxon.com/docs/setup/cli/
### Missing Documentation

I have tried to login to polyaxon using the client 1.0.5 with the server running 1.1.0-rc2.
I tried two separate ways to login: 
1) Specify command line password and username, and I get the error:
```
Could not login.
Error message: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Server': 'nginx/1.10.3', 'Date': 'Mon, 29 Jun 2020 12:25:48 GMT', 'Content-Type': 'application/json', 'Content-Length': '23', 'Connection': 'keep-alive', 'Vary': 'Accept, Origin, Cookie', 'Allow': 'GET, PUT, PATCH, DELETE, HEAD, OPTIONS', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"detail":"Not found."}
.
Status: 404. The resource you are looking for was not found. Check if the name or uuid is correct.
```

2) Just run polyaxon login and load from web browser, which goes to: 'http://10.10.10.230:80/app/token'
Although, this results in an error page:
```
Project was not found
```

In general how should we login in this new version?

**Comment by mouradmourafiq** [comment]
@anthonytec2 Polyaxon CE v1 has no auth mechanism or user management system
 * you can keep the default config with ClusterIP and use `polyaxon port-forward` or `kubectl port-forward`.
 * you can deploy Polyaxon CE behind  a reverse proxy.
 * you can deploy Polyaxon CE in a protected environment at the network level.

More details: https://github.com/polyaxon/polyaxon/blob/master/releases/1-1.md#backwards-incompatibilities
