### ISSUE TITLE
Unable to deploy Polyaxon v1.1.0 in_cluster, HTTP 413 error

### ISSUE THREAD

**Issue by ONordander** [polyaxon/polyaxon#868]
### Describe the bug
Unable to deploy Polyaxon v1.1.0 on an on-prem Kubernetes cluster using Helm/Polyaxon cli
Error:
```Polyaxon could not be installed.
Error message: `helm` command ('helm', 'install', 'polyaxon', 'polyaxon/polyaxon', '--namespace=polyaxon', '-f', 'polyaxon_config_v1.yml', '--version', '1.1.0') failed with exit status 1
stdout:

stderr:
Error: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)
.
```
### To Reproduce

`pip install -U polyaxon==1.1.0`

polyaxon_config_v1.yml
```
deploymentChart: platform
deploymentVersion: 1.1.0
```

`polyaxon admin deploy -f polyaxon_config_v1.yml`

### Expected behavior
Successful deploy.

### Environment
On-prem Kubernetes cluster, v1.17.3
```
pip freeze | grep polyaxon
polyaxon==1.1.0
polyaxon-sdk==1.1.0
```

```
helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ONordander** [comment]
We believe it has to do with the 1Mb size restriction of Kubernetes secrets, https://kubernetes.io/docs/concepts/configuration/secret/#restrictions.
So is there any way to reduce the size?

**Comment by mouradmourafiq** [comment]
The error is an nginx configuration limiting the payload to 1M, the CRD generated by kubebuilder is large, there are already several issues on the k8s-sig runtime to reduce the generated openApi configuration.

2 solution:
 * Remove the validation from the CRD
 * Change the annotation for the nginx proxy to allow larger payloads.
