### ISSUE TITLE
Experiment failed as zombie

### ISSUE THREAD

**Issue by yh-xu** [polyaxon/polyaxon#881]
### Describe the bug
Experiment failed as "Experiment is in zombie state (no heartbeat was reported)" , however it was actively logging outputs just a few seconds before failed. 

Here is experiment status : 
![image](https://user-images.githubusercontent.com/59196087/86442486-77948480-bd40-11ea-9e46-9f14b7eaa12b.png)
and this is last output before experiment was killed (the timestamp is in UTC and 8hr diff from my local time )
![image](https://user-images.githubusercontent.com/59196087/86442842-f8538080-bd40-11ea-8681-42d1c6fba5d6.png)

To troubleshoot a little bit, I checked logs of all polyaxon components. I found some errors logged half an hour (around 11:00, UTC time 3:00 ) before experiment failed (at 11:33).  
It seems some connection errors happend at 11:00, but as experiment continued outputing data before failed, the connection problem shouldn't last for a long period. I'm confused why the experiment was determined as zombie by polyaxon ?
== api ==
![image](https://user-images.githubusercontent.com/59196087/86444292-1cb05c80-bd43-11ea-9ec9-49a21f0c1d0f.png)
![image](https://user-images.githubusercontent.com/59196087/86444846-fc34d200-bd43-11ea-8323-559db5863791.png)
![image](https://user-images.githubusercontent.com/59196087/86445000-3aca8c80-bd44-11ea-9c64-48dd984ae2d1.png)

== polyaxon-beat-crons ==
![image](https://user-images.githubusercontent.com/59196087/86445233-98f76f80-bd44-11ea-869f-9ad78330491d.png)

== polyaxon-monitor ==
![image](https://user-images.githubusercontent.com/59196087/86446233-415a0380-bd46-11ea-8121-aed62229d4f6.png)

== redis ==
![image](https://user-images.githubusercontent.com/59196087/86445458-fa1f4300-bd44-11ea-808e-5317809aed0c.png)

### To Reproduce
Not sure how to reproduce. The problem happened 3 times today and yesterday, and I was running experiments just as what I did the day before.

### Expected behavior
Active experiments should not be killed as zombie.

### Environment
kubernetes v1.17
polyaxon v0.6.1

**Comment by mouradmourafiq** [comment]
Did you have any issues with Redis prior to this error.
I am not sure how Redis is deployed: persistence, auth, proximity to other core components, ...

Maybe we should just remove any persistence to disk all together for redis?

Also another question is how do you deploy Polyaxon, is redis the broker or are you using rabbitmq as a btoker. If I have to guess, I think the latter otherwise the whole system would not work.

**Comment by yh-xu** [comment]
> Did you have any issues with Redis prior to this error.
> I am not sure how Redis is deployed: persistence, auth, proximity to other core components, ...
> 
> Maybe we should just remove any persistence to disk all together for redis?
> 
> Also another question is how do you deploy Polyaxon, is redis the broker or are you using rabbitmq as a broker. If I have to guess, the latter is the broker otherwise the whole system would not work.

Here is redis log prior to the error.
![image](https://user-images.githubusercontent.com/59196087/86450290-ddd2d480-bd4b-11ea-9f42-132f7221158e.png)

I followd the default value in polyaxon v0.6.1 chart to deploy redis. It's master persistence enabled. Redis is the broker.

**Comment by yh-xu** [comment]
one thing to add: actually all the experiments got kill at the same time for zombie state, and after that new experiments still can be executed as normal.

**Comment by mouradmourafiq** [comment]
Ok, seems like Redis has issues, though tuning Redis is not in the scope of Polyaxon, I would suggest to remove Redis persistence and redeploy:
```
redist:
  master:
    persistence: {enabled: false}
  slave:
    persistence: {enabled: false}
```
I would make sure that redis is being redployed, if not, delete Redis and Redis PVC manually.

**Comment by mouradmourafiq** [comment]
> one thing to add: actually all the experiments got kill at the same time for zombie state, and after that new experiments still can be executed as normal.

Heartbeat service uses Redis as a store, if Tedis is not working then all Experiments will not be able to report heartbeats.

The heartbeat service was removed from the open-source distro in v1 to make deployment easier and simpler to reason about. I expect all these issues to be resolved in v1 if you have time to deploy the new version.

**Comment by yh-xu** [comment]
Thanks Mourad. Is it recommended to enable broker ? my situation is to set up a stable infrastructure for multiple users to schedule their trainings.

**Comment by mouradmourafiq** [comment]
General rule (I am not sure if this is already in the docs, if not we should add it):

 * First step is to deploy Polyaxon without scheduler, your deployment will be very simple to reason about.
 * If you have performance issues, I would start first by scaling the API, more replicas means handling more requests but also more availability (there's also a plan to provide an easy way to tune the API threads to leverage strong machines)
 * There's an HPA (horizontal pod auto-scaling) in the new helm chart for all components.
 * If you are using a producer (e.g. kafka or an external service) where you don't control the number of submissions or if you are using an external system to produce a large of number of experiments (e.g. optimization system) and you want to improve latency, you can then think about enabling the scheduler.
 * In v1 you can always enable and disable the scheduler, it won't impact your Polyaxon deployment, it should be just a simple upgrade.
 * The scheduler only requires a single dependency (Redis or Rabbitmq) if you did not have any issues with the built-in Rabbitmq in the last couple of months, then you shouldn't have any problem with it in the new version, not only the scheduler handles less traffic but all the heavy tasks are running in Kubernetes native Go module.

Please read the release notes for backwards incompatibilities, and make sure to deploy Polyaxon CE in a protected network, the CE version does  not provide any auth mechanism anymore.

**Comment by mouradmourafiq** [comment]
Closing this issue, feel free to reopen.
