### ISSUE TITLE
Typo in CLI command of "New Project" tip

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#883]
### Describe the bug

When creating a new project from the UI, Polyaxon shows the following dialog:
![Screenshot 2020-07-06 at 12 45 20](https://user-images.githubusercontent.com/13285808/86585954-786b2780-bf87-11ea-8fe9-441972533dac.png)

It recommends to run `polyaxon project create -h` for more information, but the command fails with:
```
$ polyaxon project create -h
Usage: polyaxon project create [OPTIONS]
Try "polyaxon project create --help" for help.

Error: no such option: -h
```
### To Reproduce
Try to run `polyaxon project create -h` as mentioned in the tip.

### Expected behavior

The tip should recommend using `polyaxon project create --help` which will give the desired output.

### Environment
Polyaxon CE v1.1.0

@mouradmourafiq I would've made a PR to fix this typo, but I couldn't find the UI code of Polyaxon. Is the UI currently not open-source or am I just missing something?

**Comment by mouradmourafiq** [comment]
Should be fixed for today's release 👍

**Comment by mouradmourafiq** [comment]
> @mouradmourafiq I would've made a PR to fix this typo, but I couldn't find the UI code of Polyaxon. Is the UI currently not open-source or am I just missing something?

The UI is currently a free non open-source project, it's used for both products, not sure when it will be possible to make it as an installable for the commercial product, so we can open-source the core. For now we removed all code duplication.

For users who want a 100% open-source  project, they need to turn-off the flag `uiEnabled: false`

**Comment by lgeiger** [comment]
Sounds good, I was just wondering whether I missed something.

**Comment by mouradmourafiq** [comment]
The wording in the docs has been changed as well in several places prior to the v1.1 release to something like this `Polyaxon CE is our free community edition based on Polyaxon open-source tools`
