### ISSUE TITLE
TensorBoard Hub component doesn't have "latest" tag

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#885]
### Describe the bug

When following https://polyaxon.com/integrations/tensorboard/ to deploy a TensorBoard service the first command fails since `/polyaxon/polyaxon-hub/master/tensorboard/latest.yaml` doesn't exist. Either a default TensorBoard component is missing on the public Hub or the docs need to be updated.

### To Reproduce
Run `polyaxon -v hub --name=tensorboard get` which will fail with:
```
$ polyaxon -v hub --name=tensorboard get
Starting new HTTPS connection (1): raw.githubusercontent.com:443
https://raw.githubusercontent.com:443 "GET /polyaxon/polyaxon-hub/master/tensorboard/latest.yaml HTTP/1.1" 404 14
Could not get component `tensorboard`.
Error message: Component `tensorboard` was not found, please check that the name and tag are valid.
```

### Expected behavior

Command succeeds and gets info for the TensorBoard component.

### Environment

Polyaxon CE v1.1

**Comment by mouradmourafiq** [comment]
Yes, I am aware of this one, the docs get generated for all components, may be we should just make a `latest` version similarl to `single-run`.
