### ISSUE TITLE
Improve collapsed sidebar 

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#891]
### Current behavior

For new users it is not clear what the icons mean when the sidebar is collapsed and in my opinion the tooltips are delayed too much to be very useful in practice. #890 increases the problem since it the sidebar can't be locked to learn the meaning of the icons.
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/13285808/86639286-f4da2680-bfd8-11ea-971c-36bb5a7704f4.gif)

### Enhancement

I think something similar to GCP would be quite nice:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13285808/86639978-24d5f980-bfda-11ea-8bbc-c121eff44440.gif)

**Comment by mouradmourafiq** [comment]
@lgeiger thank you for opening this issue, it will be part of the next release v1.1.7.

I just wanted to ask, what tool did you use for creating these gifs :)

**Comment by lgeiger** [comment]
> thank you for opening this issue, it will be part of the next release v1.1.7.

Great, thanks.

> I just wanted to ask, what tool did you use for creating these gifs :)

I sometimes use https://getkap.co/. Though if I recall correctly these GIFs were created with the default macOS Screenshot app and then converted from mp4 to GIF using some online converter.
