### ISSUE TITLE
Store filters in URL query parameter

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon#892]
### Current behavior

The new filter query syntax is great for selecting and comparing multiple different runs. Unfortunately it is not possible to share the a link to those search results as the filter queries are not represented in the URL query parameters anymore. This would allow to have sharable links to filters similar to v0.x. I think this can be quite useful especially since it looks like the option to group experiments has been removed moving from v0.x to 1.1 CE and saved searches only seem to be available in the commercial offering.

### Enhancement

It would be great if Polyaxon v1.1 would store filters in URL query parameters again or have the ability to create a link to search results so selections can be preserved.

**Comment by mouradmourafiq** [comment]
Related to #716 #682
These 2 issues were scheduled for v1.1, and were considered a blocker for a long time for the CE version, since it's possible to persist the query in the commercial offering. they were moved to v1.2 to make a first release of the open-source version.

**Comment by lgeiger** [comment]
Thanks, sorry I didn't find #716 before which is indeed the same issue.
