### ISSUE TITLE
Changing default namespace in helm chart doesn't effect polyaxon-operator -- jobs stuck in queue

### ISSUE THREAD

**Issue by patryk-s** [polyaxon/polyaxon#900]
### Describe the bug
Deploying to a different namespace than `polyaxon` leaves all experiments in *queued* state.
After some time, I figured out that the `polyaxon-operator`'s `--namespace` config option is not set, and it doesn't use the `POLYAXON_K8S_NAMESPACE` env from `polyaxon-config` configMap (I guess it's expecting `NAMESPACE`) 
### To Reproduce
```bash
helm install polyaxon polyaxon/polyaxon --namespace=polyaxon1 -f config.yaml
polyaxon project create --name=quick-start --description='Polyaxon quick start.'
polyaxon run --url=https://raw.githubusercontent.com/polyaxon/polyaxon-quick-start/master/experimentation/simple.yml
```
NOTE: I have `namespace: polyaxon1` in `config.yaml`
### Expected behavior
Experiment starts.
### Environment
Kubernetes

**Comment by mouradmourafiq** [comment]
A new release v1.1.3 for Polyaxon CE will be made in the next few minutes including a patch for this. Thanks for reporting.
