### ISSUE TITLE
Randomly missing output artifacts when using get_output_paths()

### ISSUE THREAD

**Issue by stefankraft** [polyaxon/polyaxon#945]
### Describe the bug
When getting the path to the default artifacts store via get_output_path() (either from client or module reference) and storing many (tested with 200) randomly generated images on the default artifacts store leads to some images randomly missing on the storage (typically one to three images missing). In the run container all artifacts are present though.
This was tested with a persistent volume as artifacts store as well as a host_path.
This behavior does not appear when accessing the artifacts store via the mountPath directly.

### To Reproduce
Reproduce by running the following component:
`polyaxon run --url=https://raw.githubusercontent.com/stefankraft/polyaxon/bugreport_artifact_store/run_dummy_output.yml -l`

The expected behavior as describe above when using the mountPath directly can be reproduced by:
`polyaxon run --url=https://raw.githubusercontent.com/stefankraft/polyaxon/bugreport_artifact_store/run_dummy_output.yml -l -P show_expected=true`

The above components expect the following default artifact store name and mountPath
`artifactsStore:
  name: artifacts
  kind: volume_claim
  schema:
    mountPath: "/plx-artifacts"
    volumeClaim: "artifacts"`

### Expected behavior
All 200 images are stored on the artifacts store (PV or hostPath).

### Environment
Kubernetes 1.17.6
Polyaxon 1.1.5

**Comment by mouradmourafiq** [comment]
Thanks for opening this issue, this was very subtle and due to milliseconds. The monitor now base the check on the last state of the whole context.
The fix was tested several times with several storage backends: host paths, PVC, Azure, GCS, and Minio/S3.
