### ISSUE TITLE
Add metrics visualisation to the dashboard

### ISSUE THREAD

**Issue by mouradmourafiq** [polyaxon/polyaxon#95]
Polyaxon relies heavily on Tensorboard for visualisation, but some frameworks and libraries do not support Tensorboard.

Polyaxon should provide basic visualisation for all metrics collected during the training.

**Comment by gzcf** [comment]
For other frameworks and libraries, people can use [tensorboardX](https://github.com/lanpa/tensorboard-pytorch) to write tensorboard events, and leverage tensorboard   to visualize metrics.

**Comment by mouradmourafiq** [comment]
@gzcf you are right this could be an option. It is especially quite practical for comparing experiments on group or project level.
I will try to put together a tutorial or add a guide in the documentation on how to use it to leverage Tensorboard for other frameworks and libraries. It could be also done automatically by Polyaxon.

Nevertheless, I think on experiment level and especially for metrics that the user which to collect either because they are used for the search algorithms or for early stopping, or just to have quick insight on the dashboard, to add charts. It does not have to be a full-blown Tensorboard type of visualizations.

For example, I imagine lightweight line graphs that give a quick overview. If the user wishes to drill further, she can use Tensorboard.

What do you think?

List standalone Tensorboard implmentations:

 * https://github.com/lanpa/tensorboard-pytorch
 * https://github.com/dmlc/tensorboard
 * https://github.com/TeamHG-Memex/tensorboard_logger
 * https://github.com/lspvic/jupyter_tensorboard
 * https://github.com/torrvision/crayon
 * https://github.com/jimgoo/zipline-tensorboard

**Comment by gzcf** [comment]
Yeah, providing basic visualization is still useful.

**Comment by honnibal** [comment]
Visdom looks pretty good: https://github.com/facebookresearch/visdom

I've been using TensorboardX, and I have to say I'm not that thrilled by Tensorboard...It's incredibly slow!

**Comment by rogerzklotz** [comment]
This is definitely something we would love to have included in Polyaxon. Do we have any specs on what this should allow or how it should work/behave?

**Comment by mouradmourafiq** [comment]
Since th release `0.1.3`, it's possible to see line charts for all metrics reported to polyaxon:

<img width="1279" alt="screen shot 2018-07-30 at 15 00 18" src="https://user-images.githubusercontent.com/1261626/43398790-5a3ed1a4-9409-11e8-9dd1-b747766ce165.png"> 

This is a first version, and the platform will either improve on this or provide a simple integration with a visualization framework.
