### ISSUE TITLE
Unable to perform cli commands

### ISSUE THREAD

**Issue by akshatgit** [polyaxon/polyaxon#977]
### Describe the bug
I have Polyaxon(version 1.1.6) running in k8s and also installed the latest polyaxon-sdk.
Now I am connecting polyaxon-api service over kube proxy on port 8000 and want to use polyaxon cli to connect to cluster. However, none of the cli command is working. 
Logs from polyaxon-polyaxon-api pod:
```
WARNING 2020-08-06 16:58:04,832 log 110 140278000072448 Not Found: /api/v1/versions/cli/
[pid: 110|app: 0|req: 1389/5553] 127.0.0.1 () {44 vars in 544 bytes} [Thu Aug  6 16:58:04 2020] GET /api/v1/versions/cli/ => generated 23 bytes in 15 msecs (HTTP/1.1 404) 6 headers in 203 bytes (1 switches on core 0)
```

### To Reproduce

- Install polyaxon on k8s via helm
- Install polyaxon sdk via pip
- kubectl port-forward -n polyaxon svc/polyaxon-polyaxon-api 8000:80
- polyaxon project ls
### Expected behavior

List the projects
### Environment
Kube on GKE. 

Please let me know if I have made any mistake. I have tried `kubectl port-forward -n polyaxon svc/polyaxon-polyaxon-gateway 8000:80` also, hoping this would complete the request. 

Thanks,
Akshat

**Comment by mouradmourafiq** [comment]
`kubectl port-forward -n polyaxon svc/polyaxon-polyaxon-gateway 8000:80` is the correct way to expose the service, and you need to configure the CLI : `polyaxon config set --host=http://localhost:8000`.

You can avoid all this and run: `polyaxon port-forward` which will expose the correct service and configure the CLI automatically.

**Comment by akshatgit** [comment]
```
➜  ~ polyaxon project ls
Request to http://localhost:8000/api/v1/versions/cli/ failed with status code 404.
Reason: <!DOCTYPE html>
<html>
<head>
    <title>Polyaxon</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" href="/static/images/favicon.ico?version=1"/>
    <link href="/static/vendors/fonts/fonts.css" media="all" rel="stylesheet" type="text/css"/>
    <base href="/">
    <link href="/static/dist/css/global.min.css" media="all" rel="stylesheet" type="text/css"/>
</head>

<body>
<div id="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <div class="jumbotron jumbotron-action">
                <div class="text-center">
                    <img src="/static/images/404.svg" alt="404" height="300">
                </div>
                <div id="main">
                    <p>The page you requested does not exist.</p>
                    <h3><a href="/" title="home" class="brand">Polyaxon</a></h3>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Could not get cli version.
Error message `404 on http://localhost:8000/api/v1/versions/cli/.`.
```
Still getting the same 404 error message after port forwarding the gateway.

**Comment by mouradmourafiq** [comment]
can you run `polyaxon version` and `pip freeze | grep polyaxon`?

**Comment by akshatgit** [comment]
Got the issue.. I had installed cli using this: `pip3.7 install -U polyaxon-cli` and it installed old client.
Thanks for your help, please close the issue.

**Comment by Ruchit1395** [comment]
Can you let me know the right way to install the polyaxon-cli package? ( I'm currently facing the exact same problem )

I've already tried so and so methods:

`pip3 install -U polyaxon-cli
pip install -U polyaxon-cli
`
The cli did not work in either of the cases.

**Comment by akshatgit** [comment]
@Ruchit1395 , the correct way is to install `pip install -U polyaxon`. It is mentioned [here](https://polyaxon.com/docs/core/python-library/).

**Comment by Ruchit1395** [comment]
Somehow doing that install the '0.0.0' version of the package and doesn't provide the executable

`bash: /usr/local/bin/polyaxon: No such file or directory`

```
>> sudo pip install -U polyaxon

Requirement already up-to-date: polyaxon in /usr/local/lib/python2.7/dist-packages (0.0.0)
Requirement already satisfied, skipping upgrade: six==1.11.0 in /usr/local/lib/python2.7/dist-packages (from polyaxon) (1.11.0)
```

```
>> sudo pip freeze | grep polyaxon

polyaxon==0.0.0
```

**Comment by mouradmourafiq** [comment]
@Ruchit1395 Polyaxon v1 does not support `python2.7`, you need `python3.5+` to use polyaxon cli.

**Comment by mouradmourafiq** [comment]
You should be able to create a [virtualenv](https://virtualenv.pypa.io/en/stable/installation.html) with python3 or conda.

I also suggest that you don't install Polyaxon on your default python system.

**Comment by Ruchit1395** [comment]
@mouradmourafiq @akshatgit 
Current version of python3 and pip3
```
python3 --version
Python 3.6.11
```

```
pip3 --version
pip 20.2.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```
---

Installed using the command
```
pip3 install -U polyaxon
```
Once installation is successful, executing polyaxon cli throws this error.
```
$$$ polyaxon version
Traceback (most recent call last):
  File "/usr/local/bin/polyaxon", line 5, in <module>
    from polyaxon.main import cli
  File "/usr/local/lib/python3.6/dist-packages/polyaxon/main.py", line 23, in <module>
    from polyaxon.cli.admin import admin
  File "/usr/local/lib/python3.6/dist-packages/polyaxon/cli/admin.py", line 23, in <module>
    from polyaxon.managers.deploy import DeployManager
  File "/usr/local/lib/python3.6/dist-packages/polyaxon/managers/deploy.py", line 22, in <module>
    from polyaxon.client.transport import Transport
  File "/usr/local/lib/python3.6/dist-packages/polyaxon/client/__init__.py", line 19, in <module>
    from polyaxon.client.run import RunClient
  File "/usr/local/lib/python3.6/dist-packages/polyaxon/client/run.py", line 49, in <module>
    from polyaxon.utils.code_reference import get_code_reference
  File "/usr/local/lib/python3.6/dist-packages/polyaxon/utils/code_reference.py", line 19, in <module>
    from polyaxon.utils.cmd import run_command
  File "/usr/local/lib/python3.6/dist-packages/polyaxon/utils/cmd.py", line 22, in <module>
    from psutil import Popen
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 68, in <module>
    from . import _pslinux as _psplatform
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 24, in <module>
    from . import _psutil_linux as cext
ImportError: cannot import name '_psutil_linux'
```

Thanks for responding immediately.

**Comment by mouradmourafiq** [comment]
this seems like an issue with psutil, there's a solution here https://github.com/giampaolo/psutil/issues/1288

**Comment by Ruchit1395** [comment]
Thanks for your support. The issue is resolved now.

**Comment by mouradmourafiq** [comment]
Actually we can remove the default `psutils` requirement, it's only used for tracking module.
